### ISSUE TITLE
nonWF + addNewMutation() + tree sequence = incorrect?

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#102]
The discussion of mutation time in #101 reminded me of something that's been nagging at me: right now - I think - if an individual (a) has kids, (b) has a mutation added to them by Eidos, then (c) has more kids, the genotypes in the resulting tree sequence won't be right for the kids produced in (a). We talked about this, but decided that it was a corner case that'd we'd punt on. Unless we actually fixed it and I forgot?

I think there's two solutions: (1) disallow manually adding mutations in a nonWF model to age > 0 individuals with tree sequence recording turned on, or (2) when this happens, effectively insert a clonal reproduction step before the mutation is added, so that the parent in step (a) and the parent-at-the-later-time in step (b) are represented by different individuals in the tree sequence (but they could have the same SLiM ID in metadata, even?).

**Comment by bhaller** [comment]
Yikes.  I don't remember ever talking about this.  I think (1) strikes me as the correct solution.  (2) is too sneaky/weird.  I don't think we need to support mutations within the lifetime of an individual.  If someone really, really wants to do that, they could do it themselves with clonal reproduction as you suggest; but I don't think we want to do it for them.  I'd even go so far as to say that implementing (1) would be a useful service to most users, because adding a mutation to a non-new individual is probably a bug in their model, not an intentional behavior.  (Most users, not all users, of course.)

**Comment by petrelharp** [comment]
I'm all for (1). But: mutations-during-the-lifetime is totally a thing that happens; suppose that someone wants to study the evolutionary effects of the association between father's age and number of mutations inherited by the offspring (the association for mother's age is, IIRC, positive but less strong). So maybe the error should say that "if you really want to do this, then please open an issue on github".

**Comment by bhaller** [comment]
> I'm all for (1). But: mutations-during-the-lifetime is totally a thing that happens; suppose that someone wants to study the evolutionary effects of the association between father's age and number of mutations inherited by the offspring (the association for mother's age is, IIRC, positive but less strong). So maybe the error should say that "if you really want to do this, then please open an issue on github".

Yes; not saying that it's not a thing, just that it's not a thing that I have heard of anybody wanting to model in SLiM.  :->  And it's not a thing that tskit supports; so it probably doesn't need to be a thing that SLiM supports.

**Comment by bhaller** [comment]
Trivial test model:

```
initialize() {
	initializeSLiMModelType("nonWF");
	initializeTreeSeq();
	defineConstant("K", 500);
	
	initializeMutationType("m1", 0.5, "f", 0.0);
	m1.convertToSubstitution = T;
	initializeMutationType("m2", 0.5, "f", 0.1);
	
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeMutationRate(1e-7);
	initializeRecombinationRate(1e-8);
}
reproduction() {
	subpop.addCrossed(individual, subpop.sampleIndividuals(1));
}
1 early() {
	sim.addSubpop("p1", 10);
}
early() {
	p1.fitnessScaling = K / p1.individualCount;
}
5 early() {
	inds = p1.individuals;
	ages = inds.age;
	adults = inds[ages > 0];
	target = sample(adults, 1);
	targetGenome = target.genome1;
	targetGenome.addNewDrawnMutation(m2, 1000);
}
2000 late() { sim.outputFixedMutations(); }

```

**Comment by bhaller** [comment]
It runs without any error, so clearly we did not address this issue.  :->  The fix is easy, will commit soon.

**Comment by petrelharp** [comment]
Phew. Thanks for closing that one. (Did you update the documentation?)

**Comment by bhaller** [comment]
> Phew. Thanks for closing that one. (Did you update the documentation?)

I'm not really sure that's even needed; the error message will be pretty self-explanatory for anyone who tries it.  Or do you think I should note the limitation in the `addNewMutation()` / `addNewDrawnMutation()` / `addMutations()` reference doc?  It just feels like such an unusual/edge case that maybe it's not even worth mentioning.

**Comment by petrelharp** [comment]
I do think you should add the note: anyone wanting to use those methods in a nonwf model will need to know it.

**Comment by bhaller** [comment]
OK, done.
