### ISSUE TITLE
chromosome length with tree sequence recording

### ISSUE THREAD

**Issue by mufernando** [MesserLab/SLiM#112]
Suppose you are going to perform simulations with tree sequence recording and not simulate any neutral mutations in SLiM. Then, you define your mutations types (all not neutral) and assign them to some genomic element types. If the last bit of the chromosome you want to simulate is a "neutral only" region, then SLiM has no way of knowing the exact chromosome length unless you create a GenomicElement at the very end of the chromosome.

I think the way this works feels a bit "hacky"/inconsistent. Why can I not specify genomic elements for all the other neutral regions but have to for the last bit of the chromosome? This could be solved by allowing a chromosome length parameter in `initializeTreeSequence` or even as a property of a SLiM simulation, but not sure what the best approach would be here.

cc @petrelharp, @grahamgower

**Comment by mufernando** [comment]
I was just rereading the manual and this little section wouldn't work in practice because of the issue I described.

![image](https://user-images.githubusercontent.com/9950100/96756981-ad11bc00-1389-11eb-8ba0-9f0f0a78def9.png)

**Comment by bhaller** [comment]
Hi @mufernando.  The actual length of the chromosome is max(end of last genomic element, end of last recombination region).  So if you want to make the chromosome extend past the end of the last genomic element, just pass your desired end position to `initializeRecombinationRate()`.  I'm going to close this since I think there is no bug here, but feel free to reopen it if this solution doesn't work for you.  :->

**Comment by mufernando** [comment]
Hi, Ben, thanks for the quick reply! 

Yes, that works! I didn't know that the recombination map end coordinate was also used to determine the chromosome length. When using a flat recombination maps I rarely specify the ends.

I think it would be worth it to spell this out somewhere in the manual if it isn't there already? One appropriate place could be in the description of `lastPosition` within the `Chromosome` class.

**Comment by bhaller** [comment]
Done, thanks for the suggestion.
