### ISSUE TITLE
needs a bunch of built-in functions that compute useful pop-gen things

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#118]
So, building upon the new LogFile class (https://github.com/MesserLab/SLiM/issues/114), it would be great to have a suite of functions in SLiM that compute useful pop-gen statistics – things like heterozygosity, FST, genetic variance, etc.  The more the merrier.  Then LogFile can automatically write these things out, and it becomes vastly easier to write a simulation that has detailed statistical logging included.  The main reason that SLiM doesn't already have such functions is that both my math skills and my pop-gen chops aren't really up to it.  This issue is therefore a call to the community to divvy up this work and contribute it, and I will integrate it all into SLiM.  Of course I'm happy to advise on the fastest way to do this or that in Eidos, etc.

The implementations should probably be in Eidos.  As long as they're done in a vectorized fashion, they ought to be efficient enough; and it will be far simpler than doing the calculations in C++ using SLiM's C++ objects, which are much more complex in their internals.  The implementations would then get built into SLiM; so they'd be like Eidos user-defined functions that are automatically loaded at startup, more or less.

For consistency, and so that they group nicely in doc and code completion and so forth, I would suggest that they should all have names that start with `calc`; so `calcHeterozygosity()`, etc.  And they should all be functions that can accept data in as general a form as makes sense; so if it made sense to have a generalized heterozygosity function like `calcHeterozygosity(object<Genome> genomes)`, that would probably be better than `calcHeterozygosity(object<Individual>$ individual)` or `calcHeterozygosity(object<Subpopulation>$ subpop)` or whatever.  Let the user work with whatever samples/genomes/individuals they want, for maximal generality.

Maybe I'll start a checklist here at the top, and I'll add to it / modify it according to the discussion that hopefully ensues:

- [x] `calcHeterozygosity(object<Genome> genomes)`
- [x] `calcFST(object<Genome> genomes1, object<Genome> genomes2)` @bhaller 
- [x] `calcVA(object<Individual> individuals)` (additive genetic variance) @bhaller
- [ ] ...what else?...

Writing the doc for these functions would be part of the work involved here, of course, and then I'd integrate that doc into the SLiM manual.  A key consideration would be to specify _precisely_ what the function does, to avoid confusion.  For heterozygosity, for example: is it computing observed or expected heterozygosity?  If it samples from a vector of genomes, is that with or without replacement?  How are stacked mutations treated by the algorithm?  How would sites that are multiallelic be treated?  Is there anything surprising about the implementation choices made?  Are there any assumptions made under the hood that might be violated in some models?

OK, that's enough rambling.  I'll tag @petrelharp @vsbuffalo @samchamper @ianvcaldas @grahamgower for now.  Feel free to tag others; I actually don't know GitHub handles for other Messer Lab members :-O.  If you are willing to take on a particular function, just say so and I'll put your name next to it in the checklist.  Oh, and timeframe: I don't see this as being a big rush, and probably it mostly won't make it into the upcoming SLiM 3.5 release (although it'd be great if it did), but I do want it to actually happen and not just stagnate.  :->

**Comment by bhaller** [comment]
Regarding heterozygosity, SLiM-Extras currently has this:

```
/*
  Given two haploid genomes, the number of segregating sites between the two, divided by the length of the chromosome, is pi, the average nucleotide heterozygosity, which is the standard measure for the genetic diversity in a population.  The expected value of pi is 4*Ne*mu for a pure neutral model.
  Note that this function assumes that L is a defined constant, the length of the chromosome; if you don't want to define that constant, you will need to pass in the chromosome length as a parameter instead.
*/
function (f$)genomicHeterozygosity(o<Genome>$ genome1, o<Genome>$ genome2)
{
	muts1 = genome1.mutations;
	muts2 = genome2.mutations;
	unshared = setSymmetricDifference(muts1, muts2);
	pi = size(unshared) / L;
	return pi;
}

/*
  Estimate the average nucleotide heterozygosity in a subpopulation by sampling individuals at random and averaging the heterozygosity of all of the individuals sampled.  Note that this function normally uses a sample of individuals, of a size supplied in the optional parameter sampleSize; but if sampleSize is equal to the number of individuals in subpop, it will instead compute the heterozygosity exactly, as the mean of the heterozygosities of all individuals, rather than taking a sample.  For large subpopulations, that will of course be much slower than using a sample, however.
*/
function (f$)subpopHeterozygosity(o<Subpopulation>$ subpop, [i$ sampleSize=100])
{
	if (sampleSize == subpop.individualCount)
		sampledIndividuals = subpop.individuals;
	else
		sampledIndividuals = sample(subpop.individuals, sampleSize, replace=T);
	
	pi_total = 0;
	for (individual in sampledIndividuals)
	{
		genomes = individual.genomes;
		individual_pi = genomicHeterozygosity(genomes[0], genomes[1]);
		pi_total = pi_total + individual_pi;
	}
	return pi_total / sampleSize;
}
```

So the naming and the API would probably need to be cleaned up, and it probably should just get passed a vector of genomes rather than taking a sample from a subpopulation itself; that was a bad design.

Also, as per a recent slim-discuss thread (https://groups.google.com/g/slim-discuss/c/ObR1qPeVv6k), this doesn't really do the right thing when there is more than one segregating mutation at a given site; it kind of makes the infinite-sites assumption that any given site is (at most) biallelic.  In the thread, I said maybe a good fix for that issue would be:

```
function (f$)genomicHeterozygosity(o<Genome>$ genome1, o<Genome>$ genome2)
{
    muts1 = genome1.mutations;
    muts2 = genome2.mutations;
    unshared = setSymmetricDifference(muts1, muts2);
    unshared_positions = unique(unshared.position, preserveOrder=F);
    pi = size(unshared_positions) / L;
    return pi;
}
```

This uniques the positions of the unshared mutations, so that if a site is multiallelic it still just gets counted once.  I'm not sure whether that's the right solution, or whether there's a better approach.  But anyway, that's the current state of things with heterozygosity, for whoever wants to sign up to un-muddle it.  :->

**Comment by bhaller** [comment]
Regarding FST, SLiM-Extras has an FST calculator that may or may not be robust/reusable, at https://github.com/MesserLab/SLiM-Extras/blob/master/functions/calcFST.txt:

```
function (f$)calcFST(o<Subpopulation>$ subpop1, o<Subpopulation>$ subpop2)
{
	p1_p = sim.mutationFrequencies(subpop1);
	p2_p = sim.mutationFrequencies(subpop2);
	mean_p = (p1_p + p2_p) / 2.0;
	H_t = 2.0 * mean_p * (1.0 - mean_p);
	H_s = p1_p * (1.0 - p1_p) + p2_p * (1.0 - p2_p);
	fst = 1.0 - H_s/H_t;
	fst = fst[!isNAN(fst)];  // exclude muts where mean_p is 0.0 or 1.0
	return mean(fst);
}
```

I notice that it just calculates overall FST between two subpopulations; maybe it would be nice if it had an optional `[No<Mutation> mutations = NULL]` argument that allowed one to specify a particular set of mutations to do the calculation with?

**Comment by grahamgower** [comment]
> both my math skills and my pop-gen chops aren't really up to it

I'm right there with you! But nonetheless happy to contribute where I can.

> should [CalcFst] really just take two subpopulations? does anyone compute FST between two arbitrary sets of genomes that aren't subpopulations?

I think arbitrary sets of genomes. There's probably lots of good reasons to group individuals in ways other than their subpopulation label, such as geographical location, presence/absence of a specific allele, inferred trait value for a QTL, or simply to pool subpopulations together.

**Comment by bhaller** [comment]
I'll take FST, since I think I understand how to calculate it correctly.

**Comment by petrelharp** [comment]
> I'll take FST, since I think I understand how to calculate it correctly.

A bold claim. ;)

**Comment by petrelharp** [comment]
So, "number of offspring so far" is a good metric. I've done this by giving every individual a `tag` that starts at zero when born and increments by one with every `reproduction` callback. I guess I could write eidos code that would register a `modifyChild` callback that would do the same thing in both nonWF and WF models. Then, this code would have to be run for the logger to work. So, I guess it'd be wrapped in a function, like `addNumOffspringLogger(log, subpop)`.

If this sounds good, no need to reply, I'll do this. But if you have a better idea, lmk. We also discussed in #114 implementing it at a low level. But maybe @bhaller is right - this isn't a common enough thing to warrant the overhead in all sims. I tend to just turn on logging in test runs, then turn it off in the big, for-reals simulation runs, for instance.

**Comment by bhaller** [comment]
> > I'll take FST, since I think I understand how to calculate it correctly.
> 
> A bold claim. ;)

I know!  But there's code for it in one of the recipes, and after revising it twice in response to people saying that it was wrong, things have been quiet for a while now, so maybe now it's actually right.  :->

**Comment by bhaller** [comment]
> So, "number of offspring so far" is a good metric. I've done this by giving every individual a `tag` that starts at zero when born and increments by one with every `reproduction` callback. I guess I could write eidos code that would register a `modifyChild` callback that would do the same thing in both nonWF and WF models. Then, this code would have to be run for the logger to work. So, I guess it'd be wrapped in a function, like `addNumOffspringLogger(log, subpop)`.
> 
> If this sounds good, no need to reply, I'll do this. But if you have a better idea, lmk. We also discussed in #114 implementing it at a low level. But maybe @bhaller is right - this isn't a common enough thing to warrant the overhead in all sims. I tend to just turn on logging in test runs, then turn it off in the big, for-reals simulation runs, for instance.

Hmm.  The modifyChild() solution you mention might be a bit sensitive to model implementation; in particular, if the model itself has modifyChild() callbacks that sometimes reject the proposed child, then your callback would have to be guaranteed to run after all of the model's own callbacks, etc.  So it gets a bit messy I think.  It would also be pretty clow, since adding a modifyChild() callback to a model involves substantial overhead.  If this is worth doing – and it probably is – then the counting of offspring should probably be built in to SLiM.  The overhead will be small-ish.

I'm more concerned with the fact that some people will want "reproductive output so far, for living individuals" and some will want "total lifetime reproductive output, for dead individuals".  Both would involve the same internal tallying code.  So perhaps both ought to be provided as possible outputs?  For the former, "reproductive output so far" could actually be a property on Individual, and then one could use addCustomColumn() or addMeanSDColumns() to add a logger that assesses all individuals, individuals in one subpop, individuals over a threshold age, etc. – having it be a property gives total flexibility, so that seems better than having a new addNumOffspringColumn() or whatever.

But that approach doesn't work for the latter, "total lifetime reproductive output", because by the time that you want to access the property on the individuals, they're dead.  So maybe in that case an addLifetimeReproductionColumns() method would be appropriate, adding mean and SD columns for that metric.  Pondering this.  Well, providing the mean lifetime reproductive output can be done through time without having to keep a vector of every data point; one can keep a running mean and update it as new data points come in, with a bit of numerical error.  But to provide the SD, we'd have to actually keep a vector with every individual data point, right?  So if a model has a pop size of 1 million, we're adding 1 million new data points to a vector with every generational turnover, just so that we can provide the SD?  That is a bit painful.  But there's no way to update a running SD, is there?

Thoughts @petrelharp ?

**Comment by petrelharp** [comment]
>  For the former, "reproductive output so far" could actually be a property on Individual,

That would be the most useful!

> But that approach doesn't work for the latter, "total lifetime reproductive output", because by the time that you want to access the property on the individuals, they're dead. 

Well, I'm not sure if anyone actually should want to compute this. It is a natural thing to look at, but I'm not sure it tells us anything qualitatively different than the mean number of offspring by age for each individual alive. Realized fitness is not just number of total offspring, it depends on how fast one has the offspring: five offspring across 5 years implies higher fitness than 5 offspring across 100 years. I don't remember what the right calculation is - number of offspring divided by age? @vsbuffalo, do you know?

And, one *could* arrive at this number by subtraction, anyhow: by logging the total number of offspring and total number of individuals just before and just after mortality, for instance. (and the total number of offspring squared would let you get the SD)

**Comment by bhaller** [comment]
`calcFST()` is now pushed to GitHub, and should be ready to use.  Here's the doc I wrote for it (start reading with the new section header, halfway down the page).  I'd appreciate if somebody (@petrelharp?) could check that it makes sense, and that the Eidos code for the function itself also makes sense.  You can now see the Eidos source code for functions that are written in Eidos using the `functionSource()` function; e.g., type `functionSource("calcFST")` in the Eidos console in SLiMgui.  But of course you'll need to be on the GitHub head to do that.  :->  
[SLiM_Manual_calcFST.pdf](https://github.com/MesserLab/SLiM/files/5556760/SLiM_Manual_calcFST.pdf)

**Comment by bhaller** [comment]
> > For the former, "reproductive output so far" could actually be a property on Individual,
> 
> That would be the most useful!

So, another thought.  If addCrossed() is called with two parents, does each get awarded 1.0 or 0.5 for its reproductive output?  Related question: if addSelfed() gets called with one parent, does that individual get awarded 1.0 or 2.0 for its reproductive output?  And likewise for addCloned()?

**Comment by bhaller** [comment]
I have just added `calcVA()` for additive genetic variance, after a bit of consultation with folks on this end.

**Comment by bhaller** [comment]
OK, I've added functions for heterozygosity, with the help of various folks.  I also put in a Watterson's theta estimator function.  @petrelharp your requested reproductiveOutput property on Individual is now implemented, plus a lifetimeReproductiveOutput property on Subpopulation; see the doc in SLiMgui in the GitHub head.  I didn't add specific generators for those to LogFile since it's trivial to use them with the custom column APIs.

There may be other metrics that would be useful to have for LogFile and other purposes; however, I don't know what they might be.  So, I'm going to close this issue, since all of the work that I'm aware of has been done.  Please open a new issue if there is a metric you want added (and provide an Eidos implementation for that metric, if possible :->).
