### ISSUE TITLE
argument hints in eidos console show instead as wierd html

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#119]
See, look at the bottom of the window:
![Screenshot from 2020-11-11 20-45-04](https://user-images.githubusercontent.com/1046249/98896929-050a8280-245f-11eb-93c3-324a09a9f37b.png)

This is with the current master from github, with Qt 5.14.2. Let me know if I can provide more info?

**Comment by bhaller** [comment]
Hrm, I thought I already committed a fix for that.  You're sure you're on the curren tGitHub head, and have rebuilt your QtSLiM?

**Comment by petrelharp** [comment]
Whoops! Yes and yes... but I apparently wasn't *running* the rebuilt one. =) Apologies!
