### ISSUE TITLE
Should give users a way to attach an arbitrary metadata string to a tree sequence

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#122]
It would be good to have a parameter to `treeSeqOutput()`, `[string$ metadata=""]`, that would let the user supply a string as metadata to be added to the top-level metadata in the saved tree sequence; then they could get that back out on the python side and use it for their own purposes.  I think this came up as an idea a while back, but an issue didn't get opened for it, so I'm just doing that now since today's tskit meeting reminded me of it.  Not sure whether this is easy or hard; certainly it's not urgent.  :->  @petrelharp

**Comment by petrelharp** [comment]
This would be useful! And, it should probably be a dictionary, since we write things out as JSON?

**Comment by bhaller** [comment]
> This would be useful! And, it should probably be a dictionary, since we write things out as JSON?

I think it would be nice to allow it to be any arbitrary string, for generality; but it would certainly be nice if it were easy to archive an Eidos `Dictionary` object (which does now have a `serialize()` method that produces a parseable string, although not a JSON string) and unarchive it back into objects on the Python side.  I can easily extend the `serialize()` method to take a `format` parameter, and add support for serializing to JSON, if that ends up being useful for this...

**Comment by petrelharp** [comment]
Ok, that makes sense - I guess it just needs one more argument, which is the name of the key it'll be stored under in the JSON.

**Comment by bhaller** [comment]
> Ok, that makes sense - I guess it just needs one more argument, which is the name of the key it'll be stored under in the JSON.

`treeSeqOutput()`, you mean?  Hmm, that's a bit messy – having to add two arguments, one for the string to write and one for the name of the key.  Can the name of the key not just be fixed/predetermined?  Or if we can, and want to, allow people to add any arbitrary key they want, then maybe `treeSeqOutput()` ought to take a dictionary, where the key names of the dictionary get used as the JSON key names, and the key values in the dictionary have to be values that can be serialized out as JSON?  Then people could add multiple keys with whatever values they want, with a single parameter...?

**Comment by petrelharp** [comment]
> Can the name of the key not just be fixed/predetermined? 

Oh, yes, that'd be fine. 

> Or if we can, and want to, allow people to add any arbitrary key they want, then maybe treeSeqOutput() ought to take a dictionary, where the key names of the dictionary get used as the JSON key names, and the key values in the dictionary have to be values that can be serialized out as JSON? 

That's more like what I was imagining. The main thing is it'd be nice to be able to, say, stick a few numerical vectors, along with their names, into the metadata, and be able to have those pulled out automatically when then metadata is parsed as JSON.  Note that if someone wants to put in a string they can just pass in, say `{"data": "here's the string I want to put in"}`.

**Comment by bhaller** [comment]
OK, that seems like a good plan.  If I add the necessary user-level API to `Dictionary` and `treeSeqOuput()`, can you connect it up to the metadata generation in SLiM (which I don't know anything about)?  (I don't anticipate working on this until after New Year's.)

**Comment by petrelharp** [comment]
Sure. [Here's the metadata-generating code](https://github.com/MesserLab/SLiM/blob/e325decdbeb5f3c16c300ce5d5feeda5b78f90de/core/slim_sim.cpp#L6380), btw - it's pretty straightforward, although to use it we'll have to figure out how to get an Eidos dictionary into a `nlohmann::json` dictionary. (hm.)

**Comment by bhaller** [comment]
> Sure. [Here's the metadata-generating code](https://github.com/MesserLab/SLiM/blob/e325decdbeb5f3c16c300ce5d5feeda5b78f90de/core/slim_sim.cpp#L6380), btw - it's pretty straightforward, although to use it we'll have to figure out how to get an Eidos dictionary into a `nlohmann::json` dictionary. (hm.)

I can do that part no problem.  I just don't understand the different levels of metadata, the schemas, the JSON versus struct thing, what's allowed where, etc.  :->

**Comment by bhaller** [comment]
Hi @petrelharp.  Thinking of putting in the necessary support for this now.  Should the additional parameter to `treeSeqOuput()` be named `metadata=`?  `usermetadata=`?  `userdata=`?  Something else?

**Comment by petrelharp** [comment]
I think just `metadata` is OK - the docs will explain where it goes (and hence, how to get it back out again).

**Comment by bhaller** [comment]
> I think just `metadata` is OK - the docs will explain where it goes (and hence, how to get it back out again).

OK, here's the doc for the parameter so far:

A Dictionary object containing user-generated metadata may be supplied with the metadata parameter.  If present, this dictionary will be serialized as JSON and attached to the saved tree sequence.  If pyslim is used to read the tree sequence in Python, this metadata will automatically be deserialized and made available.

So.  What should it say about where it goes, and how to get it back out again?

**Comment by bhaller** [comment]
WTF, GitHub deleted my comment when I tried to update it!

@petrelharp I was asking about this new doc:

A Dictionary object containing user-generated metadata may be supplied with the metadata parameter.  If present, this dictionary will be serialized as JSON and attached to the saved tree sequence.  If pyslim is used to read the tree sequence in Python, this metadata will automatically be deserialized and made available.

What additional detail should I give after "attached to the saved tree sequence" and after "made available"?  I'm not sure what your plans are exactly.

**Comment by bhaller** [comment]
OK, @petrelharp, I have committed step one of this.  The doc needs to be improved (see previous), but I think it's working.  Here's a test model:

```
initialize() {
	initializeTreeSeq();
	initializeMutationRate(0);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 1e8-1);
	initializeRecombinationRate(1e-8);
}
1 {
	sim.addSubpop("p1", 500);
}
500 late() {
	foobar = Dictionary();
	foobar.setValue("foo", "bar");
	foobar.setValue("bar", c("baz", "xyzzy"));

	d = Dictionary();
	d.setValue("NULL", NULL);
	d.setValue("logical", T);
	d.setValue("logicals", c(T, F, F, T));
	d.setValue("string", "foo");
	d.setValue("strings", c("foo", "bar"));
	d.setValue("integer", 5);
	d.setValue("integers", 5:10);
	d.setValue("float", 5.5);
	d.setValue("floats", 5.5:10);
	d.setValue("dictionary", foobar);
	d.setValue("dictionaries", c(foobar, foobar));
	
	sim.treeSeqOutput("~/Desktop/test.trees", metadata=d);
}
```

It constructs a complicated dictionary and passes it to the new `metadata=` parameter of `treeSeqOutput()`.  And here's the console output you get if you uncomment the line after `// for debugging`, at slim_sim.cpp:6394:

```
JSON metadata: 
{
    "dictionaries": [
        {
            "bar": [
                "baz",
                "xyzzy"
            ],
            "foo": [
                "bar"
            ]
        },
        {
            "bar": [
                "baz",
                "xyzzy"
            ],
            "foo": [
                "bar"
            ]
        }
    ],
    "dictionary": [
        {
            "bar": [
                "baz",
                "xyzzy"
            ],
            "foo": [
                "bar"
            ]
        }
    ],
    "float": [
        5.5
    ],
    "floats": [
        5.5,
        6.5,
        7.5,
        8.5,
        9.5
    ],
    "integer": [
        5
    ],
    "integers": [
        5,
        6,
        7,
        8,
        9,
        10
    ],
    "logical": [
        1
    ],
    "logicals": [
        1,
        0,
        0,
        1
    ],
    "string": [
        "foo"
    ],
    "strings": [
        "foo",
        "bar"
    ]
}
```

So everything seems to be converting to JSON fine.  The one oddity, I guess, is that singleton values get converted to JSON as arrays containing one value, rather than simple values.  This is a side effect of Eidos's "everything is a vector" approach; it was the natural way for the code to work.  It seems fine to me, but if you think people will find it objectionable, I'm sure I can figure out a way to fix it (but it won't be as elegant).

At present I think (but haven't verified) that this stuff is getting added under a key named "metadata" that is underneath the "SLiM" key.  I'm not sure whether that's where you planned for it to go or not.  See comments starting at slim_sim.cpp:6383 with questions for you.

I suppose it would be nice if SLiM read this key back in, too, and converted the JSON metadata back into a `Dictionary` object, and made that available.  It's not immediately obvious where that metadata would be made available, though.  The `readFromPopulationFile()` method already has a return value, unfortunately, otherwise that would be the obvious/elegant place to return it.  I suppose I could add a read-only "metadata" property to SLiMSim, or it could get assigned to SLiMSim as a Dictionary value for a key named "metadata", or some such, but that feels kinda hack-y.  Or we could change the return value of `readFromPopulationFile()` to return the metadata dictionary instead, and the current return value (the generation counter read in as the current generation) could be turned into a key-value pair in the returned metadata dict; but that would break backward compatibility, and is also a little hack-y.  Any better ideas?

Anyway, unless I've forgotten something I believe the ball is now in your court.  :->

**Comment by petrelharp** [comment]
Sorry for the delay... Some answers [here](https://github.com/MesserLab/SLiM/commit/598b1a4f7e6166ef1c7895908baae03234926dfd#r45721299).

>  The one oddity, I guess, is that singleton values get converted to JSON as arrays containing one value, rather than simple values. 

No big deal.

> I suppose it would be nice if SLiM read this key back in, too, and converted the JSON metadata back into a Dictionary object, 

Probably? But I don't know of any use cases of this (yet), so no need to do it? I'm not thinking of a great way to return it...

> What additional detail should I give after "attached to the saved tree sequence" and after "made available"? 

I don't have to do anything! The magic of metadata in tskit means that `ts.metadata` is a python dictionary, and that the stuff you put in there will be in it, just like you put it in!

**Comment by bhaller** [comment]
OK, groovy.

**Comment by petrelharp** [comment]
For future reference, pyslim test at https://github.com/tskit-dev/pyslim/pull/120 .

The docs make sense!  :tada:
