### ISSUE TITLE
QMenus detached from QMenuBar on Fedora 32+, vertical offset increasing with each use

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#126]
### My System
Fedora 33 Workstation, Gnome Desktop Environment with no shell extensions or themes.
QtSLiM built from v3.4 sources.

### Situation and Issue
After using a QMenu and relaunching QtSLiM, QMenus are detached from the menu bar as depicted in the first attached screenshot. Each interaction and subsequent relaunch of QtSLiM increases the detached offset of the QMenu.

The situation can continue until the QMenu is outside the window of QtSLiM, and continue further until the QMenu is no longer visible on screen.

### Screenshots, in sequential order
![Screenshot from 2020-11-29 03-03-01](https://user-images.githubusercontent.com/51974245/100560392-d9ff9b80-3272-11eb-92e0-def2445a6036.png)
![Screenshot from 2020-11-29 03-03-50](https://user-images.githubusercontent.com/51974245/100560391-d9670500-3272-11eb-9ec1-743d6c8e53ea.png)
![Screenshot from 2020-11-29 03-04-30](https://user-images.githubusercontent.com/51974245/100560390-d9670500-3272-11eb-8a79-88c51a2c95ad.png)
![Screenshot from 2020-11-29 03-05-08](https://user-images.githubusercontent.com/51974245/100560389-d835d800-3272-11eb-90c1-48fc93faa989.png)

Occurs indeterminately when using Wayland compositing (what triggers the issue is unknown).

- Changing the compositor to X11 resets the vertical offset of QMenus.
- The issue is gone after changing back to Wayland compositing after using the X11 compositor to 'reset' the position/offset of QMenus.
- Persists across hard system reboots.

A similar issue was noticed on Fedora 32, but no information about that can be provided as I am no longer running that version of Fedora.

**Comment by bryce-carson** [comment]
When using multiple monitors with different heights with Qt5 apps, a similar issue, but with horizontal misplacement as well, occurs on Wayland composited desktop environments: https://bugreports.qt.io/browse/QTBUG-88561.

**Comment by bhaller** [comment]
Well, it's an interesting bug, but it's a Qt bug, and completely out of my control.  I would recommend running the most recent (5.x) version of Qt, if you aren't already; it might have a fix.  Beyond that, there's really nothing I can do about such problems, so I'm going to close this.  You can report it to Qt at https://bugreports.qt.io if you want to; or search for an open bug on the issue, since it has probably already been reported.

**Comment by bhaller** [comment]
> When using multiple monitors with different heights with Qt5 apps, a similar issue, but with horizontal misplacement as well, occurs on Wayland composited desktop environments: https://bugreports.qt.io/browse/QTBUG-88561.

Ah, I see you found qtbug.  :->

**Comment by bryce-carson** [comment]
> Well, it's an interesting bug, but it's a Qt bug, and completely out of my control. I would recommend running the most recent (5.x) version of Qt, if you aren't already; it might have a fix. Beyond that, there's really nothing I can do about such problems, so I'm going to close this. You can report it to Qt at https://bugreports.qt.io if you want to; or search for an open bug on the issue, since it has probably already been reported.

Ah, I see. Yes, I had taken a look a few weeks ago, the last time this happened, at the main window UI code, and the Qt5 documentation and I couldn't see anything that might cause this. Thanks for the reply.
