### ISSUE TITLE
QtSLiM Wayland Issues

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#127]
If QtSLiM is launched from the terminal we get some output warnings when using Fedora 33 Workstation (with the Gnome desktop environment) and Wayland compositing (the new default, rather than X11):

[brycecarson@localhost ~]$ SLiMgui 
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
[brycecarson@localhost ~]$ SLiMgui 
QSocketNotifier: Can only be used with threads started with QThread
[brycecarson@localhost ~]$ 

These warnings are not apparent or present when using X11 compositing. It may be related to #126.

**Comment by bryce-carson** [comment]
When using multiple monitors with different heights with Qt5 apps, a similar issue, but with horizontal misplacement as well, occurs on Wayland composited desktop environments: https://bugreports.qt.io/browse/QTBUG-88561.

**Comment by bhaller** [comment]
As with the previous bug – nothing I can do about this sort of thing.  It's like reporting macOS bugs to me; just nothing to do with my code.  So I'm going to close this; sorry!
