### ISSUE TITLE
Modeling Genealogical Ancestry?

### ISSUE THREAD

**Issue by swamidass** [MesserLab/SLiM#128]
How can we track of genealogical ancestry in biparental simulations? For example, 

1. If we mark a specific individuals, I'd like to know who are their genealogical (not necessarily genetic) descendents.

2. If we mark a group of individuals, I'd like to know who are are genealogical descendents of all (or any) of them.

3. If we mark a group of individuals, I'd like to know who are ancestors of all of them.

I understand it might not be feasible to do all these computations in an efficient manner, so only some of this may be feasible.

**Comment by bhaller** [comment]
Hi!  Please ask questions on the slim-discuss mailing list, not on GitHub.  https://groups.google.com/g/slim-discuss
