### ISSUE TITLE
Update description of treerec implementation

### ISSUE THREAD

**Issue by hyanwong** [MesserLab/SLiM#130]
The [implementation.md](https://github.com/MesserLab/SLiM/blob/master/treerec/implementation.md) file describes saving the first generation individuals for recapitation, but as of SLiM 3.5 I think this doesn't apply, so I guess this file needs updating? I'm updating it as part of https://github.com/MesserLab/SLiM/pull/40#issuecomment-755222254 but I thought I should check here that this is correct, and whether we want to keep the `implementation.md` file anyway.

**Comment by bhaller** [comment]
This is @petrelharp's department.  I thought he did update the file as part of SLiM 3.5, though; but perhaps a detail was missed?

**Comment by bhaller** [comment]
If there is a change to be made to it for 3.5, that should be done now, not in #40, just to keep things properly compartmentalized.  Who knows whether/when #40 will be finished.

**Comment by hyanwong** [comment]
Good point. I'll leave it to @petrelharp to say if I've misunderstood here.

**Comment by petrelharp** [comment]
Oh damn, good point, @hyanwong - I failed to update that in #106.

**Comment by hyanwong** [comment]
Do you want me to put in a PR which (essentially) just removes those lines, @petrelharp ?

**Comment by petrelharp** [comment]
Well, whoever does it needs to carefully read the changes to the code to make sure that the updates to the description are correct. I'll do it soon.
