### ISSUE TITLE
SLiMgui should do a better job with Python scripts

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#137]
Some of the "recipes" in the manual involve python scrips, to do tree sequence stuff with pyslim.  All of the manual recipes are available in SLiMgui under the File > Open Recipe menu, including these python recipes.  SLiMgui doesn't handle them very well, though.  They open in a SLiM model window just like a .slim file would, but since they're in python, SLiM immediately shows an error message because the script isn't Eidos.  It would be nice if this were handled better.

I'm thinking that SLiM could actually allow the user to run these python scripts.  It could, when the Play button is clicked, just call out to Bash and ask it to run a command line like "python3 <path>" in the current working directory (which would be settable with the folder button, as usual).  It could show the output from the execution of that command in the output pane on the right.  I don't think I'll try to get into doing anything fancy, like syntax coloring for python code, or anything like that.  But I could show the python code, allow it to be run, and show the output, all inside SLiMgui.  This would make following the tree-seq worksheets in the SLiM workshop much simpler, too; no hassles with external text editors, Terminal, etc.

I suppose the window I'd show the code in would be like the SLiM model window, but without the population table, chromosome view, individuals view, etc.; just the editor pane, the output pane, and the play button, I guess.  Something like that.

So.  Any comments from the pythonic folks, like @petrelharp, @grahamgower, @vsbuffalo, @ianvcaldas, @samchamper?  Would you use this feature at all?  Would a hard-coded command line of "python3 <path>" suffice, or should I put in a pref to let the user choose the python executable they want to use or something?  Are there things I'm missing here?  Would I need to pipe keyboard input to the python process, do you think?  I guess I'd want to have a "stop" button that would kill the python process, in case it hung or something...?

**Comment by bhaller** [comment]
I suppose the File menu could then have New Python Script type menu items; it could let you make a new empty python script, or a new boilerplate script for doing mutation overlay or recapitation.  Very much like how you can make a new WF or nonWF boilerplate script now, with New X commands.  @petrelharp does this seem like a good idea?

**Comment by samchamper** [comment]
This sounds handy in theory, but I'll admit that I'm one of those people who has lots of windows open anyway on multiple monitors, so I think I'd still default to having python scripts open in a separate text editor.

If you were to implement this, I agree that you'd want a "stop" button, and also that you probably wouldn't need to worry about input (I can't remember the last time I used input()). Also, "python3" would generally work, but it might be best if you allow some flexibility in setting what command line string is actually being run, as I expect that many folks use argparse and would want to be able to specify args.

**Comment by bhaller** [comment]
> If you were to implement this, I agree that you'd want a "stop" button, and also that you probably wouldn't need to worry about input (I can't remember the last time I used input()). Also, "python3" would generally work, but it might be best if you allow some flexibility in setting what command line string is actually being run, as I expect that many folks use argparse and would want to be able to specify args.

OK.  What's argparse?  What sort of flexibility are you thinking of here?  Just a way to replace "python3" with an arbitrary string?  Or is more needed than that?

**Comment by grahamgower** [comment]
I wonder if its better to just not open the python scripts in SLiMgui at all? Probably it's better for users to open the python script in their chosen IDE or text editor, and run the script from there. Or run the script manually from the terminal.

**Comment by petrelharp** [comment]
I think I'm with @grahamgower here - if the use case is for students, I generally think that newbies should always be looking at code syntax-highlighted, since it makes it less daunting and less frustrating to find the syntax mistakes. I wouldn't use it either, for the same reason. Maybe I'm missing something about the use case, though?

If the goal is to make workshops more seamless, you could have something to pop open a terminal, so that oen could then run `python3 myscript.py` in it and see the output... but then, it's just as easy to open an *actual* terminal, so I don't see the upside there either.

**Comment by bhaller** [comment]
Yes, I'd much rather fob this off on the user's existing Python IDE/editor.  Unfortunately, I haven't been able to find a portable way, across Linux variants, to ask the system "open the document at <path> in whatever the user's default app for files of this type/extension happens to be".  When the user selects a .py recipe file from SLiMgui's Open Recipe menu, something needs to happen – that .py file should open, either in SLiMgui or in an external app, and I can't figure out how to make it happen in an external app.  Is there a Bash command to do this that is portable across Linux variants?  Qt does not seem to provide this functionality, unfortunately.  This is why I've been thinking about opening the document inside SLiMgui instead.

Another complication is that the .py file in question doesn't really exist in the filesystem; it's inside the SLiMgui executable, as a Qt resource, however that works internally.  So there isn't really a real document to open/execute in the first place, as far as Unix is concerned.  However, I can get around that by creating a temporary .py file inside /tmp, I imagine.

**Comment by petrelharp** [comment]
Oh, I see. This is tricky.  I guess you could open up the files in an editor, and give people the option to save them where they want, but put a comment up top saying "you gotta run this on your own".

>  Is there a Bash command to do this that is portable across Linux variants? 

Well, `xdg-open filename.py` does something not unreasonable.

An alternative would be to add all such recipes to the pyslim docs? So this could just open up the URL for the relevant page?

**Comment by bhaller** [comment]
> Oh, I see. This is tricky. I guess you could open up the files in an editor, and give people the option to save them where they want, but put a comment up top saying "you gotta run this on your own".
> 
> > Is there a Bash command to do this that is portable across Linux variants?
> 
> Well, `xdg-open filename.py` does something not unreasonable.

And that works across Linux variants?  OK, that sounds like a workable solution, then.  I can make a .py file for the recipe in /tmp, and tell Bash to execute `xdg-open /tmp/filename.py`, and it's up to the user after that; they will need to ensure that .py files open in the app they want on their system.  I'll try this out and see if I can get it to work.  :->

> An alternative would be to add all such recipes to the pyslim docs? So this could just open up the URL for the relevant page?

Well, that would be a pretty big doc migration.  I mean, just about every recipe in the tree-seq chapter uses pyslim.  I don't think we want all of that to become pyslim doc.  As we recently discussed, it makes sense to put all of the more advanced pyslim stuff into the pyslim docs, but the SLiM docs do need to provide a basic introduction to how to do basic things.

**Comment by grahamgower** [comment]
> > Is there a Bash command to do this that is portable across Linux variants?
> 
> Well, `xdg-open filename.py` does something not unreasonable.

This might be the least-worst option.

> And that works across Linux variants?

Well, maybe. But if it does the wrong thing, then it's on the user to fix their setup. For example, on my system, python scripts are unassociated MIME types, and it seems that files with an unassocaited MIME are xdg-open'd with Firefox by default. I've no idea who thought this to be a sensible default, or if I inadvertantly did (or didn't) set something up. But the fix is to associate python scripts with a specific app. (I added `text/x-script.python=gvim.desktop` under the `[Default Applications]` block in `~/.config/mimeapps.list` --- perfectly obvious, right?)

**Comment by petrelharp** [comment]
> Well, that would be a pretty big doc migration. I mean, just about every recipe in the tree-seq chapter uses pyslim. I don't think we want all of that to become pyslim doc.

Or, we could just make a directory with the script files in it, rather than moving the actual docs over? And, these could then be linked to? This could be nice because then we could use them for automatic pyslim testing as well, to make sure they haven't broken.

**Comment by bhaller** [comment]
> > Well, that would be a pretty big doc migration. I mean, just about every recipe in the tree-seq chapter uses pyslim. I don't think we want all of that to become pyslim doc.
> 
> Or, we could just make a directory with the script files in it, rather than moving the actual docs over? And, these could then be linked to? This could be nice because then we could use them for automatic pyslim testing as well, to make sure they haven't broken.

Ah, I see.  Hmm.  If we did that, then choosing a .py recipe from SLiM's Open Recipe menu would open a web page in the user's browser, I guess?  That seems non-optimal.  Or are you thinking that SLiM would download the file from the web, save it to /tmp, and then open it for the user with `xdg-open`?  In that case, the advantage over having the recipes reside inside SLiMgui is not clear.  (Apart from the pyslim testing issue you mention; but really that's a bigger issue, that it would be great to automate testing of *all* of the recipes that are in the SLiM manual.)

**Comment by petrelharp** [comment]
> Hmm. If we did that, then choosing a .py recipe from SLiM's Open Recipe menu would open a web page in the user's browser, I guess? 

Yeah, that's my suggestion. The point is, I think, to make it easy for users of the GUI to get the code that corresponds to particular examples?

**Comment by bhaller** [comment]
> > Hmm. If we did that, then choosing a .py recipe from SLiM's Open Recipe menu would open a web page in the user's browser, I guess?
> 
> Yeah, that's my suggestion. The point is, I think, to make it easy for users of the GUI to get the code that corresponds to particular examples?

Well, that's part of the point.  Making it easy for them to *run* the code is also part of the point, though.  They could copy-paste the code from their web browser into their Python environment of choice, or into a plain-text window to save and run in their terminal; but that's not terribly smooth.  Still, it's better than the current user experience.  Hmm.

**Comment by bhaller** [comment]
In particular, what is driving this for me is that the instructions in the SLiM workshop, for how to run the python code chunks, is really gross.  I have to tell people that on macOS they should copy/paste the code into TextEdit, but that they need to turn off smart quotes, etc., in TextEdit first so that it won't corrupt their code, and then they have to save the file, and then they have to go to Terminal and run the file they saved, etc.  For users who aren't used to working in Terminal, this is pretty clunky.  I can't assume that they will have any Python IDE installed, though.  And for Linux users I can't even give them instructions that good; they're pretty much on their own in figuring out what text editor to paste into, how to ensure that that editor doesn't apply "smart quotes", saves as plain text rather than rich text, etc.  All of this is just really hard to walk new users through, step by step.  This is why having a solution that is self-contained inside SLiMgui itself has so much appeal, even if power users would rarely/never use it.

**Comment by petrelharp** [comment]
Well, you could have a link to the "raw" file, like this:
  https://raw.githubusercontent.com/tskit-dev/pyslim/main/docs/selection.slim
(that's what I got by clicking on the "raw" link of this page: https://github.com/tskit-dev/pyslim/blob/main/docs/selection.slim - they could also right-click on "raw" and do "save link as" ) Then, they could save the file wherever they want, and run python on it? They shouldn't be copy-pasting, I agree.

I don't think the python examples are going to be useful for people who don't know how to save a python script and then run it using python.  So, with the TextEdit bit removed, do you think "save to a file; open terminal, navigate to the directory the file is in, and run `python3 filename.py`" would be good for the target audience?

**Comment by bhaller** [comment]
> Well, you could have a link to the "raw" file, like this:
> https://raw.githubusercontent.com/tskit-dev/pyslim/main/docs/selection.slim
> (that's what I got by clicking on the "raw" link of this page: https://github.com/tskit-dev/pyslim/blob/main/docs/selection.slim - they could also right-click on "raw" and do "save link as" ) Then, they could save the file wherever they want, and run python on it? They shouldn't be copy-pasting, I agree.
> 
> I don't think the python examples are going to be useful for people who don't know how to save a python script and then run it using python. So, with the TextEdit bit removed, do you think "save to a file; open terminal, navigate to the directory the file is in, and run `python3 filename.py`" would be good for the target audience?

It would be an improvement, for sure.  Still a lot less smooth than "choose the .py recipe from the Open Recipe menu in SLiMgui, and then click the big green "play" button to execute it", though.  :->  Using pyslim may be many people's first experience with python (it's *my* first experience with python, in fact!), so I want it to be as gentle as possible.  :->

Yes, this may be sufficiently simple, even if less than ideal.  I'll ponder this for a little while, and then probably connect with you about whether putting the python recipes into pyslim or something makes sense.  (I could also just throw them onto benhaller.com, of course, if the goal is just to have them available by URL so that they can be opened by a browser; and then I'm not relying on GitHub not to change its URLs to those resources!)

**Comment by ianvcaldas** [comment]
The thing that makes the most sense to me, if it can be done, would be for SLiM to automatically "download" the .py file into the current directory when they click the recipe and everything from then is on the user. It's easy to navigate to the directory and run the script in a terminal or to open it with whatever app the user prefers using the standard methods of the system.

The problem with a big green Play button is that I think most Python users have multiple versions of Python in their system, and it's hard to tell what will come up with default bash `python3` invocation. (For instance, in my computer it brings up the Python autoinstalled by Homebrew as a dependency, which I don't use and where pyslim isn't installed...)

**Comment by bryce-carson** [comment]
An implementation might be "Show in Finder" or "Open in Explorer". Qt has stuff for this, according to this Stack Exchange thread: https://stackoverflow.com/questions/3490336/how-to-reveal-in-finder-or-show-in-explorer-with-qt/37775479.

This would allow the .py files to remain in the SLiM sources, and then the user can use the Open Recipe dialogue, and it will "reveal" the file in the default graphical file manager. I don't know if this would be possible in Linux, because of the range of graphical file managers, but assuming Qt handles portability well enough for SLiMgui to be where it is now, it could work.

**Comment by bhaller** [comment]
> An implementation might be "Show in Finder" or "Open in Explorer". Qt has stuff for this, according to this Stack Exchange thread: https://stackoverflow.com/questions/3490336/how-to-reveal-in-finder-or-show-in-explorer-with-qt/37775479.

Unfortunately, the solutions on that thread only work on macOS and Windows, not Linux.  I'm already intimately familiar with that particular SO thread.  :->  Note that the Linux branch of the code in the top reply has the comment "// we cannot select a file here, because no file browser really supports it...".  None of the other replies has a good solution for Linux either.  It seems that there is just not a strategy that works well on Linux.

**Comment by bryce-carson** [comment]
> > An implementation might be "Show in Finder" or "Open in Explorer". Qt has stuff for this, according to this Stack Exchange thread: https://stackoverflow.com/questions/3490336/how-to-reveal-in-finder-or-show-in-explorer-with-qt/37775479.
> 
> Unfortunately, the solutions on that thread only work on macOS and Windows, not Linux. I'm already intimately familiar with that particular SO thread. :-> Note that the Linux branch of the code in the top reply has the comment "// we cannot select a file here, because no file browser really supports it...". None of the other replies has a good solution for Linux either. It seems that there is just not a strategy that works well on Linux.

The command `xdg-open [directory]` can open a file manager. It should be desktop agnostic, and because all of the files are appropriately named it shouldn't be difficult for a SLiM user to find the correct .py file on Linux. Pre-selecting a file is... more of a convenience than is necessary, I think.

**Comment by bhaller** [comment]
> The command `xdg-open [directory]` can open a file manager. It should be desktop agnostic, and because all of the files are appropriately named it shouldn't be difficult for a SLiM user to find the correct .py file on Linux. Pre-selecting a file is... more of a convenience than is necessary, I think.

I dunno.  I think if the user selects a .py recipe in SLiMgui, and in response a folder pops open on their desktop containing all of the recipes (of which there are more than a hundred), that's pretty sub-optimal.  I'm leaning toward the suggestion of opening the relevant file in the user's browser; then they see the specific file they requested, and they can then do whatever they want to do with it – just look at it right there (which is probably all that many users want to do anyway), or save it to whatever location they want and open it in whatever app they want.  Also, it's not clear that xdg-open is available across all Linux platforms, from the chat above; so that's a pretty fundamental problem.  If this were an easy problem to solve cross-platform, Qt would already provide a wrapped solution; the fact that they don't means they don't have a good solution, and they know what they're doing.

**Comment by bhaller** [comment]
> > The command `xdg-open [directory]` can open a file manager. It should be desktop agnostic, and because all of the files are appropriately named it shouldn't be difficult for a SLiM user to find the correct .py file on Linux. Pre-selecting a file is... more of a convenience than is necessary, I think.
> 
> I dunno. I think if the user selects a .py recipe in SLiMgui, and in response a folder pops open on their desktop containing all of the recipes (of which there are more than a hundred), that's pretty sub-optimal. I'm leaning toward the suggestion of opening the relevant file in the user's browser; then they see the specific file they requested, and they can then do whatever they want to do with it – just look at it right there (which is probably all that many users want to do anyway), or save it to whatever location they want and open it in whatever app they want. Also, it's not clear that xdg-open is available across all Linux platforms, from the chat above; so that's a pretty fundamental problem. If this were an easy problem to solve cross-platform, Qt would already provide a wrapped solution; the fact that they don't means they don't have a good solution, and they know what they're doing.

Oh, and also: note that there isn't a directory to open in the first place; all the recipes are compiled into the SLiMgui binary on Linux.  So to do this at all, SLiMgui would have to create a new directory under /tmp, and create the recipe files inside it, and then open that directory in the desktop environment.  That just seems pretty weird.  You're not really supposed to expose /tmp to the user – to encourage them to browse/open files that are inside /tmp, for example.

**Comment by bryce-carson** [comment]
> > The command `xdg-open [directory]` can open a file manager. It should be desktop agnostic, and because all of the files are appropriately named it shouldn't be difficult for a SLiM user to find the correct .py file on Linux. Pre-selecting a file is... more of a convenience than is necessary, I think.
> 
> I dunno. I think if the user selects a .py recipe in SLiMgui, and in response a folder pops open on their desktop containing all of the recipes (of which there are more than a hundred), that's pretty sub-optimal. I'm leaning toward the suggestion of opening the relevant file in the user's browser; then they see the specific file they requested, and they can then do whatever they want to do with it – just look at it right there (which is probably all that many users want to do anyway), or save it to whatever location they want and open it in whatever app they want. Also, it's not clear that xdg-open is available across all Linux platforms, from the chat above; so that's a pretty fundamental problem. If this were an easy problem to solve cross-platform, Qt would already provide a wrapped solution; the fact that they don't means they don't have a good solution, and they know what they're doing.

Ah, yes I hadn't seen that `xdg-open` was already mentioned. That's unfortunate, but those Qt people do know what they're doing, for sure. Darn!

**Comment by bhaller** [comment]
> Ah, yes I hadn't seen that `xdg-open` was already mentioned. That's unfortunate, but those Qt people do know what they're doing, for sure. Darn!

Thanks for the brainstorming.  If you see a path to a better solution, please continue to debate; I don't mean to shoot you down, I just don't see it yet.

**Comment by bryce-carson** [comment]
I'm looking at the sources and documentation, and while I don't write C++ or Qt apps, at all, ever, it looks like we could open the Qresource after writing out a temporary copy. If an appropriate application doesn't exist, it should open in the browser anyways.
Is there a reason why QDesktopServices::openURL wouldn't work with the qrcs?

**Comment by bhaller** [comment]
> I'm looking at the sources and documentation, and while I don't write C++ or Qt apps, at all, ever, it looks like we could open the Qresource after writing out a temporary copy. If an appropriate application doesn't exist, it should open in the browser anyways.
> Is there a reason why QDesktopServices::openURL wouldn't work with the qrcs?

Well, we could certainly write the .py file to /tmp and then ask Qt to open it.  I see two problems with that, though.  One is that opening files that are inside /tmp is kind of a no-no; that's not supposed to be a place where the user has open files.  I'm not sure what would go *wrong*, but it feels very wrong to me, at a gut level.  Two, I don't think there's any particular guarantee for where the file will open if the user doesn't have a Python IDE; I'm not aware of a guarantee that it will fall back on the browser.  Could end up anywhere, or maybe just failing in some way.  This stuff just doesn't seem to be well-defined on Linux.  It could work out better for some users – specifically those who have a binding set up for .py files.  But for other users – in particular, novice users who are less likely to have a .py binding set up – it might do some unpredictable thing.  Opening the content in the browser, reliably, seems preferable.

**Comment by bryce-carson** [comment]
What about using the Eidos Console as a portable text editor? When a Python recipe is selected we could "open" it in the Eidos Console like below. Saving the file is easy, just specify a path.

We could pass the qrc within the here document string below, and with the delimiter being arbitrary we might do something like `<<python`, and could, if really desired, include a python syntax highlighting module to color here document strings with that delimiter.

1. Portable
2. Makes use of existing qrc
3. Surrounding Eidos code may confuse the user, however if they are learning the Python *extension?* to SLiM they shouldn't be confused for long.
4. Enables a path for Python highlighting within lambdas, functions, system commands, etc.
5. Doesn't rely on external applications; openURL can fail.

It should also be more responsive than spawning a browser window; there may also be the issue that an existing browser window is not brought to the foreground on some systems, causing the user to think "nothing happened."

What do you think, Ben?
```
DIR = NULL;
NAME = "recipeName.py";

writeFile(filePath = paste(c(DIR, NAME)), contents = <<python
# Keywords: Python, tree-sequence recording, tree sequence recording

# This is a Python recipe, to be run after the section 17.1 recipe

import msprime, pyslim

ts = pyslim.load("./recipe_17.1.trees").simplify()
mutated = msprime.mutate(ts, rate=1e-7, random_seed=1, keep=True)
mutated.dump("./recipe_17.1_overlaid.trees")
>>python);
```

**Comment by bhaller** [comment]
> What about using the Eidos Console as a portable text editor? When a Python recipe is selected we could "open" it in the Eidos Console like below....

Hmm.  I recognize that the openURL solution is imperfect (can fail, can produce a window that is hidden behind other windows).  The solution you propose just seems very strange to me, though.  I think it would be confusing to beginning users, who are the main target audience for this feature in the first place.  If we really wanted to avoid the openURL route, the more straightforward thing, to me, would seem to be to just run a Save panel immediately – ask the user for a path to which the .py recipe file should be saved on their system (since we can't open it from inside the application bundle where it has been compiled, and since we don't want to save it to /tmp, and since we can't tell the Linux system to reveal it at any particular chosen path automatically, and since we have no reliable way to tell Linux to open a given .py file in a good application – the user may not even _have_ a good application to open it in).  If we ran a Save panel, and the user chose to save the file to, say, ~/Desktop/foo.py, then the user would understand that the file now exists at ~/Desktop/foo.py – since they themselves just chose that path and clicked "Save" – so they could then go looking for it if they wanted to.  (We could even run an alert panel, after the Save panel, the first time that the user does this, telling the user "The file has been saved to <path>.  You can now locate it and open it in the Python editor of your choice.")  That seems much more straightforward than putting a Python-file-generating script into their Eidos console and expecting them to understand that they need to modify that script to provide a path, and then execute that script to generate the Python script they've requested.  At present I would say that opening a new browser window is a solution I can live with, although it's imperfect; but if you (@bryce-carson) or someone else reading this feels strongly that running a Save panel would be better, I'm open to that.  Not sure why that solution didn't occur to me earlier.
