### ISSUE TITLE
Improvements to treerec unit testing framework

### ISSUE THREAD

**Issue by hyanwong** [MesserLab/SLiM#140]
Following on from [various](https://github.com/MesserLab/SLiM/pull/40#issuecomment-758132212) [comments](https://github.com/MesserLab/SLiM/pull/136#issuecomment-757533537) in other PRs, I though it worth collecting some notes on how to parallelise the python tests in `treerec/tests`, after chatting to @benjeffrey.

At the moment, for each SLiM script in `testRecipes`, a bash script runs `slim` (which outputs some files, including tree sequences) and then a set of different pytest runs are executed which read and compare these files.

Some things I think we should do:

1. The slim scripts should each be run within a different unique dir (probably named by the script name), so that generated files are all output there.
2. In fact, each time a set of files is output from SLiM (e.g. via the bespoke `outputMutationTypes()` function), we should probably save to a subdirectory within that directory, perhaps named by the generation time? The directory would be created within the SLiM recipe by the Eidos `createDirectory()` function. That would allow us to do `outputMutationTypes()` multiple times within the same simulation.
3. Each slim script should be a parameter that is passed to a pytest fixture. The fixture should be session-scoped, and for each parameter (i.e. script), if the output files are not present, the SLiM simulation is run and a lock file created so that other tests that are trying to get the output files will wait until a joint file is created. (Untested) code is possibly something like this (modified from [here](https://github.com/pytest-dev/pytest-xdist#making-session-scoped-fixtures-execute-only-once) )
    ``` python
    from filelock import FileLock
    slim_recipes = ["test_010_recipe1", "test_011_recipe2"] # replace with code to get all recipes


    def subdirs(run_dir):
        """
        SLiM recipes are expected to output their results into a set of directories
        within the run_dir: return a list of them
        """
        return [f.name for f in os.scandir(run_dir) if f.is_dir()]

    def run_slim(recipe, run_dir, recipe_dir="testRecipes"):
        """
        Run the script specified by recipe, producing files in the run_dir directory
        Return a list of directories containing the files on which tests should be run
        """
        full_recipe = os.path.abspath(os.path.join(recipe_dir, recipe + ".slim"))
        if not os.path.isdir(run_dir):
            raise RuntimeError(f"The directory {run_dir} need to be created")
        subprocess.call(["slim", "-s", "22", full_recipe], cwd=run_dir)
        return subdirs(run_dir)

    @pytest.fixture(scope="session", params=slim_recipes)
    def session_data(request, tmp_path_factory, worker_id):
        """
        Most logic in this fixture is to check whether we are running as a single proc, or as a worker.
        If a worker, and this is the first run, we need to lock the process until the simulations have finished.
        """
        if worker_id == "master":
            # not executing in with multiple workers, just produce the data and let
            # pytest's fixture caching do its job
            run_dir = os.path.join(tmp_path_factory.getbasetemp(), request.param)
            return run_slim(recipe=request.param, run_dir=run_dir)
    
        run_dir = os.path.join(tmp_path_factory.getbasetemp().parent, request.param)
        with FileLock(os.path.join(run_dir, "simulation.lock")):
            # get the temp directory shared by all workers, so that simulation files
            # are shared between workers
            run_dir = os.path.join(tmp_path_factory.getbasetemp().parent, request.param)
            if fn.is_file():
                data_dirs = subdirs(run_dir)
            else:
                data_dirs = run_slim(recipe=request.param, run_dir=run_dir)
        return data_dirs

    class TestWhatever:
        def test_whatever(self, session_data):
            for d in session_data:
                compare(os.path.join(d, "out.trees"), os.path.join(d, "out.txt"))
   ```

I'll add to this as I think of stuff. The idea is to template this approach for the tests in `treerec/tests` and then to port the scheme to `pyslim/tests`. Do you think this might work @petrelharp ?

**Comment by petrelharp** [comment]
That sounds like a promising plan, and I like it that we don't have to add the unique-directory-creating code to the SLiM script.

Looks like I might need to understand fixtures, also.

**Comment by hyanwong** [comment]
> Looks like I might need to understand fixtures, also.

Yes, they baffle me. I had a longish chat with Ben Jeffery to get started, so I'm a little more up on this. But I'm still confused!

**Comment by hyanwong** [comment]
Done with https://github.com/MesserLab/SLiM/pull/142
