### ISSUE TITLE
Add '-h[elp]' flag to command line slim (trivial)

### ISSUE THREAD

**Issue by hyanwong** [MesserLab/SLiM#141]
I was expecting to be able to type `slim -h` (or even `slim --help`) on the command line to get a bit of info on running slim. Instead, I get this by simply typing `slim` with no commands. I guess it would be trivial to add the `-h[elp]` flag to do the same as if you give no commands? This would make it a little more consistent with other command-line programs.

**Comment by bhaller** [comment]
A related problem seems like the fact that `slim -h` gives the error `ERROR (main): could not open input file: -h`, which is dumb.  Any bad flag should result in the usage being printed; that used to work, so it regressed at some point.  But `-h` and `--help` and similar should result in the full info being printed, not just the usage, also.

**Comment by hyanwong** [comment]
>  But `-h` and `--help` and similar should result in the full info being printed, not just the usage, also.

Yes, that would be better, if it's easy.
