### ISSUE TITLE
Desktop File & Organization Name Issue

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#143]
Desktop integration in Fedora 33 Workstation (Gnome desktop environment) is partially broken. The issue is not present on CentOS or Ubuntu, despite no change in the sources.

- Application menu does not have an icon and the name is reported as "edu.MesserLab.SLiMgui"
- The Dash does not have an applicaiton icon

**Comment by bryce-carson** [comment]
The organization name in the Qt sources should be "org.messerlab", not "edu.messerlab", as the domain name for the organization is messerlab.org. There are multiple files that have this difference.

The Free Desktop files are all named "org.messerlab" for the above stated reason; the patch is a cludge until, if, the edit is made across the other files in the sources.

**Comment by bhaller** [comment]
OK.  Are you planning to submit a PR for renaming those other files, then?  Do you need me to do something here?

**Comment by bryce-carson** [comment]
I can look into making a PR for it. I'm not sure if it would impact anything in XCode, but it shouldn't if it is only "where is the application developer on the internet?" (messerlab.org).

**Comment by bhaller** [comment]
> I can look into making a PR for it. I'm not sure if it would impact anything in XCode, but it shouldn't if it is only "where is the application developer on the internet?" (messerlab.org). In this moment, desktop integration is restored with that merge; the rest is convention for the "reverse" domain name in the X Desktop specs.

If we're talking about the Free Desktop files that you added to the repo a while back, Xcode doesn't know anything about them; they're not added to the Xcode project.  Should be 100% safe.  Those files are yours to do with as you see fit.  :->  Thanks!

**Comment by bryce-carson** [comment]
Sorry, I meant the appearance of "messerlab.edu" on lines such as [this](https://github.com/MesserLab/SLiM/blob/abb51d8253db64837279c63e275d8859d191fbb0/QtSLiM/QtSLiMAppDelegate.cpp#L128) may possibly be renamed to "messerlab.org". The organization name should point to the domain name, was what I meant. It's nit-picking, though; it shouldn't impact anything to leave it as it is now that the commit on the .desktop has been merged.

**Comment by bhaller** [comment]
> Sorry, I meant the appearance of "messerlab.edu" on lines such as [this](https://github.com/MesserLab/SLiM/blob/abb51d8253db64837279c63e275d8859d191fbb0/QtSLiM/QtSLiMAppDelegate.cpp#L128) may possibly be renamed to "messerlab.org". The organization name should point to the domain name, was what I meant. It's nit-picking, though; it shouldn't impact anything to leave it as it is now that the commit on the .desktop has been merged.

I see.  I believe changing that would change the location where Qt saves its prefs, and so the user would lose their preferences if they have been modified.  Is that organization name connected up to the Free Desktop stuff?  I thought it was purely a Qt thing.  If there's no user-visible impact of leaving it as it is now, then yes, let's leave it.

**Comment by bhaller** [comment]
And thanks for the fix for Fedora!  :->

**Comment by bryce-carson** [comment]
It happens that this causes a minor issue when using the Gnome Classic environment. The application title in the Application Menu will be set to "QtSLiM," as we have `QCoreApplication::setApplicationName("QtSLiM");` in QtSLiMAppDelegate.cpp.

I can make another source modification in the Fedora package, or we could make the application and organization identity conformant upstream. The modification is very easy to do in the packaging process. I could make the identity changes as well to make globs for "messerlab" consistent and predictable, such as "where is the configuration file for SLiMgui?"
```bash
for dir in {$HOME/.config,$(echo $XDG_DATA_DIRS | sed 's/:/\ /'),$(echo $XDG_CONFIG_DIRS | sed 's/:/\ /')}; do
find $dir -name "*messerlab*"
done
```
Which should turn up not just the desktop integration files, but also the application preferences .conf file, which is stored as `$HOME/.config/MesserLab/QtSLiM.conf` at present.

P.S.: I've made the changes in my package and I am testing them; I have included a new section in the RPM that checks for any existing SLiMgui (QtSLiM) preferences and renames them, so preferences are retained. Let me know what you think, @bhaller. :)

**Comment by bhaller** [comment]
The application name "QtSLiM" is causing more trouble than it's worth.  I propose to change it; the only thing that will happen as a result, I think, is that people will lose their SLiMgui pref choices and have to make them again, which is not the end of the world.  Shall I commit that change?

**Comment by bryce-carson** [comment]
That works, yep. Be sure to set the organization _domain_ to "messerlab.org" as well. Organization name can remain as "MesserLab", however.

On Fedora, as I said, it was easy to rename the .conf file during package upgrade so preferences aren't lost (which isn't a big deal because there aren't a lot), but couldn't reading an old plist in an app bundle be done on OSX?

**Comment by bhaller** [comment]
OK, I've just committed what I hope is the right change; let me know.  :->

I'm happy to just let the preferences be lost.  I would say let's *not* try to rename the old file, etc., on any platform; the possible risks (ending up with a corrupted prefs file somehow, overwriting the user's prefs against their wishes when they're keeping/installing multiple versions or something, etc.) are not worth it; the Law of Unintended Consequences looms large for things like this.  Let's just make a clean break, do it right, and then we're good from then on.  :->

**Comment by bryce-carson** [comment]
Okay, I won't push that section of the rpm, then, but just the necessary changes.

**Comment by bhaller** [comment]
Thanks @bryce-carson.  Let me know when I should close this issue (or close it yourself, if GitHub will let you).
