### ISSUE TITLE
Unexpected homozygote inheritance

### ISSUE THREAD

**Issue by elcortegano** [MesserLab/SLiM#145]
I was writing a configuration file that write output in plink PED format, and on the way I was testing the correspondence between alleles inherited and parents assigned in the pedigree. However, I have come to some examples where inheritance seems wrong (unless I am misunderstanding something), and individuals are born homozygote for alleles present in only one parental (attached configuration file in [pedigree.zip](https://github.com/MesserLab/SLiM/files/5835317/pedigree.zip)).

The output is the following, where I have included a field "Pedigree" showing the numerical ID (+1) of individuals and parents.

```
// Initial random seed:
2979381301912

// RunInitializeCallbacks():
initializeSLiMOptions(keepPedigrees = T);
initializeMutationRate(0);
initializeMutationType(1, 0.5, "f", 0);
initializeGenomicElementType(1, m1, 1);
initializeGenomicElement(g1, 0, 3);
initializeRecombinationRate(0);

// Starting run at generation <start>:
1 

Pedigree:
id	dam	sire
1	0	0
2	0	0
#OUT: 1 A
Version: 3
Populations:
p1 2 H
Mutations:
0 0 m1 0 0 0.5 p1 1 1
1 1 m1 1 0 0.5 p1 1 1
2 2 m1 2 0 0.5 p1 1 1
3 3 m1 3 0 0.5 p1 1 1
Individuals:
p1:i0 H p1:0 p1:1
p1:i1 H p1:2 p1:3
Genomes:
p1:0 A 0
p1:1 A 1
p1:2 A 2
p1:3 A 3
Pedigree:
id	dam	sire
3	2	1
4	1	2
#OUT: 2 A
Version: 3
Populations:
p1 2 H
Mutations:
1 0 m1 0 0 0.5 p1 1 1
2 1 m1 1 0 0.5 p1 1 1
0 3 m1 3 0 0.5 p1 1 2
Individuals:
p1:i0 H p1:0 p1:1
p1:i1 H p1:2 p1:3
Genomes:
p1:0 A 0
p1:1 A 0
p1:2 A 1
p1:3 A 2
```
What bugs me is this situation that sometimes one individual is homozygous for some allele, while having different parents. Note that here in the first generation four mutations are generated so that both parents are heterozygous for different allele sets. In the second generation, individual with ID = 3 (and genomes p1:0 and p1:1) is homozygous for the allele 0. This allele was named allele 3 on the previous generation, and was carried by individual with ID = 2 only, suggesting the allele has been "copied" and individual ID = 1 do not contribute to ID = 3 genome. Is this a bug? why cannot see alleles inherited from ID = 1 to ID = 3 in this case?

Thank you

**Comment by bhaller** [comment]
Hi!  I think your misunderstanding is stemming from the fact that you're outputting the pedigree information in an `early()` event.  You are therefore not seeing, anywhere in your output, the pedigree information for the final generation produced, where the homozygosity occurs.  If you change your `1:2 early()` event to a `1:2 late()` event, then with the same random number seed, the final generation's information looks like this:

```
Pedigree:
id	dam	sire
5	4	4
6	3	3
```

As you can see, both individuals are the product of selfing in this generation, explaining the genetics.  The pedigree information is now being output at the same point in the generation cycle as the `outputFull()` calls, making the output easier to interpret.  No bug here, so I'm going to close.  :->
