### ISSUE TITLE
build under GitHub Actions with macOS 10.15 and Qt 5.9.5 should not fail

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#146]
OK, so this is a bit of a weird one, @grahamgower.  The macOS 10.15 / Qt 5.9.5 build in GitHub Actions is presently failing:

https://github.com/MesserLab/SLiM/actions/runs/502651719

And I know exactly why it's failing: it's because I put in a check for macOS builds using Qt versions less than 5.15.2, with a `#error` directive in SLiMgui's code if that version requirement is not satisfied (at QtSLiMAppDelegate.cpp:61):

```
#ifdef __APPLE__
// On macOS we enforce Qt 5.15.2 as a hard limit; macOS does not have Qt preinstalled, and there is
// not much reason for anybody to use a version prior to 5.15.2 for a build.  5.15.2 is the only
// LTS version with support for macOS 11, dark mode, and various other things we want.  However,
// if you need to build against an earlier Qt version (because you're using a macOS version earlier
// than 10.13, perhaps), you can comment out this #error line and your build will probably work;
// just note that that configuration is unsupported.
#if (QT_VERSION < QT_VERSION_CHECK(5, 15, 2))
#error "SLiMgui on macOS requires Qt version 5.15.2 or later.  Please uninstall Qt and then install a more recent version (5.15.2 recommended)."
#endif
...
```

However, as the comment there notes, users on macOS 10.12 or earlier might still want to build against an earlier version of Qt, because Qt 5.15 only supports back to macOS 10.13.  To allow for that possibility, I'd like to continue to have the Qt 5.9.5 build run on macOS, even though it's not an officially supported configuration.  (Ideally, it would be a macOS 10.12 / Qt 5.9.5 build, in fact, but I guess GitHub Actions doesn't have earlier versions of macOS, right?)

So, what to do?  I don't want to remove that configuration, because it's useful for the above reason.  I don't want to change the `#error` to a `#warning`, really, because then users will just not notice it at all; it'll just be a random warning sprinkled in among all the build spewage (warnings are really only useful for developers, not for end users).  What I'd *like* to do is make it so the build against Qt 5.9.5 succeeds with no error, but only if the build is happening under GitHub Actions, not in any other case.  To do that, I would need the GitHub Actions build to define a special C preprocessor flag that I could check in that error code above.

Is there a way to do that?  Or does GitHub Actions already define such a flag, which I could simply use?  Google searches like "github actions define preprocessor flag" don't seem to give anything useful.  @benjeffery I hope you don't mind me tagging you; you seem to know a lot about GitHub Actions!

**Comment by benjeffery** [comment]
You can set environment variables like:
```
env:
  CFLAGS: -D NO_QT_VERSION_WARNING
```
Would that work with your build system?

**Comment by bhaller** [comment]
@benjeffery that sounds perfect!  Thanks!

**Comment by bhaller** [comment]
Hi @benjeffery.  It doesn't seem to be working, and I don't know why.  You can see the current version of the YAML file here:

https://github.com/MesserLab/SLiM/blob/master/.github/workflows/tests.yml

I added:

    env:
      CXXFLAGS: -D NO_QT_VERSION_ERROR

inside the GUI job, which is where it's needed; as far as I can tell from the GitHub Actions doc, that is a legal place to put it.  I used CXXFLAGS instead of CFLAGS since the code in question is C++; as far as I can tell, that is the correct thing to do.  But the build still fails:

https://github.com/MesserLab/SLiM/actions/runs/504393986

So it seems that the flag is not getting defined.  Apologies for my cluelessness, but would you mind taking a quick look at this and telling me in what way, specifically, I am being an idiot?  :->  Thanks!

**Comment by bhaller** [comment]
Maybe this link brings up the specific build within that job that failed for the relevant reason:

https://github.com/MesserLab/SLiM/runs/1750737921?check_suite_focus=true

**Comment by bhaller** [comment]
Ah, I see.  cmake passes the flag along to the compiler, and so the cmake build succeeds.  But qmake does not seem to do this, at least as presently configured, and so the qmake build still fails.  So the YAML change is working fine, and I just need to figure out how to make qmake co-operate with the environment's CXXFLAGS value.  I'll work on that.  Sorry for the noise @benjeffery, your recommended fix is working great, the ball is in my court.  :->  Thanks!

**Comment by bhaller** [comment]
fixed
