### ISSUE TITLE
Manual Contributions and Corrections

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#148]
Hi @bhaller,

Should I email you for corrections and contributions to the SLiM or Eidos manuals? Could we create a repository for the manuals to allow contributions?

Regards.

# Correction in Section 2.2.1 (For users on Fedora)

The following in the Fedora installation instructions may be misleading (see the second quotation). The desktop integration has been tested and should not have any issues, except one possible issue on Wayland that I am working through and will correct when the solution is identified.

>The installed executables (slim, eidos, and SLiMgui) are placed in /usr/bin. ~~If that procedure 
works for you, you can skip right ahead to where it says **OK, now you have SLiMgui!**, in section 
2.4.2 below.~~ 

We might also append the following sentence to the above passage after the removal of the second sentence.

*/usr/bin is on the $PATH, so the `slim` and `eidos` command-line programs will be available in your terminal without any extra work; `SLiMgui` can also be launched from the terminal, but is integrated with the desktop environment in FreeDesktop compliant environments.*

>**OK, now you have SLiMgui!** You may notice that SLiMgui does not have an application icon 
until it is launched, and that it does not appear in the application launcher, and that the .slim file 
extension is not registered to SLiMgui (and so double-clicking .slim files in your Linux windowing 
system doesn’t launch SLiMgui and open the file), and so forth. These issues are external to 
SLiMgui itself; they have to do with how SLiMgui is registered as an application in the desktop 
environment. Section 2.4.4 will show how to fix those issues for the GNOME desktop 
environment in Ubuntu 18.04 LTS.

**OK, now you have SLiMgui!** also appears at the end of the Arch installation instructions, but I don't know if the Arch installer includes desktop integration.

# Contribution to Section 19.2

This is a placeholder while I write the contribution. The contribution is a suggestion to use `xargs` to prevent quotation games with Unix shells, something that was helpful in my workflow.

**Comment by bhaller** [comment]
> Hi @bhaller,
> 
> Should I email you for corrections and contributions to the SLiM or Eidos manuals? Could we create a repository for the manuals to allow contributions?

Hi @bryce-carson,

The manuals are Pages documents (a macOS app with a binary file format), so PRs for the doc on GitHub aren't possible, unfortunately.  Either email or opening an issue as you've done here is fine.  Maybe some day the manual will be ported off of Pages, but that's a huge and complicated undertaking, not least because the present workflow for generating the online doc inside SLiMgui depends upon the current Pages doc in tricky ways.

> # Correction in Section 2.2.1 (For users on Fedora)
> The following in the Fedora installation instructions may be misleading (see the second quotation). The desktop integration has been tested and should not have any issues, except one possible issue on Wayland that I am working through and will correct when the solution is identified.
> 
> > The installed executables (slim, eidos, and SLiMgui) are placed in /usr/bin. ~If that procedure
> > works for you, you can skip right ahead to where it says **OK, now you have SLiMgui!**, in section
> > 2.4.2 below.~
> 
> We might also append the following sentence to the above passage after the removal of the second sentence.
> 
> _/usr/bin is on the $PATH, so the `slim` and `eidos` command-line programs will be available in your terminal without any extra work; `SLiMgui` can also be launched from the terminal, but is integrated with the desktop environment in FreeDesktop compliant environments._

I see.  I didn't realize that the Fedora installer also did the desktop integration steps; I thought that was only in your Debian script.  So, it is in both?

In the Debian section I have, near the top:

It then attempts to integrate SLiMgui into the desktop environment, providing an application icon, double-clickable .slim files with a document icon, and other niceties (the success of this step may vary depending on your platform).  If this script works for you, then you are completely done.

Perhaps I should just say the same thing in the Fedora section, for parallelism?  Or perhaps I should remove that from the Debian section, and instead say what you propose for the Fedora section – i.e., parallelism in the opposite direction?

As for the note about $PATH, sure, I can mention that.  I suppose that should then be mentioned in the Debian section too.

> > **OK, now you have SLiMgui!** You may notice that SLiMgui does not have an application icon
> > until it is launched, and that it does not appear in the application launcher, and that the .slim file
> > extension is not registered to SLiMgui (and so double-clicking .slim files in your Linux windowing
> > system doesn’t launch SLiMgui and open the file), and so forth. These issues are external to
> > SLiMgui itself; they have to do with how SLiMgui is registered as an application in the desktop
> > environment. Section 2.4.4 will show how to fix those issues for the GNOME desktop
> > environment in Ubuntu 18.04 LTS.
> 
> **OK, now you have SLiMgui!** also appears at the end of the Arch installation instructions, but I don't know if the Arch installer includes desktop integration.

It does not, I believe.  But the "**OK, now you have SLiMgui!**" section only talks about GNOME on Ubuntu because that is the only platform those steps have been tested on.  I suspect, actually, that that whole section about doing the desktop integration manually ought to be removed; I think the way I recommend doing it is probably much worse than the way you do it in your scripts.  But that whole issue is rather opaque to me – I have yet to discover decent documentation for Linux desktop integration – so I haven't touched it thus far.

> # Contribution to Section 19.2
> This is a placeholder while I write the contribution. The contribution is a suggestion to use `xargs` to prevent quotation games with Unix shells, something that was helpful in my workflow.

OK; sounds good, I don't know anything about `xargs` :->.  You should just open a new issue for that contribution, when it's ready; let's keep this issue as just a discussion of the installation issues.

**Comment by bryce-carson** [comment]
> The manuals are Pages documents (a macOS app with a binary file format), so PRs for the doc on GitHub aren't possible, unfortunately. Either email or opening an issue as you've done here is fine. Maybe some day the manual will be ported off of Pages, but that's a huge and complicated undertaking, not least because the present workflow for generating the online doc inside SLiMgui depends upon the current Pages doc in tricky ways.

Okay. I do have a 2019 MacBook, so I could work with the Pages document directly if that would not cause any issues with the workflow. I don't know Pages very well, but I used it with some LaTeX last year to produce a report. Are there good diff features that would let you see changes, similar to how GitHub diffs work, and merge them into your copy?

> > # Correction in Section 2.2.1 (For users on Fedora)
> > The following in the Fedora installation instructions may be misleading (see the second quotation). The desktop integration has been tested and should not have any issues, except one possible issue on Wayland that I am working through and will correct when the solution is identified.
> > > The installed executables (slim, eidos, and SLiMgui) are placed in /usr/bin. ~If that procedure
> > > works for you, you can skip right ahead to where it says **OK, now you have SLiMgui!**, in section
> > > 2.4.2 below.~
> > 
> > 
> > We might also append the following sentence to the above passage after the removal of the second sentence.
> > _/usr/bin is on the $PATH, so the `slim` and `eidos` command-line programs will be available in your terminal without any extra work; `SLiMgui` can also be launched from the terminal, but is integrated with the desktop environment in FreeDesktop compliant environments._
> 
> I see. I didn't realize that the Fedora installer also did the desktop integration steps; I thought that was only in your Debian script. So, it is in both?

The desktop integration steps in the the Debian script are based off of the Fedora-family RPM, actually; I don't think there are even any changes. The desktop integration is the same, because the major desktop environments, Gnome and KDE, and most environments that aren't tiling window managers, are FreeDesktop compliant to some degree. The [Gnome Application Developer guides](https://developer.gnome.org/platform-overview/unstable/) offer some introductory information on [desktop integration](https://developer.gnome.org/platform-overview/unstable/dev-launching.html.en), but the [FreeDesktop specifications](https://www.freedesktop.org/wiki/Specifications/) are good for guiding how you should target *as many systems as possible* and not lock your desktop application in to a single environment (which is a little harder to do now, because of the FreeDesktop Group's efforts and many environments being "compliant-enough").

> In the Debian section I have, near the top:
> 
> It then attempts to integrate SLiMgui into the desktop environment, providing an application icon, double-clickable .slim files with a document icon, and other niceties (the success of this step may vary depending on your platform). If this script works for you, then you are completely done.
> 
> Perhaps I should just say the same thing in the Fedora section, for parallelism? Or perhaps I should remove that from the Debian section, and instead say what you propose for the Fedora section – i.e., parallelism in the opposite direction?
> 
> As for the note about $PATH, sure, I can mention that. I suppose that should then be mentioned in the Debian section too.

I think using the verb *attempt* is not the most accurate way to describe the process. If a user has a recent, relatively well-known desktop environment the process should work successfully regardless of what it is, except tiling window manager environments that are, in some ways, not a desktop environment (there is no "desktop" metaphor).

If you're comfortable with it, let's use the sentence I proposed. Text to be removed is striken out, and text to be added is included in bold.

---

For users on Debian and Ubuntu: Bryce Carson has kindly created an installation script for Linux distros in the Debian family, including Ubuntu. It downloads the source code archive for the current release version of SLiM, builds its targets with cmake and make, and installs slim, eidos, and SLiMgui in /usr/bin. ~~It then attempts to integrate SLiMgui into the desktop environment, providing an application icon, double-clickable .slim files with a document icon, and other niceties (the success of this step may vary depending on your platform). If this script works for you, then you are completely done.~~ **/usr/bin is on the $PATH, so the `slim` and `eidos` command-line programs will be available in your terminal without any extra work; `SLiMgui` can also be launched from the terminal, but is integrated with the desktop environment in FreeDesktop compliant environments.**  _**A Paragraph break might be appropriate here.**_ The script is hosted in the SLiM-Extras repository on GitHub, at https://raw.githubusercontent.com/MesserLab/SLiM-Extras/master/installation/DebianUbuntuInstall.sh. Note that it requires cmake, qmake, Qt, and either curl or wget to be installed on your system first; if they are not, it will print instructions on how to install them. Follow those instructions to install the needed packages, and then try running the install script again.
If this script works for you, then you are completely done. The script is hosted in the SLiM-Extras repository on GitHub, at https://raw.githubusercontent.com/MesserLab/SLiM-Extras/master/installation/DebianUbuntuInstall.sh. Note that it requires cmake, qmake, Qt, and either curl or wget to be installed on your system first; if they are not, it will print instructions on how to install them. Follow those instructions to install the needed packages, and then try running the install script again.

---
For users on Fedora, CentOS, and RedHat Enterprise Linux: Bryce Carson has kindly created an installer package for Linux distros in the Fedora family. Recent (Fedora 31+) versions of these distros appear to have a sufficiently recent Qt installed already, but if yours doesn’t, it will be installed alongside SLiM as a dependency. The installer is hosted on a COPR repository
(“copper”), a Fedora community service that builds packages and hosts third-party software repositories. The first step is to enable the COPR repository that Bryce has created:
sudo dnf copr enable bacarson/SLiM-Selection_on_Linked_Mutations
Then install slim, eidos, and SLiMgui using DNF, Fedora’s software package manager, which
will download the binary package for installation from Bryce’s COPR repository:
     sudo dnf install SLiM
The installed executables (slim, eidos, and SLiMgui) are placed in /usr/bin. ~~If that procedure works for you, you can skip right ahead to where it says OK, now you have SLiMgui!, in section 2.4.2 below.~~ **_/usr/bin is on the $PATH, so the `slim` and `eidos` command-line programs will be available in your terminal without any extra work; `SLiMgui` can also be launched from the terminal, but is integrated with the desktop environment in FreeDesktop compliant environments._**

---

> > > **OK, now you have SLiMgui!** You may notice that SLiMgui does not have an application icon
> > > until it is launched, and that it does not appear in the application launcher, and that the .slim file
> > > extension is not registered to SLiMgui (and so double-clicking .slim files in your Linux windowing
> > > system doesn’t launch SLiMgui and open the file), and so forth. These issues are external to
> > > SLiMgui itself; they have to do with how SLiMgui is registered as an application in the desktop
> > > environment. Section 2.4.4 will show how to fix those issues for the GNOME desktop
> > > environment in Ubuntu 18.04 LTS.
> > 
> > 
> > **OK, now you have SLiMgui!** also appears at the end of the Arch installation instructions, but I don't know if the Arch installer includes desktop integration.
> 
> It does not, I believe. But the "**OK, now you have SLiMgui!**" section only talks about GNOME on Ubuntu because that is the only platform those steps have been tested on. I suspect, actually, that that whole section about doing the desktop integration manually ought to be removed; I think the way I recommend doing it is probably much worse than the way you do it in your scripts. But that whole issue is rather opaque to me – I have yet to discover decent documentation for Linux desktop integration – so I haven't touched it thus far.

It might be useful to retain section 2.4.4, but with some changes I can make it specification conformant. The first sentence of the section properly guides Debian and Ubuntu users, and with the other references to this section striken out from the Fedora and Debian sections we are alright. I'm not familiar with Arch, but I might take a look at Manjaro (Arch-based) and see if I can sort out desktop integration there (each of the desktop environments provided by Manjaro, XFCE, KDE, and Gnome, are all FreeDesktop compliant). I would say base Arch Linux users are "on their own;" however, they can use the commands within the Debian build and install script if they are using a standard desktop environment; they're standard commands and should be available.

> > # Contribution to Section 19.2
> > This is a placeholder while I write the contribution. The contribution is a suggestion to use `xargs` to prevent quotation games with Unix shells, something that was helpful in my workflow.
> 
> OK; sounds good, I don't know anything about `xargs` :->. You should just open a new issue for that contribution, when it's ready; let's keep this issue as just a discussion of the installation issues.

Sounds good!

**Comment by bhaller** [comment]
> > The manuals are Pages documents (a macOS app with a binary file format), so PRs for the doc on GitHub aren't possible, unfortunately. Either email or opening an issue as you've done here is fine. Maybe some day the manual will be ported off of Pages, but that's a huge and complicated undertaking, not least because the present workflow for generating the online doc inside SLiMgui depends upon the current Pages doc in tricky ways.
> 
> Okay. I do have a 2019 MacBook, so I could work with the Pages document directly if that would not cause any issues with the workflow. I don't know Pages very well, but I used it with some LaTeX last year to produce a report. Are there good diff features that would let you see changes, similar to how GitHub diffs work, and merge them into your copy?

It does have a track-changes type feature, yes.  It doesn't really have Git-style merges, but merging your tracked changes in shouldn't be a problem.  I've just emailed you the manual.  It's about 18 MB, so we'll see whether it goes through email or not; many servers still have ridiculously low attachment size limits.  If not, I'll get it to you some other way.

So, rather than replying in detail to your proposed edits, which sound great to me, why don't you just have at the document and we'll take it from there?  You can put in your section 19.2 edits as well, and I'll just merge it all in.

**Comment by bhaller** [comment]
Hi @bryce-carson.  No rush, but just checking that you received the Pages doc I emailed you.

**Comment by bryce-carson** [comment]
Ah, yes. I did. I'll close this issue, and I will email you my changes when I have them ready.
