### ISSUE TITLE
InteractionType.strengthToPoint method?

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#162]
There's `distance( )` and `distanceToPoint( )` methods, and `strength( )` but no `strengthToPoint( )`. This would be convenient, for instance, in a model with interactions between species, and you want to get the interactions for one species (which is one population) with a given individual of the other (for which we extract its location as a point).

Maybe this is not terribly necessary, since you can just do e.g. `exp(-i1.distanceToPoint^2)`, but this would be conceptually clearer and less error-prone, since we set the 'interaction function' when defining the interaction.

**Comment by bhaller** [comment]
I think I had reasons for not doing this.  For one thing, interactions can be sex-specific, so the interaction strength with a "point" is maybe not well-defined, but you could argue that that's the caller's problem.  More problematic, perhaps, is that interaction strengths can be modified by interaction() callbacks, and those are defined in terms of a receiver and an exerter (which must live in the same subpopulation); it isn't clear how they would be defined/called in the case of strengthToPoint().  I feel like there was an even more compelling reason why I didn't do this, but it's not coming to mind right now...

**Comment by petrelharp** [comment]
Ah, I see. Ok, makes sense.

**Comment by bhaller** [comment]
Which is not to say that it wouldn't be useful.  It's something to think about.
