### ISSUE TITLE
CMake OpenGL Error on openSUSE Leap 15.2 (and Tumbleweed)

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#165]
I am attempting to build SLiMgui on openSUSE; this will allow users of this Linux distro to have a binary package available from the Copr repository, and eventually enables _"easy" installation on Windows 10! (with [GWSL](https://opticos.github.io/gwsl/))._

Here's the build error: 

```
 + cmake --parallel -DBUILD_SLIMGUI=ON ./SLiM-3.6/
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE is Release
BUILD_SLIMGUI is ON
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenGL.cmake:427 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:149 (find_package)


-- Configuring incomplete, errors occurred!
See also "/builddir/build/BUILD/CMakeFiles/CMakeOutput.log".
```

**Comment by bryce-carson** [comment]
I already resolved a CMake Error (a c++ compiler wasn't installed by default, or suggested alongside cmake on openSUSE) by fixing an omission in the RPM SPEC file. I don't think there are any others, but if you think it might not be a SLiM issue, then feel free to take a look.

[SLiM-3.6-4.fc33.src.rpm.zip](https://github.com/MesserLab/SLiM/files/6098876/SLiM-3.6-4.fc33.src.rpm.zip)

**Comment by bhaller** [comment]
It looks like the necessary OpenGL libraries are not installed.  Section 2.4.3 has some suggestions that might be relevant, like mesa-common-dev and libglu1-mesa-dev.  I don't think it's a SLiM issue; it has not yet started to try to compile any SLiM source file.

**Comment by bryce-carson** [comment]
Ah, yes, that makes sense.
I'm clueless when it comes to software compilation, so when there's a CMake Error I don't understand I generally suspect the CMakeLists.

Now I recall that this file is autogenerated by Qt Creator, right?

**Comment by bhaller** [comment]
> Ah, yes, that makes sense.
> I'm clueless when it comes to software compilation, so when there's a CMake Error I don't understand I generally suspect the CMakeLists.

:->

> Now I recall that this file is autogenerated by Qt Creator, right?

No, it's hand-written.  But the error is basically cmake saying "I can't find OpenGL".  That's probably an error in system configuration, in some way.  If OpenGL is installed, cmake should be able to find it; if it can't, then either cmake or OpenGL hasn't been configured properly.  That's my understanding, anyway.  I'm not very good at this cmake stuff either.  I find it rather frustrating that software developers are still wasting countless hours on these silly issues, in the year 2021.  :-<

**Comment by bhaller** [comment]
But that's me being grumpy.  :->

**Comment by bryce-carson** [comment]
I'll get around to determining which package is missing in the openSUSE conditional. Then we'll have another distro with binary packages.

I realized that, woops, we don't need to depend on this distro for an "easier" WSL Install. See my proposed instructions in the Extras repo. :happy:

Regardless, openSUSE is ahead on the road.

**Comment by bhaller** [comment]
> I've looked inside CMakeLists before. I would hate to write that by hand, it looks quite daunting and delicate.

Yeah, I dislike all work involving anything makefile-ish.  It's always unnecessarily complicated and cryptic, poorly documented, and difficult to test/debug.

> I'll get around to determining which package is missing in the openSUSE conditional. Then we'll have another distro with binary packages.

OK, that sounds great, although I don't know what "openSUSE" is.  :->

> I realized that, woops, we don't need to depend on this distro for an "easier" WSL Install. See my proposed instructions in the Extras repo.
> 
> Regardless, openSUSE is ahead on the road.

OK!  :->
