### ISSUE TITLE
Soft-wrapped lines in the Eidos Console are not parsed/interpreted as full lines

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#166]
### Platforms

- Fedora 33
- MacOS Catalina (latest patches applied)

### How to reproduce

1. Open the Eidos Console in SLiMgui
2. Type a long line that is soft-wrapped onto the next line. Alternatively, move the splitter to reduce the size of the text-input box to split a line.

### Observed behaviour

- A line, such as that pictured (`p1.genomes.mutationFrequenciesInGenomes();`), is correctly soft-wrapped.

1. The *virtual* line that the cursor is on determines what string is passed to the Eidos interpreter.
2. As the line is incomplete, various Eidos errors occur.

See the screenshot, and the code-block for further example of the behaviour.

#### The input text, copied directly from the text-box in the Eidos Console (the first line is properly unwrapped):
```Eidos
p1.genomes.mutationFrequenciesInGenomes();
sim.mutations;
sim.str();
```

#### The output from Eidos:
```
> nGenomes();
ERROR (EidosInterpreter::Evaluate_Call): unrecognized function name nGenomes.
> p1.genomes.mutationFrequenciesI
ERROR (EidosValue_Object_vector::GetPropertyOfElements): property mutationFrequenciesI is not defined for object element type Genome.
> 
```

![Screenshot_20210313_185035](https://user-images.githubusercontent.com/51974245/111054902-88e47380-842d-11eb-890d-178ee046ca02.png)

**Comment by bhaller** [comment]
Wow!  Well, that's clearly wrong.  :->
