### ISSUE TITLE
Feature Request: Code Completion

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#167]
It would be _nice_ if SLiMgui could offer code completion for Eidos. That's quite a feature, and I imagine it would take a lot of work if not using QScintilla (which would also be quite a task to migrate to, without also implementing a completion framework).

Would this be a workable feature request? Sometimes it is difficult to type in the _lower Camel-case_ style used for methods and properties. I also find myself always keeping the Scripting Help window open; that's not a bad thing for a framework of this size (`man` and `info` are indispensible too), but quick reference to check spelling or referring to something forgotten can become distracting when you're developing a model.

**Comment by bhaller** [comment]
It already does!  Press escape to complete.  Closing; reopen if I have misunderstood.

**Comment by bryce-carson** [comment]
Silly me! That's great! Thanks, Ben!
