### ISSUE TITLE
Feature request: load a json file into eidos as a Dictionary.

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#170]
JSON files are just lists, dictionaries, strings and numbers. All things that could well be parsed into an eidos `Dictionary`. Being able to load a json file at runtime would open a world of possibilities for user-written config-file-based modules written for SLiM.

**Comment by bhaller** [comment]
Sure, this ought to be easy.  I think I'd implement it as an extension to the Dictionary() constructor: if a string vector is passed as the sole argument to Dictionary(), that string vector gets parsed as JSON (perhaps multiple lines of JSON, thus vector) to construct the Dictionary.  Does that sound good?  So then you'd just read a JSON file in with readFile(), and pass the resulting string vector on to Dictionary(), which you could do in a single line of code, like d = Dictionary(readFile("path/to/file.json")) or whatever.

**Comment by bhaller** [comment]
It would also be trivial to make it possible to serialize a Dictionary out as JSON.  I imagine I'd do this as a [json=F] optional argument to the existing serialize() method on Dictionary; passing json=T would give you a JSON string instead of the current simplified serialization syntax.  You could then pass that to writeFile() if you wished.

**Comment by grahamgower** [comment]
Thanks Ben, those suggestsions both sound awesome! Ping @bodkan, who might have suggestions (and who'll certainly put it to good use).

**Comment by bhaller** [comment]
Too bad we didn't think of this for SLiM 3.6.  I'm hoping not to roll a new SLiM version for a fairly long time.  Would having this added to the GitHub head, but not to a release version of SLiM yet, suffice for your purposes?  I suppose not, if you want to use this in stdpopsim.  Hmm.

**Comment by grahamgower** [comment]
Oh, no rush. I certainly won't get around to using this for a couple of months at least.

**Comment by bhaller** [comment]
OK, great!

**Comment by bhaller** [comment]
OK, this is now done.  From the VERSIONS notes:

	add a [format='slim'] parameter to Dictionary.serialize(), adding support for JSON serialization with the 'json' format specifier (note the JSON serialization format changed slightly due to bug fixes)
	add a Dictionary(string$ jsonString) constructor for creating a Dictionary from a JSON serialization

It will be released in SLiM 3.6.1, whenever that happens.  It'd be great if you could give it a whirl at some point and make sure that it works for your purposes, prior to release.  Thanks for the suggestion!

**Comment by grahamgower** [comment]
Awesome, thanks @bhaller! I'll try to test it out sometime next week.
