### ISSUE TITLE
update links for msprime, tskit, pyslim

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#181]
Things have moved to tskit.dev, links should be updated in the manual and elsewhere.  I believe the pyslim doc is slated to migrate but has not yet done so, so fixing this is waiting for that to happen.  @petrelharp please ping here when the pyslim doc has moved, thanks!

**Comment by bhaller** [comment]
Hey @petrelharp, what's the status of this?

**Comment by petrelharp** [comment]
Ah, sorry - it's moved! We can update the links! https://tskit.dev/pyslim/docs/latest

**Comment by bhaller** [comment]
OK, this is fixed.  AFAICT the required changes were only in the manual; no code changes needed anywhere.  If you're aware of links that need updating outside of the manual, please let me know.
