### ISSUE TITLE
location of ladybugs is wrong when lines are wrapping

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#185]
Here is a screenshot of what happens after I click by line 35 in the script:
![Screenshot from 2021-05-20 08-44-19](https://user-images.githubusercontent.com/1046249/119009054-99422e80-b947-11eb-9239-6bc82933fadf.png)
... the ladybug shows up in the wrong place, by line 28! In fact, debugging output shows it's actually tagging line 28.  Experimenting a bit it seems to be shifted up by the number of lines above that point that are wrapped; so that for instance this puts it in the right place:
![Screenshot from 2021-05-20 08-47-00](https://user-images.githubusercontent.com/1046249/119009429-f63de480-b947-11eb-98a4-9b9c921e4461.png)

**Comment by bhaller** [comment]
So there's a bug with the bugs.  Hmm.  Naughty little bugs, running around where they're not supposed to be.

**Comment by bhaller** [comment]
I believe this is now fixed.  Very simple bug, just using the wrong Qt API to get the line that was clicked...
