### ISSUE TITLE
document conversion of Image.integerX to Image.floatX

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#187]
I'm using an image to specify local bias in dispersal; to do this I was using `2 * (Image.floatR - 0.5)` to obtain values between -1 and 1. So, in writing out images I was expecting the 'halfway point', with an `integerR` value of 127, to represent 0 (ie, no bias). However, I've found out that the `Image.floatR == Image.integerR / 255`, not `Image.floatR == Image.integerR / 256`, as I expected. 

At first I thought that maybe this was a bug - that the denominator should be 256. However, I guess we have to decide between "do we want 1.0" and "do we want a midpoint"; and I think the first thing is more important. Doing some googling it seems like there is no standard for how to do float->int for images.

So - I just think this should be documented. (and, maybe I'll work with the integers explicitly to avoid this problem...)

**Comment by bhaller** [comment]
I think this is documented.  The doc for Image, in the Eidos manual, says for floatR "Values will be in [0,1]", and says for integerR "Values will be in [0,255]", and similarly for other channels.  This behavior is very standard, AFAIK.  Given that this is documented, is there a bug here?

**Comment by bhaller** [comment]
Note that 8-bit values (such as are often used for the RGB channels of PNG images) range from 0 to 255.  That's where 255 comes from; any software that divides by 256 instead would simply be buggy and wrong, IMHO.  And so, with a total of 256 values (0 to 255), there is no value that is exactly at the halfway point.  That's not me making that decision, that's 8-bit graphics.  :->

**Comment by petrelharp** [comment]
Well, the values `(0:255)/256` *are* in `[0,1]`, although it would be more precise to say they're in `[0,1)`, so maybe I should have figured this out. But, to avoid confusion, I think it's worthwhile saying under `Image.floatR` that 
```
These values are obtained from the integerR layer by dividing by 255.
```

**Comment by bhaller** [comment]
ok, just pushed a doc fix
