### ISSUE TITLE
stacked nucleotide mutations appear in tree sequence

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#194]
This SLiM script:
```
initialize() {
    setSeed(23);
	defineConstant("L", 10);
	initializeSLiMOptions(keepPedigrees=T, nucleotideBased=T);
    initializeTreeSeq();
	initializeAncestralNucleotides(randomNucleotides(L));
	initializeMutationTypeNuc("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0, mmJukesCantor(4e-6));
	initializeGenomicElement(g1, 0, L-1);
	initializeRecombinationRate(1e-2);
}

1 {
	sim.addSubpop("p1", 10);
}

100000 late() {
    sim.treeSeqOutput("out.trees");
}
```
produces stacked mutations, as shown here:
```
import tskit

ts = tskit.load("out.trees")
for m in ts.mutations():
    if len(m.metadata['mutation_list']) > 1:
        print(f"Mutation {m.id} has stacked:")
        for i, md in zip(m.derived_state.split(","), m.metadata['mutation_list']):
            print(f"  SLiM ID {i}: {md}")
```
which outputs
```
Mutation 1 has stacked:
  SLiM ID 183: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 77045, 'nucleotide': 2}
  SLiM ID 86: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 38875, 'nucleotide': 1}
Mutation 2 has stacked:
  SLiM ID 224: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 91776, 'nucleotide': 1}
  SLiM ID 183: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 77045, 'nucleotide': 2}
  SLiM ID 86: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 38875, 'nucleotide': 1}
Mutation 6 has stacked:
  SLiM ID 82: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 36374, 'nucleotide': 1}
  SLiM ID 80: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 36062, 'nucleotide': 3}
Mutation 10 has stacked:
  SLiM ID 89: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 40118, 'nucleotide': 0}
  SLiM ID 44: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 23409, 'nucleotide': 2}
Mutation 12 has stacked:
  SLiM ID 108: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 46302, 'nucleotide': 3}
  SLiM ID 24: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 13095, 'nucleotide': 2}
Mutation 13 has stacked:
  SLiM ID 128: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 55867, 'nucleotide': 2}
  SLiM ID 108: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 46302, 'nucleotide': 3}
  SLiM ID 24: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 13095, 'nucleotide': 2}
Mutation 15 has stacked:
  SLiM ID 185: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 77552, 'nucleotide': 3}
  SLiM ID 93: {'mutation_type': 1, 'selection_coeff': 0.0, 'subpopulation': 1, 'slim_time': 40957, 'nucleotide': 2}
```

My suspicion is it has to do with substitutions, as this doesn't happen with shorter times.

**Comment by bhaller** [comment]
Ah, substitutions, yes.  That is intentional.  To make things work properly, every genome is considered to contain any mutation that has been fixed and substituted, IIRC.  It's a bit odd from the nucleotide-based perspective, I guess, but it makes crosscheck pass.  I'm pretty sure we talked about all this when we worked through the original design.  :->  So I'm inclined to close this as "works as designed", but if you really think it's wrong then let's talk about it.

**Comment by petrelharp** [comment]
Ah, ok. So, I guess it doesn't cause trouble on reading back in?

This is OK - but, is the most recent one the first or last one? I don't recall this being documented - we should make sure it is.

**Comment by bhaller** [comment]
See slim_sim.cpp:5635:

```
	// find and incorporate any fixed mutations at this position, which exist in all new derived states but are not included by SLiM
	// BCH 5/14/2019: Note that this means that derived states will be recorded that look "stacked" even when those mutations would
	// not have stacked, by the stacking policy, had they occurred in the same genome at the same time.  So this is a bit weird.
	// For example, you can end up with a derived state that appears to show two nucleotides stacked at the same position; but one
	// fixed before the other one occurred, so they aren't stacked really, the new one just occurred on the ancestral background of
	// the old one.  Possibly we ought to do something different about this (and not record a stacked derived state), but that
	// would be a big change since it has implications for crosscheck, etc.  FIXME
```

Gotta love those old FIXME comments.  :->

> Ah, ok. So, I guess it doesn't cause trouble on reading back in?

I believe that it does not, but I'm not sure that I have a test in my test suite that exercises this particular thing.  I'm pretty sure all of this got tested thoroughly back when we did the original work, though.

> This is OK - but, is the most recent one the first or last one? I don't recall this being documented - we should make sure it is.

As shown at the code referenced above, substitutions get added on to the end of the derived state.  Probably not documented, no.  Section 26.4.1 seems like the natural place to put it.  It already read:

> The derived state field for each mutation entry is actually a comma-separated list of mutation IDs, in ASCII, representing all of the stacked mutations present at the position in question after the addition (or removal) of a mutation; this is rather different from the way the derived state field is used in most mutation models.

I have just added another sentence:

> Note that fixed mutations (i.e., Substitution objects in SLiM) will be added on to the end of this derived state list, even in cases such as nucleotide-based models where mutations do not normally stack, because of the way substitutions are reconciled internally between SLiM and the tree sequence.

Does this seem sufficient, at least for now?

**Comment by petrelharp** [comment]
That seems good, yes. We can't tell the actual SLiM genotype from what's in the tree sequence without also knowing the stacking policy, but we've already thought about that a lot.
