### ISSUE TITLE
Syntax error in the Debian/Ubuntu installation script

### ISSUE THREAD

**Issue by JereKoskela** [MesserLab/SLiM#201]
I tried running the shell script installer (https://raw.githubusercontent.com/MesserLab/SLiM-Extras/master/installation/DebianUbuntuInstall.sh) on Kubuntu 18.04, and got the following:

bash: line 30: conditional binary operator expected
bash: line 30: syntax error near `satisfied.\n"`
bash: line 30: `[[ $qmakeinstalled == 0 && $qtchooserinstalled == 0 && $qtbase5devinstalled == 0]] || printf "All of: qt5-qmake, qtchooser, and qtbase5-dev must be installed.\nInstall the Qt5 requirements with 'sudo apt install qtbase5-d
ev qtchooser qt5-qmake'.\nInstalling these packages ensures all build\nand runtime requirements are satisfied.\n"'

The same syntax error showed up regardless of whether I ran the script locally, or directly from the web.

**Comment by grahamgower** [comment]
> stalled == 0]]

That doesn't look right. Maybe try inserting a space between the `0` and the `]]`?

**Comment by JereKoskela** [comment]
> That doesn't look right. Maybe try inserting a space between the `0` and the `]]`?

That gets rid of the syntax error, thanks!

**Comment by bhaller** [comment]
@bryce-carson

**Comment by bryce-carson** [comment]
@bhaller This has been fixed; we can close this issue.

**Comment by bhaller** [comment]
Thought it was already closed!  Thanks!
