### ISSUE TITLE
Accessing GSL's epsilon for floating point comparisons?

### ISSUE THREAD

**Issue by vsbuffalo** [MesserLab/SLiM#202]
As far as I can tell, SLiM doesn't have a way to access the machine's epsilon (which I think in this case is GSL's `GSL_DBL_EPSILON `). Did I overlook a way to do this from Eidos, and if not, could this be added? 

Also, a function like Python's `math.isclose()` and Numpy's `np.isclose()` could be useful too (a separate issue since the tolerance here is an argument rather than based on epsilon).

**Comment by bhaller** [comment]
Hmm, why do you want epsilon?  You are raising my eyebrows here.  The correct use of it in calculations is pretty technical.  See, e.g., the example code on this page: https://en.cppreference.com/w/cpp/types/numeric_limits/epsilon.  I'm finding it hard to imagine a legit reason to use it in a SLiM model!

Does is_close() basically just do `abs(x-y) < threshold`?  Is that worth additional API complexity?

**Comment by vsbuffalo** [comment]
I agree that it's tricky, and my usage case may in fact be getting that floating point stuff wrong.

In my case, I care about calculating the probability of fixation using Kimura's equation, which I have implemented in Eidos like:

        function (float)pfix(float ss, integer NN) {
          f = 0.5 / NN;
          a = 1 - exp(-2*NN*ss*f);
          b = 1 - exp(-2*NN*ss);
          p =  a / b;
          assert(isFinite(p));
          return p;
        }

Analytically, as s → 0, pfix → 1/2N. The question is how do we handle selection coefficients that (1) zero and (2) zero-ish floats.

Adding a conditional for the case that s == 0 is wrong, because there are cases where s is functionally zero as a float, and pfix should return 1/2N. So I want a threshold level that encapsulates the same logic as the analytic limit — wouldn't this be s ≤ machine epsilon? Anything else seems arbitrary given N can be anything (ignoring the limits of simulation).

**Comment by bhaller** [comment]
Hmm.  Well, epsilon is *not* zero, nor is it "functionally zero"; it's just a particular very small number.  Why treat it specially, any more than you would treat, say, 2*epsilon specially?  If epsilon underflows the calculation, then 2*epsilon probably does too, no?  It makes more sense to me to look at whether the calculation intermediates underflow.  I.e., if `1 - exp(-2*NN*ss)` == 0 then ss is small enough that the calculation has underflowed and you should return 1/2N, or something.  Or just look at whether the final result is INF, perhaps, and return 1/2N in that case?  Epsilon doesn't really have anything to do with approaching *zero*; it has to do with approaching *one*.  It's the smallest difference from 1.0 that can be represented.  The smallest difference from 0.0 that can be represented is almost 300 orders of magnitude smaller than epsilon, so if you cut off your calculation at epsilon you'd probably be clipping much higher than you need to.

**Comment by petrelharp** [comment]
I'm with Ben here - I'd use math, not machine epsilon. Let's see:

*note:* many languages have `exp1m()` to avoid the floating point imprecision in doing `1 - exp(x)` for small `x`. I'm not sure if that would solve the problem here or not?

Maybe the way I'd do this is to note that if
```
b = 1 - exp(-2*NN*ss)
```
then for some `C` that is I think maybe equal to 1,
```
abs( b - 2 * NN * ss ) <= C * (2 * NN * ss)^2
```
and you could just return `f` if `ss` is small enough that the amount of error is acceptible to you.

**Comment by bhaller** [comment]
> _note:_ many languages have `exp1m()` to avoid the floating point imprecision in doing `1 - exp(x)` for small `x`. I'm not sure if that would solve the problem here or not?

Well, C++ and R have `expm1()` for computing `exp(x) - 1` for small x; not sure whether that effectively comes out to the same thing or not.  Neither language appears to have `exp1m()`, according to a cursory search I just did.  If adding `expm1()` is helpful, I'm much happier adding that than I am adding epsilon.  But something like @petrelharp's proposal might do the trick without the need to add anything.

**Comment by petrelharp** [comment]
Sorry - I meant `expm1`, couldn't remember which way it went. (Note that if you *do* add `expm1` - not required - then you should also do `log1p`.)

**Comment by bhaller** [comment]
> Sorry - I meant `expm1`, couldn't remember which way it went. (Note that if you _do_ add `expm1` - not required - then you should also do `log1p`.)

Sure.  I'll wait until somebody has a use case for them, though.  Is this issue a use case for them?  If not, should it maybe be closed?  I'm not seeing an issue here that needs fixing, so far.

**Comment by bhaller** [comment]
I'm going to close this, since there's been no defense of it for three weeks.  :->  Of course it can be reopened if someone disagrees.
