### ISSUE TITLE
merge latest tskit

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#206]
Ben Jeffery says: "https://github.com/tskit-dev/tskit/releases/tag/C_0.99.14 is released! I'd love to get some testing here of the new large 64bit columns."  I guess it's time to merge the latest tskit into SLiM.  Want to do a PR, @petrelharp?  Once that's done, I can dig up the test case that triggered the metadata overflow and give it a whirl.  :->

**Comment by bhaller** [comment]
I just verified that this does indeed fix the metadata overflow problem that started us down this road in the first place.  The test model used to error out at generation 21400, now it keeps running.  I killed the process at 60000 generations and ~9 GB of memory usage; since it would run to generation 400,000 without ever simplifying, it would eventually bring my laptop down, so I didn't run it to completion, but that's a separate problem :->.  Thanks!

**Comment by petrelharp** [comment]
AWESOME!
