### ISSUE TITLE
WriteTreeSeq modifies tables

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#209]
Over in #208, @bhaller  pointed out that

> (Incidentally – WriteTreeSequence() [calls tsk_table_collection_sort() and tsk_table_collection_deduplicate_sites()]( https://github.com/MesserLab/SLiM/blob/master/core/slim_sim.cpp#L7294) on the simulation's tables, before it makes a copy of the simulation's tables with tsk_table_collection_copy(), when simplify=F, so calling treeSeqOutput(simplify=F) in Eidos has side effects on the simulation's tables; do we really want to be doing that before we copy the tables, or is that a separate bug?)

The deduplicate sites should be harmless; but the `sort` is a bit worrisome. On the one hand, we do both of these [during simplification](https://github.com/MesserLab/SLiM/blob/0627dcacfda8973aacde0c4ad1a3eb4b232eac51/core/slim_sim.cpp#L5304), so a sort of the tables as we go along ought to be OK in princple.  

Furthermore, I've just run a quick test, and inserting a call to `sim.treeSeqOutput` in the middle of a simulation does *not* the final output. (It does change the *order* of the *rows* in the final tree sequence, but the tree sequences are equivalent!)

And, let's see - after sorting and deduplicating sites, Simplify does
1. [simplify](https://github.com/MesserLab/SLiM/blob/0627dcacfda8973aacde0c4ad1a3eb4b232eac51/core/slim_sim.cpp#L5321)
2. [update map of remembered genomes](https://github.com/MesserLab/SLiM/blob/0627dcacfda8973aacde0c4ad1a3eb4b232eac51/core/slim_sim.cpp#L5326) which maps genomes to nodes
3. [record table position](https://github.com/MesserLab/SLiM/blob/0627dcacfda8973aacde0c4ad1a3eb4b232eac51/core/slim_sim.cpp#L5329) 

Skipping step (1) means the number of rows in the tables won't change, so step (3) is unnecessary. And, [tsk_table_collection_sort doesn't affect the node table](https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TableCollection.sort), so step (2) should be unnecessary also.

For completeness, here's the test that inserting a call to outputTreeSeq in the middle doesn't change anything:
with `recipe_nonWFa.slim`:
```
initialize()
{
    setSeed(23);
    initializeSLiMModelType("nonWF");
    initializeSLiMOptions(keepPedigrees=T);
    initializeTreeSeq();
    initializeMutationRate(1e-2);
    initializeMutationType("m1", 0.5, "f", -0.1);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 999);
    initializeRecombinationRate(1e-2);
    defineConstant("K", 100);
}

reproduction() {
    subpop.addCrossed(individual, subpop.sampleIndividuals(1));
}

1 early() {
    sim.addSubpop("p1", K);
}

early() {
    p1.fitnessScaling = K / p1.individualCount;
}

10 late() {
    sim.treeSeqOutput("a_gen10.trees");
   sim.simulationFinished();
}
```
and `recipe_nonWFb.slim`:
```
initialize()
{
    setSeed(23);
    initializeSLiMModelType("nonWF");
    initializeSLiMOptions(keepPedigrees=T);
    initializeTreeSeq();
    initializeMutationRate(1e-2);
    initializeMutationType("m1", 0.5, "f", -0.1);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 999);
    initializeRecombinationRate(1e-2);
    defineConstant("K", 100);
}

reproduction() {
    subpop.addCrossed(individual, subpop.sampleIndividuals(1));
}

1 early() {
    sim.addSubpop("p1", K);
}

early() {
    p1.fitnessScaling = K / p1.individualCount;
}

5 early() {
    sim.treeSeqOutput("b_gen5.trees");
}

10 late() {
    sim.treeSeqOutput("b_gen10.trees");
   sim.simulationFinished();
}
```
the only differences being
```
$ diff recipe_nonWFa.slim recipe_nonWFb.slim
26a27,30
> 5 early() {
>     sim.treeSeqOutput("b_gen5.trees");
> }
> 
28c32
<     sim.treeSeqOutput("a_gen10.trees");
---
>     sim.treeSeqOutput("b_gen10.trees");
```
and then running `python3 test_unchanged.py` where `test_unchanged.py` is
```
import tskit

ats = tskit.load("a_gen10.trees")
bts = tskit.load("b_gen10.trees")

assert ats.num_nodes == bts.num_nodes 
assert set([n.metadata['slim_id'] for n in ats.nodes()]) == set([n.metadata['slim_id'] for n in bts.nodes()])

bmap = {}
for j, n in enumerate(bts.nodes()):
    bmap[n.metadata['slim_id']] = j

at = ats.tables
bt = bts.tables

for n in at.nodes:
  m = bmap[n.metadata['slim_id']]
  assert bt.nodes[m] == n

node_map = [bmap[n.metadata['slim_id']] for n in at.nodes]

bt.subset(nodes=node_map, remove_unreferenced=False, reorder_populations=False)
bt.sort()

at.assert_equals(bt, ignore_provenance=True)
```
This last script is a bit complex because it has to reorder rows in the result to get them to match, but once this is done, then they do indeed match.

So - I think this is not a bug. However, moving the sort and deduplicate calls to after the table copy would be harmless, would be less confusing and possibly avoid other errors in the future.

**Comment by bhaller** [comment]
Awesome.  Thanks for looking into this.  So if I understand correctly, the code path where simplification is done for the write is 100% good, but the code path where simplification is not done for the write should move the tsk_table_collection_sort() and tsk_table_collection_deduplicate_sites() calls to happen on the copied table collection rather than the original.  Is that correct?  I'm a little confused because of where you write:

> Skipping step (1) means the number of rows in the tables won't change, so step (3) is unnecessary. And, tsk_table_collection_sort doesn't affect the node table, so step (2) should be unnecessary also.

I'm not clear on what you're saying there.  Are you saying that if we don't simplify, we actually don't need to do the tsk_table_collection_sort() and tsk_table_collection_deduplicate_sites() calls at all?  Or are you just saying that those two steps are the only two steps that we _do_ need to do, out of all the various things that simplify does?

**Comment by petrelharp** [comment]
>  the code path where simplification is done for the write is 100% good, but the code path where simplification is not done for the write should move the tsk_table_collection_sort() and tsk_table_collection_deduplicate_sites() calls to happen on the copied table collection rather than the original. Is that correct?

Yep - that's what I meant.

>  >   Skipping step (1) means the number of rows in the tables won't change, so step (3) is unnecessary. And, tsk_table_collection_sort doesn't affect the node table, so step (2) should be unnecessary also.
>
> I'm not clear on what you're saying there. Are you saying that if we don't simplify, we actually don't need to do the tsk_table_collection_sort() and tsk_table_collection_deduplicate_sites() calls at all? Or are you just saying that those two steps are the only two steps that we do need to do, out of all the various things that simplify does?

Steps 1-3 were the things that happened *after* sorting and dedup'ing in the simplify code path. Since we're pretty sure the simplify code path works fine, I was checking what the difference was. And, I convinced myself that if we didn't simplify (step 1) then we could also skip 2 & 3 and still have valid tables. (However, they'll still be reordered.)

**Comment by bhaller** [comment]
> Steps 1-3 were the things that happened _after_ sorting and dedup'ing in the simplify code path. Since we're pretty sure the simplify code path works fine, I was checking what the difference was. And, I convinced myself that if we didn't simplify (step 1) then we could also skip 2 & 3 and still have valid tables. (However, they'll still be reordered.)

I'm sick today, on too many meds for this to make sense to me, sorry.  If you want to submit a PR with the necessary change, go for it, otherwise I'll tackle this when I'm better...
