### ISSUE TITLE
allow loading from treeSeq even when treeSeq isn't enabled?

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#216]
Currently, trying to do `sim.readFromPopulationFile()` raises an error if you haven't done `initializeTreeSeq()`. Sometimes [people want to](https://groups.google.com/g/slim-discuss/c/qJga1wTPliE/m/nEg_mA4MCwAJ) run simulations without tree sequence recording, for speed, and so do things like
```
c.     Wrote a script to take the treesequence at time 0 and write a file in slim output
```
to move from a treeseq simulation to one without. However, I don't know of any reason that you shouldn't be able to load in a simulation from a tree sequence and yet not have tree sequence recording turned on? This would make it possible, for instance, to intiialize a giant simulation from an msprime simulation and run it without recording the tree sequence (for speed).

**Comment by bhaller** [comment]
Hmm.  If they want to do that, they can just dump the msprime output in MS or VCF format and load that in, no?  I guess you could make the case that the .trees file will be smaller, faster to load in, and express the pattern of mutations more concisely, so for a giant simulation perhaps it would work where MS/VCF wouldn't.  Hmm.  Well, I guess a .trees is "just another file format", in a sense, and there's no particular reason why users shouldn't use it to ferry data around even if they don't intend to use tree-seq recording in SLiM.  And I guess we can just (a) pretend that tree-seq recording is on, (b) load the .trees as usual, and then (c) throw all the tree-seq data structures away.  For some reason this makes me feel nervous, but I don't see a problem with the idea offhand...

**Comment by bhaller** [comment]
OK, this seems to work now.  I haven't tested it extensively, but I don't really see why there would be any weird edge cases; we just load and then throw away the tree-seq data structures.  Let me know if you see any problems.
