### ISSUE TITLE
hidden unicode characters can lead to strange Eidos errors

### ISSUE THREAD

**Issue by vsbuffalo** [MesserLab/SLiM#217]
I noticed when copying some code from the SLiM manual PDF that the example wasn't working as expected. The error was:

```
ERROR (EidosScript::Match): unexpected token '@f' in expression statement; expected ';'.

Error on script line 40, character 2:

  f = sim.mutationFrequencies(NULL, mut);
```

Upon looking at the SLiM file in `less`, I found a very subtle issue: a hidden Unicode character (`<U+2028>` "line separator") had been copied over. It may be worthwhile to explicitly warn about non-unicode characters. I've attached the file [here](https://github.com/MesserLab/SLiM/files/7214829/mre.slim.txt)
 since it's not clear how GitHub could reformat the problematic character. In `less` it looks like:

```
fitness(m2) {<U+2028>
  // the frequency dependent system in the SLiM manual
  f = sim.mutationFrequencies(NULL, mut);
  return 1.0 - (f - 0.5)*0.2;<U+2028>
}
```

**Comment by bhaller** [comment]
Thanks Vince.  Interesting that the stray Unicode is only at the end of one of the lines, not all of them.  The mysteries of PDF.  :->  To avoid this in future, you might wish to open recipes from the SLiM manual in SLiMgui; it has all of them built in for you, with no stray Unicode characters.  :->  In any case, it's a good bug; SLiM should give a better error message somehow.

**Comment by bhaller** [comment]
OK, now it should give a better error message:

```
ERROR (EidosScript::Tokenize): illegal Unicode character in token ' ' (note the illegal character may not print visibly).  Deleting it is recommended; if it is not visible, you might select across it and retype the text it is contained within.

Error on script line 38, character 13:

fitness(m2) { 
             ^^^
```

The fix should cover the Unicode characters that are most likely to cause problems, I think, including `<U+2028>`.
