### ISSUE TITLE
Should be able to get an Image representing a given spatial map

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#223]
Some SLiM API should exist to get an Image for a spatial map.  This can probably just be at the map's actual defined grid resolution; getting a higher-res interpolated version of the map is unnecessary, right?  Anyway, if support for interpolation is needed, `width` / `height` parameters should be easy enough to add later; for now it can assume that width and height are equal to the spatial map's resolution.  @petrelharp @gbradburd

**Comment by petrelharp** [comment]
Sounds great - a higher-res verison actually would be nice, because if the map is set to do interpolation in SLiM, a higher-res version would give us the map as actually seen by individuals in SLiM?

**Comment by bhaller** [comment]
> Sounds great - a higher-res verison actually would be nice, because if the map is set to do interpolation in SLiM, a higher-res version would give us the map as actually seen by individuals in SLiM?

Sure, OK; straightforward to implement I think.

**Comment by bhaller** [comment]
Done, seems groovy.
