### ISSUE TITLE
ideas for further support of dataframe-like Dictionaries

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#228]
In [https://github.com/bodkan/slendr/pull/66](https://github.com/bodkan/slendr/pull/66), @bodkan and I have discussed things he does in his slendr scripts to facilitate dataframe-like usage of `Dictionary`.  Some of those things could be carried over into Eidos.  To quote:

> > * filter(), also interesting.  Something like this could also conceivably be added to Eidos.
> > * num_rows(), ditto.  Possibly this idea of a Dictionary as a dataframe-like object ought to be more formalized.  Eidos could define a subclass of Dictionary named DataFrame that defined more of this sort of functionality.
> > * print_table(), ah, interesting.  Yes, the default print for Dictionary is not so readable when the Dictionary is, conceptually, a dataframe.  Again, if DataFrame were a subclass this could be handled in Eidos.
> 
> These would be very useful additions indeed, even after I make the JSON switch once the slendr "format" settles down.

So, the idea is to maybe make a `DataFrame` (`Dataframe`?) subclass of `Dictionary` that formalizes this usage pattern and provides additional support.  The fact that it's a `Dictionary` subclass would maybe not be something that is committed to formally; maybe that's an implementation detail that is not guaranteed to the end user, in case we want to shift to an underlying implementation more like R.  In any case, things like counting the number of rows in the dataframe, printing it in a readable way – and I forget what @bodkan's `filter()` does, but that too.  :->

Some dataframe-like functionality has already been put into `Dictionary`.  That might get moved down to the subclass, but that would break backward compatibility for those still using it.  It might therefore be left where it is – but that does clutter up the `Dictionary` interface, and makes for a confusing API design.  In particular, the `getRowValues()` method might move; `appendKeysAndValuesFrom()` might also.  IIRC, @grahamgower has an interest in this.  Comments/ideas welcome.

**Comment by petrelharp** [comment]
I vote for `DataFrame` over `Dataframe`. =)

**Comment by petrelharp** [comment]
Sounds perfect. My only suggestion is that you not worry about doing sensible CSV output for non-DataFrame dictionaries.

**Comment by bodkan** [comment]
This looks great, Ben!

One idea: functions such as `read_csv` and friends in _tidyverse_ in R have a `col_types` column which can be used to help the parser with determining column types (or perhaps override what would the parser normally guess to be the column type). For instance, specifying `read_tsv(..., col_types = "ciicl", ...)` would parse a table with column with types (in order) character, integer, integer, character, logical. For a more detailed description, see **`col_types`** under "Arguments" section of the [manual](https://readr.tidyverse.org/reference/read_delim.html).

Is the something that could be added to the interface? I don't think this is always needed, but I'm thinking about situations which motivated our "type inference" discussion w.r.t. R <--> slendr <--> SLiM in the first place. I.e. cases where R saves a number in one format, which is supposed to be an integer, but it's actually loaded as float, etc. There could perhaps be other similar cases. Giving the user the power to determine which exact types they want to get out of the csv/tsv might be useful.

**Comment by bhaller** [comment]
OK, `DataFrame` is added, `readCSV()` is added, serialize("csv") is added.  Doc for everything is live in SLiMgui if you build that from GitHub, otherwise I can email a new manual PDF to anybody who wants it.  Fallout should be minimal.  @bodkan it would be great if you could try porting `slendr` over to this and let me know if there are any additional features you need to make it work smoothly for you; you are the real-world test case for this, at the moment.  I didn't do anything equivalent to your `filter()` since that's trivial, and printing of `DataFrame` assumes an infinite-width console at the moment; let me know if that presents a problem for your usage of it.  Other things are more or less as discussed above.  `nrow` / `ncol` / `dim` ended up as properties, no reason for them to be methods.  Subsetting of `DataFrame` is less pretty than in R, since Eidos doesn't presently support operator overloading by classes, so you can't use `[]` or `$`, but the `subset()` / `subsetRows()` / `subsetColumns()` methods should work reasonably well (plus `getValue()` inherited from `Dictionary`).  I added a whole bunch of unit tests for the new stuff, but quite a bit of code got added here, so there might be bugs to be found; let me know if you see anything that seems wrong.  Thanks!

**Comment by bodkan** [comment]
Great! Thanks for the summary.

I'll get the SLiM GitHub dev version compiled later this week and start porting things over to the new `DataFrame`. I will open a PR in the slendr repo once I get something presentable.
