### ISSUE TITLE
integer versus float literals in Eidos need improvement

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#230]
Numeric literals like 5.5e5 are interpreted as float in Eidos even though they are representable as integer.  It would be nice to clean this up; in particular, it's a source of minor difficulty when command-line defaults are generated by languages like R that emit integers in floating-point notation.  There might be some cases where this change breaks backward compatibility, though, so it's worth pondering whether the payoff is worth it.

**Comment by bhaller** [comment]
If this is going to be fixed at all, it should be fixed for SLiM 4, since it will break backward compatibility.

**Comment by bhaller** [comment]
After reflecting on this, I've decided not to do it.  Besides the backward compatibility break that could introduce confusing bugs, the big problem is that if 5.5e2 comes out as integer 550, how does the user indicate float 550.0?  I mean, in _that_ case they can type 550.0 and get a float, but for larger numbers – 5.2378e6, say – you really want to be able to use scientific notation for the float and not be surprised by getting an integer, I think.

It's unfortunate, because for 5e2 versus 5.0e2 you can express which type you want, which is great, but for 5.5e2 you really can't – Eidos needs to choose one type or the other, and choosing float seems better overall, even though I'd really like to be able to get integer instead sometimes.

Of course languages like C resolve this sort of thing with weird additional syntax, like `550UL` indicating an unsigned long with value 550, if I recall correctly.  But that is too ugly; too technical for Eidos.

Closing; but @petrelharp if you have any ideas they would be appreciated.

**Comment by petrelharp** [comment]
Seems fine to me. The situation is a bit annoying, but there's no resolution to it that isn't. You can ask R to output things not in scientific notaiton (e.g. with `options(scipen=9)`, IIRC, or with `sprintf( )`); and in eidos the user can wrap things in `asInteger( )`.

**Comment by bhaller** [comment]
> Seems fine to me. The situation is a bit annoying, but there's no resolution to it that isn't. You can ask R to output things not in scientific notaiton (e.g. with `options(scipen=9)`, IIRC, or with `sprintf( )`); and in eidos the user can wrap things in `asInteger( )`.

Yep, OK, agreed.  Thanks.
