### ISSUE TITLE
make sure CI errors go away when tskit removes parent ordering

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#232]
See https://github.com/MesserLab/SLiM/runs/3946440358?check_suite_focus=true - currently the pyslim tests fail with
```
E           _tskit.LibraryError: Individuals must be provided in an order where children are after their parent individuals
```
... as expected. But this is a reminder to us to make sure that it works again.

**Comment by bhaller** [comment]
@rdinnager will want to enable the tskit tests for the Windows build once this is resolved; they are disabled for now, that that the Windows tests are green for him.  So, tagging him here so he's in the loop.

**Comment by bhaller** [comment]
OK, so.  I have merged tskit C_0.99.15 into SLiM, resolved all the issues with it that I can see, run all my local tests on it including crosscheck (all tests are green except for three known cases where the test suite fails crosscheck for unrelated reasons), and merged that `tskit_one_point_oh` branch down into `master`.  However, the CI tests are still failing with the same "Individuals must be provided in an order..." error.  This is a bit surprising to me.  The changes to tskit to remove the Individuals table ordering requirement are done, and are out in C_0.99.15, which is an official release.  I thought that the CI tests automatically ran against the current release version of tskit, so I expected the tests to go green now that everything is in sync... but they didn't.  @petrelharp, do you understand why?

**Comment by bhaller** [comment]
Aha.  I guess there's something I don't understand about tskit releases, then, because if I go to:

https://github.com/tskit-dev/tskit/releases

then "C API 0.99.15" is marked "latest"?  That's why I was expecting that this problem would fix itself.  Hmm.  Is the official Python release not in sync with the official C API release?

**Comment by bhaller** [comment]
See https://github.com/tskit-dev/tskit/issues/2065

**Comment by bhaller** [comment]
So, Ben Jeffery (deliberately not tagged) wrote:

> according to the log in the run you have linked above tskit 0.3.7 is being used. This is because you are using cached dependancies.

So, the mystery now is how to force a recache of the cached tskit 0.3.7, to move up to 0.4.0.  @grahamgower or @rdinnager or @petrelharp anybody know?  I'll start googling now but I don't know anything about this GitHub Actions stuff...

**Comment by bhaller** [comment]
Ben Jeffery then wrote:

> The caching is based on a hash of treerec/tests/pip-requirements.txt so any change to that file will force the dependencies to be regenerated.

So, I'm looking at that file.  It has:

```
setuptools
filelock
numpy
pytest
pytest-xdist
```

It does not list `tskit` or `msprime`; they are instead listed in `treerec/tests/conda-requirements.txt`.  I wonder whether changing that file also forces a recache?  And I wonder what sort of change I ought to make, to safely trigger the recache; are comments allowed in these files?  Extraneous spaces?

A comment about all this ought to be added to `treerec/tests/README.md` once it is figured out.

**Comment by grahamgower** [comment]
The cache step (docs [here](https://github.com/actions/cache)) has a `key` field that defines when to invalidate the cache:
```
key: ${{ runner.os }}-${{ matrix.python}}-conda-v10-${{ hashFiles('treerec/tests/conda-requirements.txt') }}-${{ hashFiles('treerec/tests/pip-requirements.txt') }}
```
So any change to the conda-requirements.txt or pip-requirements.txt should invalidate the cache. You can also bump the `v10` in that key field to invalidate the cache. Given you want to explicitly use the newer tskit, I recommend adding `tskit >= 0.4.0b1` to the `pip-requirements.txt`.

**Comment by bhaller** [comment]
Hi @grahamgower.  I was just about try to bumping that `v10` to `v11` to see if it did anything; thanks for the reassurance on that point.  :->

> Given you want to explicitly use the newer tskit, I recommend adding tskit >= 0.4.0b1 to the pip-requirements.txt.

So, right now `tskit` is listed in `conda-requirements.txt` not `pip-requirements.txt`.  Are you proposing that I should add `tskit >= 0.4.0b1` to `pip-requirements.txt`, or did you mean that I should change the existing line in `conda-requirements.txt`?  Also, the `b1` should not be needed, right?  AFAIK version `0.4.0` is released.

**Comment by grahamgower** [comment]
> Hi @grahamgower. I was just about try to bumping that `v10` to `v11` to see if it did anything; thanks for the reassurance on that point. :->
> 
> > Given you want to explicitly use the newer tskit, I recommend adding tskit >= 0.4.0b1 to the pip-requirements.txt.
> 
> So, right now `tskit` is listed in `conda-requirements.txt` not `pip-requirements.txt`. Are you proposing that I should add `tskit >= 0.4.0b1` to `pip-requirements.txt`, or did you mean that I should change the existing line in `conda-requirements.txt`? Also, the `b1` should not be needed, right? AFAIK version `0.4.0` is released.

Oh, if its already in the conda-requirements, then yes, just whack in the version requirement there. And I didn't realise that tskit 0.4.0 had shipped --- not sure how I missed that .:0

**Comment by grahamgower** [comment]
> are comments allowed in these files? Extraneous spaces?

Yes, you can start a comment with a `#` in both pip requirements and conda requirements files.

**Comment by bhaller** [comment]
OK, the tskit version issue appears to be fixed:

https://github.com/MesserLab/SLiM/runs/4498983347?check_suite_focus=true

Thanks for the help @grahamgower and @benjeffery.

The tests are still red, but now for reasons having to do with pyslim I think.  So, @petrelharp, you can mark this as fixed when you've got that sorted.  :->

**Comment by benjeffery** [comment]
Sorry for leading you astray - I thought tskit would be in `treerec/tests/pip-requirements.txt`. We have wheels for Windows, OSX and linux for all of Python 3.7->3.10 so you don't have to use conda.

**Comment by grahamgower** [comment]
I don't recall precisely, but the conda bits were probably included to get msprime installed without gsl annoyances. Not sure if that's still needed (e.g. for windows).

**Comment by bhaller** [comment]
@rdinnager all tests are now green, yay!  IIRC you had disabled the tskit tests for Windows somehow, so that you could get your tests on Windows to go green.  I believe it is now time for you to re-enable them.  If you point me towards how/where you did it, I'm happy to make the change.  Thanks!
