### ISSUE TITLE
Error loading multi-population tree sequence file

### ISSUE THREAD

**Issue by ziyimo** [MesserLab/SLiM#238]
I was trying to continue a coalescent simulation in SLiM by first simulating with msprime, annotate the tree sequence with pyslim and then load it in SLiM.

When I tried to load the .tree file using `sim.readFromPopulationFile("initialize_test.trees");`
> ERROR (SLiMSim::__ConfigureSubpopulationsFromTables): subpopulation count mismatch; this file cannot be read.

I am struggling to understand what this error message means.
For reference, attached is the tree-sequence file I am trying to load. 
[ts.tar.gz](https://github.com/MesserLab/SLiM/files/7507628/ts.tar.gz)

Thanks!

**Comment by bhaller** [comment]
> ERROR (SLiMSim::__ConfigureSubpopulationsFromTables): subpopulation count mismatch; this file cannot be read.

I believe this is due to a bug that has been fixed (#168).  If you use the current GitHub head version of SLiM (instructions for doing so are in chapter 2 of the manual) this problem ought to go away.  If you still see a problem, please open a new issue with those details.  Good luck!
