### ISSUE TITLE
relatedness() needs improvement

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#245]
A user noticed that `relatedness()` has a logic error: if individuals A and B have grandparents 1234 for A and 1156 for B (i.e., B's two parents each had individual 1 as a parent, so 1 is B's grandparent twice), the values returned are (a) wrong, and (b) not symmetric – A.relatedness(B) != B.relatedness(A).  Delving into this, I have realized that this is actually a big can of worms and that in general it is both not terribly well-defined (if you go back far enough, everybody's relatedness is 1.0!) and horrifically complicated (what if an individual A has the same other individual B for both parent and grandparent due to inbreeding, etc.).  A perfect solution seems unlikely; but the goal, with `relatedness()`, has always been to provide something that is heuristically useful, not necessarily something that is correct in some absolute, definitive sense.  So, it needs to be fixed so that for relatively straightforward cases, such as the user encountered, it provides results that are (a) not clearly wrong, and (b) symmetric.  Even the correct path to achieve that modest objective is a bit unclear at the moment, so I'm putting this issue on GitHub to see whether there are opinions/discussion to be had.

Here's the new manual writeup that I propose; the most important new bit is the discussion of "assumptions" at the end:

--------------------------------

`– (float)relatedness(object<Individual> individuals)`

Returns a vector containing the degrees of relatedness between the receiver and each of the individuals in individuals.  The relatedness between A and B is always 1.0 if A and B are actually the same individual; this facility works even if SLiM’s optional pedigree tracking is not enabled (in which case all other relatedness values will be 0.0).  Otherwise, if pedigree tracking is turned on with initializeSLiMOptions(keepPedigrees=T), this method will use the pedigree information described in section 24.6.1 to construct a relatedness estimate.

More specifically, if information about the grandparental generation is available, then each grandparent shared by A and B contributes 0.125 towards the total relatedness, for a maximum value of 0.5 with four shared grandparents.  More complex cases, such as might arise if an individual’s two parents each shared one parent, are handled consistent with this simple case; essentially, the degree of consanguinity based upon the identities of the grandparents is being measured.  If grandparental information is unavailable, then if parental information is available it is used, with each parent shared by A and B contributing 0.25, again for a maximum of 0.5, again accounting for more complex cases such as one individual being the result of selfing (and thus having the same parent twice).  If even parental information is unavailable, then the relatedness is assumed to be 0.0.  Again, however, if A and B are the same individual, the relatedness will be 1.0 in all cases.

Note that this relatedness is simply pedigree-based relatedness, and does not necessarily correspond to genetic relatedness, because of the effects of factors like assortment and recombination.  If a metric of actual genetic relatedness is desired, tree-sequence recording can be used after simulation is complete, to compute the exact genetic relatedness between individuals based upon the complete ancestry tree (a topic which is beyond the scope of this manual).  Actual genetic relatedness cannot presently be calculated during a simulation run; the information is implicitly contained in the recorded tree-sequence tables, but calculating it is too computationally expensive to be reasonable.

This method makes a couple of assumptions.  One assumption is that generations are non-overlapping _or_ that incest never occurs; in other words, that an individual will not be both a parent and a grandparent to the same individual.  This assumption is necessary to make the calculations well-defined and easy to implement.  The relatedness() method attempts to check for violations of this assumption; if it sees a violation, it will raise an error.  Another assumption is that the grandparents (or the parents, if grandparents are not available) are themselves unrelated and that they are not inbred; this assumption is necessary because we have no information about their parentage, since SLiM’s pedigree tracking information only goes back two generations.  This second assumption cannot be checked for by SLiM, since the information needed to check it is not kept.  Be aware that in a model where inbreeding or selfing occurs at all (including “incidental selfing”, where an individual chooses itself as a mate), some level of “background relatedness” will be present and the second assumption will be violated.  In such circumstances, relatedness() will therefore tend to underestimate the degree of relatedness between individuals, and the greater the degree of inbreeding, the greater the underestimation will be.  If inbreeding is allowed in a model – and particularly if it is common – the results of relatedness() should therefore not be taken as an estimate of absolute relatedness, but can still be useful as an estimate of relative relatedness (indicating that, say, A is more closely related to B than to C).  A final assumption is that, in nonWF models, addRecombinant() is not being used, since the pedigree relationships involved are then too complex to trace.  This assumption is not tested for.

Note that the value returned by relatedness() is what is called the “coefficient of relationship” between two individuals (Wright, 1922; https://doi.org/10.1086/279872).  There is another metric, called the “kinship coefficient”, that is equal to one-half of the coefficient of relationship; if that is what you want, divide relatedness() by two.

--------------------------------

Please note that whatever is done with this method needs to be backward-compatible for the standard cases.  We cannot, in particular, change it to return the kinship coefficient rather than the coefficient of relationship, even if that might be desirable for some abstract reason.  Tagging @philippmesser @petrelharp.

**Comment by petrelharp** [comment]
I think this does it? I've tested some pretty convoluted things (in python) below:
```
class Ind():
    def __init__(self, x, parents):
        self.id = x
        self.parents = parents
    def __contains__(self, other):
        out = (other.id == self.id)
        for p in self.parents:
            out |= other in p
        return out
    def __eq__(self, other):
        return self.id == other.id

def relatedness(a, b):
    out = 0.0
    if a == b:
        out = 1.0
    else:
        if a in b:
            for p in b.parents:
                out += relatedness(a, p) / 2
        else:
            for p in a.parents:
                out += relatedness(p, b) / 2
    return out

i1 = Ind(1, [
     Ind(2, [
         Ind(3, []),
         Ind(4, []),
     ]),
     Ind(5, [
         Ind(6, []),
         Ind(7, []),
     ]),
])

i2 = Ind(9, [
     Ind(10, [
         Ind(11, []),
         Ind(12, []),
     ]),
     Ind(13, [
         Ind(14, []),
         Ind(15, []),
     ]),
])


full_sibs = (i1, Ind(8, i1.parents))
half_sibs = (i1, Ind(8, [i1.parents[0], i2.parents[0]]))
child = (i1, Ind(16, [i1, i2]))

assert relatedness(i1, i1) == 1.0
assert relatedness(i1, i2) == 0.0
assert relatedness(*full_sibs) == 0.5
assert relatedness(*half_sibs) == 0.25
assert relatedness(*child) == 0.5

#     i1  y       
#  i1   x
#    i2
assert relatedness(i1, Ind(16, [i1, Ind(17, [i1, Ind(18, [])])])) == 0.75

# u  v  u   y       
#  i1     x
#    i2
assert relatedness(i1, Ind(16, [i1, Ind(17, [i1.parents[0], Ind(18, [])])])) == 0.5 + 0.25 * 0.5

# c  d  e   f   c  d  e   c 
#   a     b       a     x   
#    i1             i2       
assert relatedness(
        i1,
        Ind(16,
            [i1.parents[0],
             Ind(17, [
                 i1.parents[1].parents[0],
                 i1.parents[0].parents[0]
             ])
            ]
        )
) == (0.5 * 0.5  # a
      + 0.25 * 0.25 # c
      + 0.25 * 0.25 # e
)

# c  d  e   f   c  i1
#   a     b       x     i1   
#    i1             i2       
assert relatedness(
        i1,
        Ind(16,
            [Ind(17, [
                 i1.parents[0].parents[0],
                 i1
             ]),
             i1
            ]
        )
) == (0.5 # i1-parent
      + 0.25 # i1-grandparent
      + 0.25 * 0.25 # c
)
```

**Comment by bhaller** [comment]
I'm not sure what this is doing, exactly.  What is the meaning of `if a in b`?  I don't see the operator `in` defined for Ind.

**Comment by petrelharp** [comment]
> a in b

This is defined by the `_contains_` method; it's True if `a` is in `b`'s pedigree.

**Comment by bhaller** [comment]
Yes!  This works!  Thanks a bunch!  I could see that recursion was needed, but the way the "if a in b" switches between two different approaches was the missing link.

**Comment by petrelharp** [comment]
Given the discussion over in [this commit](https://github.com/MesserLab/SLiM/commit/e381e726917f91f0d0d1e6aa9f453aa3c4794156), to fix this up for the case of sex chromosomes, this should maybe be re-opened, so that the discussion on this issue is in one place?

There, it's proposed that the solution is putting a `-1` in for ancestors from whom someone couldn't possibly have inherited a given sex chromosome. Looking more closely at what's going on, I don't think this is right, actually, since a `-1` means "an individual unrelated to anyone", when actually what we want is to say that inheritance can only go one particular way. 

So, for the X chromosome, one way to do the right thing, is to, for males, replace the father's ID by the mother (and, paternal grandparents by maternal grandparents), since it's analogous to selfing. (And for the Y, replace mother's ID by the father's.)

>  The problem with unit tests for this is that  ...

How about modifying the python code above to test it?

Here's some right answers for the X:
- mother-daughter: 0.5
- mother-son: 1.0
- father-daughter: 0.5
- father-son: 0.0
- female sibs: 0.5
- male sibs: 1.0
- a female and a male sib: 0.5
- male cousins sharing both of their maternal grandparents: 0.5

**Comment by bhaller** [comment]
Sure, happy to reopen this.

Re: testing in Python, that would be great.  Any chance you could do it?  Apologies if that's annoying, but Python just isn't a language I use at all.  I haven't started up a python environment in probably a couple of years, so it'd be a big ordeal of updating and installing, and figuring out the inevitable cascade of installation problems that python always seems to have, and then trying to remember how to use the rather bizarre python gui on the Mac, and on and on.  Today I need to focus on updating tskit in SLiM and sorting through those issues.

It also, in the end, only tests the python code, not the SLiM code, and those are two different beasts.  My primary concern is figuring out a good way to test the SLiM code, not the python code.  This issue can remain open until I figure out a way to do that.  I realize that what you're proposing is testing the *algorithm*, more than the code, and that python is a convenient place for you to do that; but it really isn't for me.  If it were in R that would work much better for me, as I use R quite frequently, and frankly it seems to work much better than Python does – the install issues with Python really turn me off to the whole language, every time I try to use it it wastes a day or two of my time.

**Comment by bhaller** [comment]
So, if you have time to test the algorithm in python, let me know and I'll wait for that; otherwise, I can optimistically make the change you suggest away from `-1` and then try to think of a way to test on the SLiM side, which of course ought to happen if possible.

**Comment by bhaller** [comment]
OK, I've got unit tests of relatedness in SLiM working, and I've put in a bunch of tests, although obviously many more could be written.  With your proposed fix to the sex-chromosome case @petrelharp, everything now seems to be working correctly.  If someone is inclined to write additional tests at some point, that would be great; but since there's no evidence of any further problems, and I need to get on with other things, I'm going to close this with my next commit.  Thanks for your help @petrelharp.

**Comment by bhaller** [comment]
OK, I've got unit tests of relatedness in SLiM working, and I've put in a bunch of tests, although obviously many more could be written.  With your proposed fix to the sex-chromosome case @petrelharp, everything now seems to be working correctly.  If someone is inclined to write additional tests at some point, that would be great; but since there's no evidence of any further problems, and I need to get on with other things, I'm going to close this with my next commit.  Thanks for your help @petrelharp.

**Comment by petrelharp** [comment]
The tests look great.
