### ISSUE TITLE
maybe allow group-level summaries in `summarizeIndividuals`?

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#249]
Suppose I'd like to compute the *covariance* between `fitnessScaling` and `tagF` (phenotype) *locally*, i.e., the covariance within each grid square. I could do this with `summarizeIndividuals` like so:
```
	// cov(x, y) == ( sum( x * y ) - sum(x) * sum(y) / n ) / (n - 1)
	grid_res = c(2, 2);
	sum_fitness = summarizeIndividuals(
		p1.individuals, grid_res, p1.spatialBounds,
		operation="individual.fitnessScaling;", gather="sum");
	sum_pheno = summarizeIndividuals(
		p1.individuals, grid_res, p1.spatialBounds,
		operation="individual.tagF;", gather="sum");
	sum_prod = summarizeIndividuals(
		p1.individuals, grid_res, p1.spatialBounds,
		operation="individual.fitnessScaling * individual.tagF;", gather="sum");
	counts = summarizeIndividuals(
		p1.individuals, grid_res, p1.spatialBounds,
		operation="1;", gather="sum");
	cov = ( sum_prod - sum_pheno * sum_fitness / counts ) / (counts - 1); // TODO: deal with dividing by zero
```
... but, this is a bit roundabout; it'd be much easier if the lambda in `summarizeIndividuals` had a variable `individuals` which was the vector of individuals in that particular grid square. Then we could *drop* the "`gather`" argument and just do:
```
	cov = summarizeIndividuals(
		p1.individuals, grid_res, p1.spatialBounds,
		operation="cov(individuals.tagF, individuals.fitnessScaling);");
```

I think the existing design is great and covers 95% of use cases, however, this is nice enough it's worth considering, I think.

**Comment by bhaller** [comment]
Perhaps both modes of operation could be supported.  I will ponder.

**Comment by petrelharp** [comment]
> Perhaps both modes of operation could be supported. I will ponder.

I vote for just one mode, so as to not overcomplicate things.

**Comment by bhaller** [comment]
Yes, true.  I'm probably having a hard time letting go of the current design because quite a bit of work went into it.  Sunken cost fallacy.

**Comment by petrelharp** [comment]
The docs look good to me; minor suggestion is to somehow make clear that "individuals" is a variable name in
```
a constant named individuals is defined 
```
by putting single quotes around it or something. (or, maybe that will be a different font in the help? I forget.)

**Comment by bhaller** [comment]
> ...minor suggestion is to somehow make clear that "individuals" is a variable name...

Yep, the typography will make that clear, I didn't go through the copy/paste about and put backquotes around the code symbols.  :->
