### ISSUE TITLE
reloading from file does not reproduce parent IDs

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#256]
Here's a MWE: first run this script:
```
initialize()
{
    setSeed(23);
    defineGlobal("TREES_FILE", "out.trees"); 
    initializeSLiMOptions(keepPedigrees=T);
    initializeTreeSeq();
    initializeMutationRate(1e-2);
    initializeMutationType("m1", 0.5, "f", -0.1);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 99);
    initializeRecombinationRate(1e-2);
}

1 early() { 
    sim.addSubpop("p1", 10);
}

10 late() {
	for (ind in p1.individuals)
		catn("Individual " + ind.pedigreeID + " has parents " + paste(ind.pedigreeParentIDs));
    sim.treeSeqOutput(TREES_FILE);
    catn("Done.");
    sim.simulationFinished();
}
```
and then this one:
```
initialize()
{
    setSeed(23);
    defineGlobal("TREES_IN", "out.trees"); 
    defineGlobal("TREES_FILE", "out2.trees"); 
    initializeSLiMOptions(keepPedigrees=T);
    initializeTreeSeq();
    initializeMutationRate(1e-2);
    initializeMutationType("m1", 0.5, "f", -0.1);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 99);
    initializeRecombinationRate(1e-2);
}

1 late() { 
    sim.readFromPopulationFile(TREES_IN);
	for (ind in p1.individuals)
		catn("Individual " + ind.pedigreeID + " has parents " + paste(ind.pedigreeParentIDs));
    sim.treeSeqOutput(TREES_FILE, simplify=F);
}
```

Notice on reloading that the individuals' parent IDs have dissappeared. I think there is no reason they can't be reloaded from the .trees file, so they should be? I think the fix would go in around [here](https://github.com/MesserLab/SLiM/blob/master/core/slim_sim.cpp#L8269), but I'm not sure of how everything there is working.

**Comment by petrelharp** [comment]
(I came across this because of the pyslim tests which check to see if round-tripping through SLiM leaves the trees file unchanged.)

**Comment by bhaller** [comment]
Sigh, must've broken with the recent individuals table changes or something?  Thanks for the report, this is bad.

**Comment by petrelharp** [comment]
Well, the recent changes added new information to the individual tables, that (apparently?) isn't being read in from the .trees file. So nothing broke, just the new stuff isn't working all the way. (note: I updated the link to where in the code I think this goes above)

**Comment by petrelharp** [comment]
I *think* we just need to add
```

                individual->pedigree_p1_ = subpop_info.pedigreeP1_[tabulation_index];
                individual->pedigree_p2_ = subpop_info.pedigreeP2_[tabulation_index];

```
to near  https://github.com/MesserLab/SLiM/blob/master/core/slim_sim.cpp#L8269 ?

**Comment by petrelharp** [comment]
I've got a maybe-fix at #257.

**Comment by bhaller** [comment]
Ah, I see, yes; I misunderstood.  Yes, seems like I just forgot to put the parental pedigree info back in.  I guess we have no way, in general, to put the grandparental pedigree info back, since we don't store it directly, so there is a loss there.  We could try to reconstruct it from the parents of the parents, but...?

**Comment by petrelharp** [comment]
>  I guess we have no way, in general, to put the grandparental pedigree info back, since we don't store it directly, so there is a loss there.

Yep - at least we can round-trip the tree sequence, if not the *complete* internal state (but we couldn't do that anyhow...).

**Comment by bhaller** [comment]
This was fixed by your PR, right?  Not sure why it didn't get auto-closed.  Closing now.

**Comment by petrelharp** [comment]
> This was fixed by your PR, right?

Yes, as checked by pyslim tests.
