### ISSUE TITLE
remove legacy metadata

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#259]
Since we're moving to 1.0, and some of the metadata structs have changed, I think it's time to *remove* all the legacy metadata stuff. This will break old code, but that has been deprecated for a bit now anyhow. We can throw an informative error, at least.

**Comment by bhaller** [comment]
Hmm, I don't see any pressing need to do this.  Lots of people on old versions of SLiM will be migrating to the new version, and we don't want to break their old `.trees` files if we can help it.  What's the upside of doing this?

**Comment by petrelharp** [comment]
Their `.trees` files won't be broken, it's their code that they'll need to update (which is easy).

The reason I'd like to do it is that since metadata schemas have changed, I'll have to do a bunch of work to keep the deprecated APIs still working. And, that's the point of deprecating them, so I don't need to maintain them when it gets burdensome.

**Comment by bhaller** [comment]
I think I'm not understanding what you're proposing.  I thought you were proposing removing support for all of the legacy metadata formats from SLiM – the old population table's metadata, for example, in `struct` instead of `JSON`.  If that's not what you're proposing, then what *are* you proposing?  Sorry if I'm being dense.

**Comment by bhaller** [comment]
Oh – maybe you intend this issue to be logged on pyslim, not SLiM??  If you have old legacy metadata support APIs in pyslim that you want to purge, I have no problem with that at all.  I just want the actual `.trees` files to continue to be readable if possible, to facilitate people upgrading without having to re-run all of their models, so I don't think SLiM can abandon any legacy metadata stuff (?).

**Comment by petrelharp** [comment]
Whoops, sorry - transferring this to pyslim. =)

**Comment by petrelharp** [comment]
Ah, I can't transfer from this repo; I'll just close it.
