### ISSUE TITLE
Add ability to set the time unit name

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#260]
Right now (SLiM 3.7) the time unit name recorded in the tree sequence is always `"ticks"`.  It'd be nice to be able to set it to other things, like `"years"` or whatever – whatever actual duration the user intends one tick of simulated time to represent.  Not sure whether anybody cares about doing this, though; nobody has asked for it yet.  @grahamgower @petrelharp maybe one of you cares?  :->

**Comment by bhaller** [comment]
This just became high-priority because of https://github.com/tskit-dev/msprime/pull/1953.  Recapitation should, by the sound of it, warn when the time units are not `"generations"`, and so setting the name of the time unit in SLiM is now important.

**Comment by grahamgower** [comment]
Maybe the time_units could be generations for WF simulations by default? I think everyone knows that this is a pretty loose approximation of biological "generations", but it's a useful one nonetheless.

**Comment by grahamgower** [comment]
Are multispecies simulations going to be non-WF only? I suppose in this case, one could do recapitation separately for each distinct species, taking care of the respective average inter-generation times.

**Comment by bhaller** [comment]
> Maybe the time_units could be generations for WF simulations by default? I think everyone knows that this is a pretty loose approximation of biological "generations", but it's a useful one nonetheless.

Yes, I was just thinking the same thing.  This seems right to me.  It will have to change to "ticks" if the WF model is multispecies, though, or if they use the multispecies facilities to alter the scheduling of their single-species model.  I'll try to remember to deal with that when the time comes.  :->

**Comment by bhaller** [comment]
> Are multispecies simulations going to be non-WF only? I suppose in this case, one could do recapitation separately for each distinct species, taking care of the respective average inter-generation times.

No, multispecies models will be either WF or nonWF, according to the present plan.  But what you say still holds; they would get a separate .trees file for each species, and would recapitate them separately, so as long as they handle time correctly for each, everything ought to work out fine.

**Comment by bhaller** [comment]
OK, adding a `timeUnit` parameter to `initializeTreeSeq()`; being able to get the time unit, change it as a simulation runs, etc., seems unnecessary, it just needs to be set up front for a given model.  Here's the proposed doc for this new parameter:

> The timeUnit parameter controls the time unit stated in the tree sequence when it is saved (which can be accessed through tskit APIs); it has no effect on the running simulation whatsoever.  The default value, NULL, indicates that a time unit of "generations" should be used for WF models in which one simulation tick represents one biological generation, whereas "ticks" should be used otherwise (e.g., for all nonWF models).  It may be helpful to set timeUnit to "generations" explicitly when modeling non-overlapping generations in a nonWF model, to tell tskit that the time unit does in fact represent biological generations; doing so may avoid warnings from tskit or msprime regarding the time unit, in cases such as recapitation where the simulation timescale is important.

**Comment by bhaller** [comment]
I added this caveat to the SLiM manual in section 17.10; @petrelharp, you may wish to emphasize this in the pyslim doc as well?
