### ISSUE TITLE
Should switch recipes over to sim_ancestry() from simulate()

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#262]
All the tree-seq recipes should be modernized to use current APIs such as sim_ancestry(), and the bit at the start of chapter 17 where it says "The recipes in this chapter are based upon SLiM 3.5, msprime 0.7.5, tskit 0.3.1, and pyslim 0.5" should be updated to modern version numbers.  This was mentioned in #242 but is not the focus of that issue, so I'm opening this separate issue.  It would be nice for SLiM 3.7, but it feels like it probably won't make it, which is OK – all the recipes still work, they're just a bit rusty.  @petrelharp let's do this when we're both a bit less slammed.  :->

**Comment by petrelharp** [comment]
Hm, this should be
```
mts = msprime.sim_ancestry(samples=5000, population_size=5000, sequence_length=1e8, recombination_rate=1e-8)
```
The change from 10000 to 5000 is because `samples` here means diploids, before it was haploids. (The population size was always diploids, though.)

**Comment by petrelharp** [comment]
And, let's see - 17.10 works, but should have these two lines changed:
```

ts = tskit.load("recipe_17.10_decap.trees")    # no simplify!

recap = pyslim.recapitate(ts, Ne=1e5, recombination_rate=3e-10, ancestral_random_seed=1)

```

**Comment by petrelharp** [comment]
Version numbers: sounds good.

**Comment by bhaller** [comment]
Hmm.  Well, I updated all of my Python stuff, after the usual several hours of tearing my hair out.  I then tried your proposed changes above for 17.10, and got this result:

```
Traceback (most recent call last):
  File "/Users/bhaller/Documents/Research/MesserLab/SLiM_project/Recipes/SLiM_Recipes/Recipe 17.10 - Adding a neutral burn-in after simulation with recapitation II.py", line 30, in <module>
    recap = pyslim.recapitate(ts, Ne=1e5, recombination_rate=3e-10, ancestral_random_seed=1)
  File "/Users/bhaller/Library/Python/3.9/lib/python/site-packages/pyslim/methods.py", line 78, in recapitate
    recap = msprime.sim_ancestry(
TypeError: sim_ancestry() got an unexpected keyword argument 'Ne'
```

With the old code, it did give a couple of deprecation warnings, but it didn't give an error; so that seems better.  The use of `pyslim.load()` instead of `tskit.load()` seems to make no difference, and gives no deprecation warning, and as I noted above, `pyslim.load()` is used in all of the recipes right now, not just 17.10.  So.  It may be that `pyslim.load()` should be changed to `tskit.load()` throughout, but I'm not sure of that change, and I don't want to screw things up, so I'm going to hold off on that for now, including for 17.10.  And it may be that `pyslim.recapitate` is the more modern API to use, but since the code supplied above gives an error, I'm going to hold off on that change too.  So I'm not going to touch 17.10 at all for now; it gives deprecation warnings, but it works.  I need to freeze for SLiM 3.7.1 now if I'm going to ship it in time, otherwise the release would potentially slip by several weeks due to other scheduling constraints.  So I'm moving forward.  If there are changes to 17.10 and other recipes that are needed, due to various deprecations, please log a separate issue on that and it will be addressed in the next release.  Thanks!

**Comment by bhaller** [comment]
I just opened #285 for the remaining issues.
