### ISSUE TITLE
add tskit tests to the CI process for the Windows builds

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#263]
So far, CI on Windows does not include the tskit tests, and indeed I don't think anybody has tried running a pyslim-centric workflow on Windows with native SLiM yet.  This is likely a job for @rdinnager; also tagging @petrelharp because pyslim and tskit tests.  :->  This will probably not happen for SLiM 3.7, which I think is fine; we just don't have time.

**Comment by rdinnager** [comment]
I started working on running the tests on Windows locally and ran into my first issue. The first run gave me 13 passed, 25 errors. Looking at some of the error logs, every one (so far) had an error like this:
```
ERROR (Eidos_DefineConstantsFromCommandLine): malformed command-line constant definition: RUN_DIR="C:\Users\rdinn\AppData\Local\Temp\pytest-of-rdinn\pytest-9\test_008 cyclical subpop.slim"
```

Looks like `pyslim` is passing `RUN_DIR` as a command line constant, and SLiM is not liking the Windows path. Having a quick look at `Eidos_DefineConstantsFromCommandLine()`, it looks like the string is being parsed by the interpreter (https://github.com/MesserLab/SLiM/blob/3f8be7513854c376b7018a3005c264da7683b74b/eidos/eidos_globals.cpp#L402). If I had to guess I would guess that it is the `':'` that is causing the problem since this is never found in unix paths and it is a token character in Eidos. Can either of you @bhaller or @petrelharp think of an easy way to get around this problem?

I'm also not sure why the 13 ones that worked didn't have this problem (perhaps they don't use a `RUN_DIR`?)

**Comment by bhaller** [comment]
Ah, I've got it.  This is intended to be an assignment of a quoted string:

`RUN_DIR="C:\Users\rdinn\AppData\Local\Temp\pytest-of-rdinn\pytest-9\test_008 cyclical subpop.slim"`

The problem is that in Eidos, backslashes are used to escape characters inside quoted strings.  So if I try just inputting this string constant in Eidos, here's what I get:

> "C:\Users\rdinn\AppData\Local\Temp\pytest-of-rdinn\pytest-9\test_008 cyclical subpop.slim"
ERROR (EidosScript::Tokenize): illegal escape \U in string literal "C:".

The backslash is taken as the start of an escape sequence, but `\U` is not a legal escape, so, error.  You've got a couple of options.  (1) Get the path with forward slashes instead, somehow, from Python I guess.  (2) Convert the backslashes to forward slashes.  (3) Double the backslashes to be `\\`, which means "no really, I want a backslash character".

It also seems odd to me that RUN_DIR, which I think is supposed to be a _directory_, is being assigned a file path.  In `init.slim` it does `setwd(RUN_DIR)`, which makes no sense with a file path.  That is later than where this error is occurring, so I don't think it is the cause of the error; but it might be symptomatic of a problem in the `.py` runner script on Windows.

These might be problems for @petrelharp to debug; I don't know how comfortable you are in Python, @rdinnager?

**Comment by bhaller** [comment]
@rdinnager did the submission to turn the pacman crank get put in?  That's the top priority right now; these tskit tests can miss SLiM 3.7 if things get complicated, but we want the pacman installer to be live when I announce SLiM 3.7 is possible.  Thanks!

**Comment by rdinnager** [comment]
Yes, I put the PR in earlier today. Just waiting for someone to review it
now.

Good point about the character escaping. I'm fairly comfortable in Python
so I could give debugging it myself ago. Any help much appreciated though!

**Comment by bhaller** [comment]
> Yes, I put the PR in earlier today. Just waiting for someone to review it now.

Ah, awesome!

> Good point about the character escaping. I'm fairly comfortable in Python so I could give debugging it myself ago. Any help much appreciated though!

I am basically illiterate in Python, so I'm no help, sorry.  Google says this should help, though:

https://www.geeksforgeeks.org/python-string-replace/

If the replace can easily be done only on Windows, that's best.  This looks helpful:

https://stackoverflow.com/a/1325587/2752221

But if it is easier to just _always_ replace backslashes with forward slashes, on every platform, I would guess that that is fine, actually; I would be surprised if backslashes ever occur in the paths on macOS/Linux.  So you could just do that for simplicity, and if it causes problems on the other platforms, then back off and make it a Windows-specific replacement...?

**Comment by rdinnager** [comment]
Ah thanks. Yes I think some combination of these applied to the run_slim()
function in the test directory should probably do it. I'll give it a try
tomorrow.

**Comment by grahamgower** [comment]
This could be useful to you:
https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_posix
