### ISSUE TITLE
unreadable profile report in SLiMgui due to background colors in dark mode

### ISSUE THREAD

**Issue by AnnaMariaL** [MesserLab/SLiM#270]
When using profiling in SLiMgui (**dark mode**), I face the problem that the white font becomes unreadable in combination with the background colors used in the profile report (see screenshot below). 
<img width="464" alt="Screen Shot 2022-01-10 at 1 33 05 PM" src="https://user-images.githubusercontent.com/19533720/148819900-38082de1-4a30-40b1-8f53-5e1d4558f5df.png">

I am using SLiM v 3.7. on macOS Mojave 10.14.16. 
I used Recipe 7.3 - Genomic structure, Part III (Chromosome organization) to generate the profile report in the screenshot. 

Best,
Anna

**Comment by bhaller** [comment]
OK, fixed this.  I fixed it by forcing the background color to white and the foreground color to black, for the profile results, whether you're in dark mode or light mode.  That seemed like the only reasonable solution, given that text needs to be colored in the report, and that the user could switch between light and dark mode *after* the report was generated.  Not ideal, but reasonable, I think.  Let me know if you see any other dark mode problems.  Thanks!
