### ISSUE TITLE
outputMutaions() : mut prevalence = genome_num ?

### ISSUE THREAD

**Issue by YuetongXU** [MesserLab/SLiM#271]
initialize(){
          defineConstant("pop_num", 50);
          defineConstant("save_path", save_path);
      
          initializeMutationRate(1e-7);
          initializeRecombinationRate(1e-8);
          initializeMutationType("m1", 0.5, "f", 0.0);
          initializeGenomicElementType("g1", m1, 1.0);
          initializeGenomicElement(g1, 0, 225000);
      
      }
      
      1 {
          defineConstant("simID", getSeed());
          for (i in 1:2)
              sim.addSubpop(i, pop_num);
      }
      
      4000 late() {
          sim.outputMutations(sim.mutationsOfType(m1), save_path + simID + "_p1-2_t4000.outputMutations");
          sim.outputFixedMutations(save_path + simID + "_p1-2_t4000.outputFixedMutations");
      }
      

SLiM version 3.6

After running the above code, it is found that there are a large number of mutation in the ’p1-2_t4000.outputMutations‘ file with a prevalence=100 (genome_num). The mutation with the prevalence=100 should be fixed, why does it still appear in the ’p1-2_t4000.outputMutations‘ file? As a control, no mutation appeared in the '_p1-2_t4000.outputFixedMutations' file.

Thank you very much !

**Comment by YuetongXU** [comment]
I know why it shows up like this, thanks

**Comment by bhaller** [comment]
Hi!  I'm curious to hear the reason, if you don't mind.  I could presumably figure it out with a little investigation, but if you already understand why, please post it here.  This is also useful for posterity, as others may find this issue by searching in Google etc.  Thanks!

**Comment by YuetongXU** [comment]
Hello! I personally understand that the purpose of most users considering multiple groups is to study the exchange of mutations between groups, so fixed mutations must also be treated as unfixed. As in p1 and p2, a mutation A->T occurred at site 12 of p1 at t=100 and was fixed at t=1000. However, this mutation does not exist at site-12 of p2, so individuals in p1 will bring the 12-site mutation when they move into the p2 population. So the 12-site mutation in p1 must also be tracked after fixation. So when t=2000 is output, the 12-site mutation in p1 will be output in outputMutation, but not in outputFixedMutation.

**Comment by bhaller** [comment]
OK, if I understand correctly the mutation is fixed in p1 but not p2.  Yes, SLiM only considers mutations to be "fixed" if they are fixed across the entire population, not just in one subpopulation.  Thanks for the clarification!  :->
