### ISSUE TITLE
`subpopulation p0 has been used already` when it hasn't

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#274]
We do not allow subpopulations to be re-used, since SLiM v3.7. However, here's a simple case that gets
```
ERROR (Population::AddSubpopulation): subpopulation p0 has been used already, and cannot be used again (to prevent conflicts).
```
even though the population in question, `p0`, has *not* been used before:
```
initialize() {
	if (T) {
		// errors
		initializeTreeSeq();
	} else {
	   // does not error
		initializeTreeSeq(simplificationRatio=INF);
	}
	initializeMutationRate(0.0);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
}

1 { sim.addSubpop("p2", 500); }
2 { sim.addSubpop("p1", 500); }
1000 { sim.addSubpop("p0", 500); }

2000 late() { sim.simulationFinished(); }
```

Note that (a) there is no error when adding `p1`; however, there *is* an error when (later) adding `p0`. The reason is that by the time we add `p0`, simplification has occurred, and so the population table has been filled out up to `p2` (with an empty slot for `p0`). Turning off simplification makes the error dissappear.

This problem popped up in stdpopsim: https://github.com/popsim-consortium/stdpopsim/issues/1177 when running [this model of archaic admixture](https://popsim-consortium.github.io/stdpopsim-docs/stable/catalog.html#sec_catalog_homsap_models_outofafricaarchaicadmixture_5r19); note that in that model the population IDs are: 0: Africans; 1: modern CEU; 2: modern CHB; 3: Neanderthal; 4: archaic non-human African hominids. Then `p0` is used for both modern and archaic human Africans, so the model first creates `p0`, then `p3` and `p4`, but errors when getting to the subpopulation split that creates `p1` and `p2`.

One way to fix this would be to redefine the model. However, this is not great, because we'd like to not shuffle around these IDs (that are part of the published API).

So, a better fix would be to allow re-using of population IDs that are in the population table *as long as the entries are NULL*. (Next, I'm going to go look at the code to check this actually makes sense.) This should work because I think that rows in the population table created by necessity to fill out a later row (as happened here) should have empty metadata, which distinguishes them from ones that were e.g., created and removed, or described in the input tree sequence.

**Comment by petrelharp** [comment]
Making this change would just require changing this bit to check if the corresponding entry in the table had non-empty metadata: https://github.com/MesserLab/SLiM/blob/master/core/slim_sim.cpp#L5633

**Comment by petrelharp** [comment]
Also, FYI - this is a bother for our stdpopsim development, but it's not affecting most people out there in the wild trying to use stdpopsim, so no worries on fixing this fast. (It would be nice to have an idea of whether this might make it into a SLiM point release or if we have to deal with it in some other way, though.)

**Comment by bhaller** [comment]
Hi @petrelharp.  Yeah, makes sense, too bad we didn't catch this bug before, oh well.

Well, there will be a point release eventually, and this fix can certainly be in it.  :->  You say "no worries on fixing this fast", and I don't presently have any plans for a new SLiM release; nothing of urgency has come up, just a few small issues and now this.  So, can this wait until whenever a point release does seem merited, which might be a couple of months?  Or should it be regarded as, in itself, justification for a SLiM 3.7.1 release?  I can do that, it's just a fair amount of work to turn the crank these days.

**Comment by petrelharp** [comment]
It can certainly wait until you're not on vacation, and I think we can have a more informed opinion from stdpopsim by that time.

**Comment by bhaller** [comment]
Yeah, not gonna do it now, just trying to pin out what the plan will be.  :->
