### ISSUE TITLE
"new dada generators"

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#275]
![Screenshot from 2022-01-28 09-33-35](https://user-images.githubusercontent.com/1046249/151594513-5599e6c9-a7fa-41a8-9efc-db4563f648ea.png)

**Comment by bhaller** [comment]
Um, hmm.

**Comment by bhaller** [comment]
Well, I suppose this is a typo and the message was supposed to say "data generators".  I will fix it accordingly.  Pretty funny, though!
