### ISSUE TITLE
Windows tests fail on installing msprime

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#277]
See for instance https://github.com/MesserLab/SLiM/runs/5028497404?check_suite_focus=true where we get:
```
Run C:\Miniconda\condabin\conda.bat activate anaconda-client-env
  C:\Miniconda\condabin\conda.bat activate anaconda-client-env
  git clone https://github.com/tskit-dev/pyslim.git
  cd pyslim && pip install .
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    MSYSTEM: MINGW64
Cloning into 'pyslim'...
Processing d:\a\slim\slim\pyslim
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting msprime>=1.0.1
  Downloading msprime-1.1.0.tar.gz (850 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting tskit
  Downloading tskit-0.4.1-cp37-cp37m-win_amd64.whl (394 kB)
Collecting kastore
  Downloading kastore-0.3.1-cp37-cp37m-win_amd64.whl (29 kB)
Collecting numpy
  Downloading numpy-1.21.5-cp37-cp37m-win_amd64.whl (14.0 MB)
Collecting newick>=1.3.0
  Downloading newick-1.3.2-py2.py3-none-any.whl (12 kB)
Collecting demes>=0.2
  Downloading demes-0.2.1-py3-none-any.whl (38 kB)
Collecting svgwrite>=1.1.10
  Downloading svgwrite-1.4.1-py3-none-any.whl (66 kB)
Collecting jsonschema>=3.0.0
  Downloading jsonschema-4.4.0-py3-none-any.whl (72 kB)
Collecting humanize
  Downloading humanize-3.14.0-py3-none-any.whl (98 kB)
Collecting attrs>=20.3.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting ruamel.yaml>=0.15.78
  Downloading ruamel.yaml-0.17.20-py3-none-any.whl (109 kB)
Collecting importlib-resources>=1.4.0
  Downloading importlib_resources-5.4.0-py3-none-any.whl (28 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp37-cp37m-win_amd64.whl (61 kB)
Requirement already satisfied: importlib-metadata in c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages (from jsonschema>=3.0.0->tskit->pyslim==0.700) (4.10.1)
Requirement already satisfied: typing-extensions in c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages (from jsonschema>=3.0.0->tskit->pyslim==0.700) (4.0.1)
Requirement already satisfied: zipp>=3.1.0 in c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages (from importlib-resources>=1.4.0->jsonschema>=3.0.0->tskit->pyslim==0.700) (3.7.0)
Collecting ruamel.yaml.clib>=0.2.6
  Downloading ruamel.yaml.clib-0.2.6-cp37-cp37m-win_amd64.whl (115 kB)
Using legacy 'setup.py install' for pyslim, since package 'wheel' is not installed.
Building wheels for collected packages: msprime
  Building wheel for msprime (pyproject.toml): started
  Building wheel for msprime (pyproject.toml): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'c:\hostedtoolcache\windows\python\3.7.9\x64\python.exe' 'c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpy49d6xhp'
       cwd: C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-dmlt1kdr\msprime_c4f4d41c514c4ae0aa44ad7f7542fe94
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_py
  running egg_info
  writing msprime.egg-info\PKG-INFO
  writing dependency_links to msprime.egg-info\dependency_links.txt
  writing entry points to msprime.egg-info\entry_points.txt
  writing requirements to msprime.egg-info\requires.txt
  writing top-level names to msprime.egg-info\top_level.txt
  setup.py:27: UserWarning: Error occured getting GSL path config: [WinError 2] The system cannot find the file specified
    warn(f"Error occured getting GSL path config: {e}")
  listing git files failed - pretending there aren't any
  reading manifest file 'msprime.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  running build_ext
  building 'msprime._msprime' extension
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  kastore.c
  git-submodules\tskit\c\subprojects\kastore\kastore.c(28): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  git-submodules\tskit\c\subprojects\kastore\kastore.c(568): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
Failed to build msprime
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  core.c
  git-submodules\tskit\c\tskit\core.c(139): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  tables.c
  git-submodules\tskit\c\tskit\tables.c(206): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  git-submodules\tskit\c\tskit\tables.c(207): warning C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  git-submodules\tskit\c\tskit\tables.c(358): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  git-submodules\tskit\c\tskit\tables.c(359): warning C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  git-submodules\tskit\c\tskit\tables.c(10670): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  git-submodules\tskit\c\tskit\tables.c(10752): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  trees.c
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  avl.c
  lib\avl.c(223): warning C4098: 'avl_free_nodes': 'void' function returning a value
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  fenwick.c
  lib\fenwick.c(31): fatal error C1083: Cannot open include file: 'gsl/gsl_math.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for msprime
ERROR: Could not build wheels for msprime, which is required to install pyproject.toml-based projects
WARNING: You are using pip version 21.3.1; however, version 22.0.2 is available.
You should consider upgrading via the 'c:\hostedtoolcache\windows\python\3.7.9\x64\python.exe -m pip install --upgrade pip' command.
Error: Process completed with exit code 1.
```

**Comment by bhaller** [comment]
Might be of interest to @rdinnager @clwgg.

**Comment by bhaller** [comment]
#278 got fixed so this can be closed, right @petrelharp?

**Comment by petrelharp** [comment]
Closed in #278

**Comment by bhaller** [comment]
@petrelharp, Windows tests now seem to be failing; is this related to this fix?  See, e.g., https://github.com/MesserLab/SLiM/runs/5071732614?check_suite_focus=true.  @rdinnager @clwgg.  Reopening for now, since it seems related...?

**Comment by petrelharp** [comment]
Well, that's an error that I encountered repeatedly in #278 and thought I got to go away finally, perhaps I did not. Perhaps someone else with a better understanding of what's going on can have a look?

**Comment by grahamgower** [comment]
Looking at the logs and the action file I don't see anything obvious. I can poke around a bit to try and figure it out, but probably not in the next couple of days.

**Comment by rdinnager** [comment]
I have an idea what might be wrong but I'll need to try some stuff out. Might take me a few days to get to though.

**Comment by petrelharp** [comment]
Thanks!!

**Comment by bhaller** [comment]
I'm hoping to roll SLiM 3.7.1 soon, because an important crashing bug in 3.7 got fixed.  If this issue could get resolved for the roll of 3.7.1, that would be great.  I know everybody is busy, so no worries if it just can't happen; but I wanted to let you all know that the schedule has suddenly changed because of that crashing bug getting fixed.  Now 3.7.1 has gone from a gleam in my eye to a fairly urgent priority, so anything that wants to ride along on the coattails of that fix needs to happen soon.  :->

**Comment by bhaller** [comment]
Thanks for the quick work @rdinnager!

**Comment by bhaller** [comment]
Sorry folks, it looks like the build is back to failing again (https://github.com/MesserLab/SLiM/actions/runs/1834222808), so I'm reopening this.  It may be that the failure is intermittent, and so it looks like it has been fixed, but then fails the next time you try to build, or something.  Anyway, we got a successful Windows build in there, so all the self-tests got validated for Windows, which is reassuring for the SLiM 3.7.1 release; so that's nice :->.  @rdinnager, do you have any ideas about how to get this working?

**Comment by grahamgower** [comment]
I think what's happening is that the following step is not calling the conda-installed python, but the python which is already in the CI host.
https://github.com/MesserLab/SLiM/blob/34c9113ee0e2f41e5458c5a8a858c876c1c4ed91/.github/workflows/tests.yml#L293-L299

The conda environment should have installed Python 3.8 (see matrix.python variable and the conda setup step), but the error from the logs indicate Python 3.7.x can't find pytest.
```
Run C:\Miniconda\condabin\conda.bat activate anaconda-client-env
  C:\Miniconda\condabin\conda.bat activate anaconda-client-env
  $env:path += ";$(pwd)\Release"
  cd treerec\tests 
  python -m pytest -xv
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    MSYSTEM: MINGW64
C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe: No module named pytest
```

**Comment by grahamgower** [comment]
I think I have an idea of the unerlying problem. The `conda-incubator/setup-miniconda` step installs conda, and inserts itself into various shell init files, like `sh`'s ~/.profile. I guess this also installs something into the powershell equivalent (one or more of the [many](https://devblogs.microsoft.com/scripting/understanding-the-six-powershell-profiles/) Profile.ps1 files?). The cache step doesn't include any Profile.ps1 file in its list of paths, so when conda is restored from the cache there is something lacking in the environment, and the conda-installed Python doesn't end up in the PATH.

I don't know enough about the details of powershell, nor what conda is actually doing during init, so I can't suggest a solution. Any ideas @rdinnager?

**Comment by petrelharp** [comment]
That makes sense! (!?!?!)

**Comment by rdinnager** [comment]
Honestly, I know virtually nothing about `conda`, and not too much about powershell either, so I have no idea how to solve this. I tried adding the `conda powershell init` line after the section that gets skipped when restoring the cache but that didn't work. The lazy person's solution (which I am leaning towards currently) would be to simply remove the caching step and just install `conda` and dependencies fresh each time the workflow is run. This is a bit wasteful of computational resources but I don't think this step takes that long to run. It may be at least a decent interim solution until I have enough time to research this a bit more deeply?

**Comment by bhaller** [comment]
I wonder whether there's some other GitHub project that we could crib from?  Somebody else must've figured this out already, right?  Not sure how to find that, though.

**Comment by rdinnager** [comment]
Here is one: https://github.com/aeon0/botty/blob/4a3b2cada4bbb79e88d4dbbd33753290004fba6c/.github/workflows/ci.yml

I don't have time to look this over and try and figure out what they did differently from us today. Will have a look tomorrow and try again. Most other projects I found using conda and powershell in CI didn't bother with caching..

**Comment by grahamgower** [comment]
I don't think we can use that workflow as an example, because it only caches the downloaded conda packages (as in the caching example in the docs for https://github.com/conda-incubator/setup-miniconda) whereas we are caching the conda environment itself such that the environment doesn't need to be reinstalled (the slow bit, in my experience). But yes, if we do away with the caching step and that would solve the problem. And that is certainly a reasonable choice.

Alternately, we could use a different shell to run those tests---the powershell is only really needed for the SLiM build step on Windows. Caching conda and using bash is working well over in stdpopsim, for all three OS platforms:
https://github.com/popsim-consortium/stdpopsim/blob/main/.github/workflows/tests.yml
