### ISSUE TITLE
[DEPLOYMENT] Debian & Ubuntu Packaging

### ISSUE THREAD

**Issue by bryce-carson** [MesserLab/SLiM#288]
### Motivation
The preferred installation method as of 2022-02-13 is the [installation script](https://github.com/MesserLab/SLiM-Extras/blob/6ea3dbc599ae9f1a225d9b151a7d6961cf0cfea4/installation/DebianUbuntuInstall.sh). DEB packages for Debian and Ubuntu users would be preferred for several reasons, as users can

- Remove the software
- Upgrade the software
- Install the software

all a little bit easier than the script, which also makes users wait for software compilation (and requires compilation software be installed).

### Targets
- [x] Investigate using [**package**cloud](https://packagecloud.io/) for hosting an APT repository for Debian (and potentially Ubuntu as well, forgoing Launchpad)
- [x] Consult the `pbuilder` and `pbuilder-dist` documentation and setup a playground of virtual machines to test building SLiM for all sorts of Debian and Ubuntu versions

### Status: 🚴🏼, slowly.
**Ubuntu**
- [x] 18.04 LTS (Bionic Beaver)
- [x] 20.04 LTS (Focal Fossa)
- [x] 21.10 (Impish Indri)

**Debian**
- [x] 10 ("Buster")
- [x] 11 ("Bullseye")
- [x] Testing ("Bookworm")
- [x] Sid (referred to as "Trixie" on **Package**cloud for some reason)

#### ⚠️ CAUTION ⚠️
The packages for Debian 11 "Bookworm" and Unstable "Sid" were not build with the distribution codename in the package name, but were renamed to include that to permit uploading to **Package**cloud. **Package**cloud disallows packages with the exact same filename to be uploaded, despite different checksums and distribution flags in the `.changes`, etc.

The packages *should* be rebuilt with the distribution codename included in the package name, but difficulties with RAM consumption, necessitating text-mode operation, or using a chroot into the qcow2 image are preventing ease of rebuild.

## Testing
🥇All of the binary packages have been uploaded to either Launchpad or Packagecloud now. The only remaining task is to have all of these sufficiently tested.

Right now that stands at:
**Ubuntu**
- [ ]  18.04 LTS (Bionic Beaver)
  _Maintainer test:
  :warning: Two packages had to be manually installed before `slimsim`: gcc-10-base, and libgcc-s1. These were not available for installation with APT on 18.04 LTS Server after installing X and GNUstep. Hopefully this is not the case for regular desktop Ubuntu.
  Installed from PPA in VM, tested in GNUstep. Works fine; all desktop integration is as expected._
- [x]  20.04 LTS (Focal Fossa)
- [ ]  21.10 (Impish Indri)

**Debian**
- [ ] 10 ("Buster")
- [ ] 11 ("Bullseye")
- [ ] 12 (Testing ("Bookworm"))
- [x] 13 ("Trixie" ("Sid"))

**Comment by bhaller** [comment]
One thing to keep an eye on with all of these is what version of Qt is installed by default, and whether that version of Qt is good for SLiMgui.  On Linux we enforce Qt 5.9.5 as a hard limit, since it is what Ubuntu 18.04 LTS has preinstalled; SLiMgui ought to build against any 5.x from 5.9.5 onward, and hopefully works without bugs, but comprehensive testing against different versions is not possible for us, so to some extent we just cross our fingers and wait for users to file issues.  Back-porting beyond Qt 5.9.5 is not going to happen, so if an old distro like "Stretch" defaults to an older Qt than that, that might mean we can't support that platform.  Overriding the default Qt version for a given distro is probably not a good idea; the Qt folks only support certain versions on certain distros, it is all very structured/planned, and if we go outside of those lines Bad Things might happen (and might be runtime problems rather than build failures, so it would be hard to even know that something was wrong).

At some point I imagine some Linux distro might start making Qt 6.x the default; SLiMgui doesn't build against 6.x, for the time being, so if it is possible to specify that we want Qt5 rather than Qt6, that may become necessary going forward.

Anyhow, that's my only thought about this, except that it looks great!  Thanks for spearheading this!

**Comment by bryce-carson** [comment]
> On Linux we enforce Qt 5.9.5 as a hard limit, since it is what Ubuntu 18.04 LTS has preinstalled

Thanks for the comment, @bhaller , I was thinking back to the last time you mentioned this a couple days ago when I was working on the current Focal Fossa package. I couldn't figure out where that was mentioned before.

I can definitely require `BuildDepends: qtbase5-dev (>= 5.9.5)` and the other necessaries for what we and Qt can sensibly support.

Backporting is... a big no from me too.

**Comment by bryce-carson** [comment]
### Process for building for a distribution

1. `pbuilder-dist DISTRIBUTION_CODENAME create`
2. `pbuilder-dist DISTRIBUTION_CODENAME build SOURCE.dsc`

**Example**:
```bash
## NOT RUN ##
pbuilder-dist bionic create
pbuilder-dist bionic build --buildresult ~/debuild/bionic/
debsign -K [PGP Key ID] --debs-dir ~/debuild/bionic/{,slimsim-3.7.1-1ubuntu1ppa1.changes,slimsim-3.7.1-1ubuntu1ppa1.dsc}
dput ppa:bryce-a-carson/slim-sim ~/debuild/bionic/slimsim-3.7.1-1ubuntu1ppa1.changes
## NOT RUN ##
```
##### Notes on the process

- Another option with Launchpad is package copying, but this doesn't seem to work easily or I have misunderstood how to use it

**Comment by bryce-carson** [comment]
# Local packaging
1. Create the ./${PKG}-${VERSION}/debian directory and all of the necessary files
   
   Each release should fix an issue you discovered during packaging and increment the package version
   ```sh
   cd ${PKG}-${VERSION}
   debuild -S
   ```

Once all issues are fixed and the package builds successfully and basic QA has been done you can continue.

# Packaging for different Ubuntu (or Debian) releases
2. Change the distribution field (e.g. from focal to bionic)
   ```sh
   dch
   debuild -S
   mkdir ~/debuild/bionic
   ```

3. You need several files: the Debian _source control_ (`dsc`) file, the original (upstream) source archive, and the Debian source archive (`*.debian.tar.xz`).
   ```sh
   cp -t ~/debuild/bionic ~/debuild/local/${PKG}-${VERSION}*{.dsc,.orig.tar.gz,1ubuntu1ppa1.debian.tar.xz}
   cd ~/debuild/bionic
   ```

4. If not already created for the target distribution, create the base image for a clean build environment.
   ```sh
   pbuilder-dist bionic create
   ```

5. Build the package in the clean environment of the desired Ubuntu (or Debian) release and then sign the package sources.
   ```sh
   pbuilder-dist bionic build --buildresult ~/debuild/bionic/ ${PKG}-${VERSION}.dsc
   debsign -K [PGP Key ID] --debs-dir ~/debuild/bionic/{,slimsim_3.7.1-1ubuntu1ppa1.changes,slimsim-3.7.1-1ubuntu1ppa1.dsc}
   ```

# Launchpad (Ubuntu only)
```sh
dput ppa:bryce-a-carson/slim-sim ~/debuild/bionic/slimsim_3.7.1-1ubuntu1ppa1_source.changes
```
## Launchpad Issues
> Rejected:
> Mismatch in binaryfulness. (arch) False != (files) True

**Comment by bryce-carson** [comment]
Builds always fail for i386 on Launchpad, which was observed before, but ignored; sometimes a submitted package would only be attempted to build for AMD64, probably because it was a locally built package and the architecture of the package is taken from the machine it is built for when using only `debuild`, but this is apparently not the case for the Debian source control file created when using `pbuilder-dist`.

> "SLiM must be built for 64-bit, not 32-bit."

```sh
[ 37%] Building CXX object CMakeFiles/eidos.dir/eidos/eidos_globals.cpp.o
/usr/bin/c++   -I/<<PKGBUILDDIR>>/gsl -I/<<PKGBUILDDIR>>/gsl/specfunc -I/<<PKGBUILDDIR>>/gsl/blas -I/<<PKGBUILDDIR>>/gsl/rng -I/<<PKGBUILDDIR>>/gsl/cdf -I/<<PKGBUILDDIR>>/gsl/vector -I/<<PKGBUILDDIR>>/gsl/err -I/<<PKGBUILDDIR>>/gsl/sys -I/<<PKGBUILDDIR>>/gsl/randist -I/<<PKGBUILDDIR>>/gsl/matrix -I/<<PKGBUILDDIR>>/gsl/cblas -I/<<PKGBUILDDIR>>/gsl/complex -I/<<PKGBUILDDIR>>/gsl/block -I/<<PKGBUILDDIR>>/gsl/linalg -I/<<PKGBUILDDIR>>/eidos -I/<<PKGBUILDDIR>>/treerec/tskit/kastore -I/<<PKGBUILDDIR>>/treerec  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11 -Wno-attributes -Wunused-label -Wunused-variable -Wunused-value -Wno-pragmas -Wempty-body -Wshadow -Wparentheses -Wswitch -Wsign-compare -Wno-sign-conversion -Wuninitialized   -o CMakeFiles/eidos.dir/eidos/eidos_globals.cpp.o -c /<<PKGBUILDDIR>>/eidos/eidos_globals.cpp
/<<PKGBUILDDIR>>/eidos/eidos_globals.cpp:87:1: error: static assertion failed: SLiM must be built for 64-bit, not 32-bit.
```

# Specify architecture in `debian/control`

- [What to specify](https://www.debian.org/doc/debian-policy/ch-customized-programs.html#architecture-specification-strings)
- [How to specify](https://www.debian.org/doc/debian-policy/ch-customized-programs.html#architecture-specification-strings)

```sh
dpkg-architecture -L
```

**Comment by bryce-carson** [comment]
@bhaller I now have packages 📦 uploaded to Launchpad for the three Ubuntu releases that we currently support, and I've published a package for Debian 10 ("Buster") to [**package**cloud](https://packagecloud.io/bryce-a-carson/SLiM). I need testers for the different releases of Ubuntu (Bionic and Impish; Impish worked locally for me, but I still need beta testing; Focal Fossa was already tested in [SLiM-Extras#21 ](https://github.com/MesserLab/SLiM-Extras/issues/21)) and for Buster.

I'll make a post on the Google Group about it; if any users would like to do some testing for me that would be great.

I'll get the packages built for the other versions of Debian soon, but I'm not in any rush. Just a geek addiction to Linux. There's always course work to focus on! :P

**Comment by bhaller** [comment]
Hi @bryce-carson!  This sounds great.  Feel free to post to slim-discuss of course, hopefully you'll get some nibbles.  Glad to hear your coursework is also receiving attention.  :->

How hard would it be to write an installer script that (a) checks the user's distro/version, (b) installs a package if one is available, or (c) runs the current installer scripts to build/install if no package is available?  Is that a good idea?  Or no?

**Comment by bryce-carson** [comment]
> How hard would it be to write an installer script that (a) checks the user's distro/version, (b) installs a package if one is available, or (c) runs the current installer scripts to build/install if no package is available?  Is that a good idea?  Or no?

That'd be quite hard, I think.

The best route forward would be putting the course work I did in Technical Writing to use to rewrite the installation section for Linux so that it is consistent in verbiage and flow for each distribution, and doesn't take too much prose to get the user the information they need:

- Binary packages are community-contributed,
- Packages are hosted by third parties unaffiliated with Cornell and the MesserLab, and
- Supported by the SLiM community only

A more extensive script just for a lot of dpkg and uname calls would be unmaintainable and I wouldn't want to try, either. :P

**Comment by bhaller** [comment]
OK, whatever you think is best; just an idea.  :->  Thanks!

**Comment by bryce-carson** [comment]
> **Debian**
> 
>     * [x]  10 ("Buster")
> 
>     * [ ]  11 ("Bullseye")
> 
>     * [ ]  Testing ("Bookworm")
> 
>     * [ ]  Sid (referred to as "Trixie" on **Package**cloud for some reason)
> 
> 
> #### ⚠️ CAUTION ⚠️
> 
> The packages for Debian 11 "Bookworm" and Unstable "Sid" were not build with the distribution codename in the package name, but were renamed to include that to permit uploading to **Package**cloud. **Package**cloud disallows packages with the exact same filename to be uploaded, despite different checksums and distribution flags in the `.changes`, etc.
> 
> The packages _should_ be rebuilt with the distribution codename included in the package name, but difficulties with RAM consumption, necessitating text-mode operation, or using a chroot into the qcow2 image are preventing ease of rebuild.

@petrelharp, I've uploaded a binary package for "Sid", but **Package**cloud refers to it as "Trixie". Additionally, see the caution that I've written in the above quote. I'm not sure if this will cause problems.

I have limited RAM on my workstation, only 8GB which is reduced to ~6GB because I use an APU. This makes building difficult and slow-going, with a lot of troubleshooting just to get basic operation unrelated to packaging.

**Comment by petrelharp** [comment]
I tried it out! Thanks to your note I quickly figured out I had to run
```
os=debian dist=Trixie bash script.deb.sh
```
... just running the script failed as it didn't know what "sid" was, and which I specified Trixie I also had to specify the os.

But, after that, the instructions worked! Nice job!!

Note: there should also be instructions for how to remove the additions. I think this is just
```
sudo rm /etc/apt/sources.list.d/bryce-a-carson_SLiM.list /etc/apt/trusted.gpg.d/bryce-a-carson_SLiM.gpg
```

I see that Trixie is the next Debian release (i.e., the next 'testing', so what's currently in sid), I guess that's why? I don't understand what your cautionary note means, by the ways.

**Comment by bryce-carson** [comment]
> I tried it out! Thanks to your note I quickly figured out I had to run
> 
> ```
> os=debian dist=Trixie bash script.deb.sh
> ```
> 
> ... just running the script failed as it didn't know what "sid" was, and which I specified Trixie I also had to specify the os.
> 
> But, after that, the instructions worked! Nice job!!

I see. I read through the source of [the script **package**cloud gives](https://packagecloud.io/install/repositories/bryce-a-carson/SLiM/script.deb.sh), and I see why you needed to do that. That's a little strange, and less user-friendly than I was hoping for. At least it's a freely hosted APT repo, right?

If specifying `$os` and `$dist` is necessary for the script to add the repository to the lists, I'll include that in a future README.md for that repository, and in the eventual update to the SLiM manual once all of this is well-tested.

---

> 
> Note: there should also be instructions for how to remove the additions. I think this is just
> 
> ```
> sudo rm /etc/apt/sources.list.d/bryce-a-carson_SLiM.list /usr/share/keyrings/bryce-a-carson_SLiM-archive-keyring.gpg
> ```

Okay, I'll include that in the instructions as well, since those files wouldn't be removed alongwith `sudo apt remove slimsim`.

---

> I see that Trixie is the next Debian release (i.e., the next 'testing', so what's currently in sid), I guess that's why?

Yeah, I wasn't aware the Debian had picked out a name for the *next* testing already. The whole point of Debian *unstable* being code-named "Sid" is because, well, Sid Phillips is unstable (according to Debian, not Pixar!).

> Woody: "That is Sid"
> Buzz: "You mean that happy child?"
> Mr. Potato Head: "That ain't no happy child."
> Rex: "He tortures toys, just for fun!"
> ―The toys observe Sid from [Andy's room](https://pixar.fandom.com/wiki/Andy%27s_House)[[src]](https://pixar.fandom.com/wiki/Toy_Story)

<img src="https://static.wikia.nocookie.net/pixar/images/9/9d/Sid2.jpg/revision/latest/scale-to-width-down/210?cb=20201208155941" srcset="https://static.wikia.nocookie.net/pixar/images/9/9d/Sid2.jpg/revision/latest/scale-to-width-down/210?cb=20201208155941 1x, https://static.wikia.nocookie.net/pixar/images/9/9d/Sid2.jpg/revision/latest/scale-to-width-down/420?cb=20201208155941 2x" class="pi-image-thumbnail" alt="" width="210" height="263" data-image-key="Sid2.jpg" data-image-name="Sid2.jpg" data-gtm-vis-recent-on-screen-31059910_570="1229" data-gtm-vis-first-on-screen-31059910_570="1229" data-gtm-vis-total-visible-time-31059910_570="100" data-gtm-vis-has-fired-31059910_570="1">

---

> I don't understand what your cautionary note means, by the ways.

When I create the binary packages for Debian releases, they're simply named `slimsim_3.7.1-1_amd64.deb`. I only uploaded one package (for "Buster") to **package**cloud.io when I first started the Debian-half of deb packaging this month.

To upload packages for other versions of Debian, I had to rename them. **package**cloud complained "a package of that name" had already been uploaded.

The Debian Policy Manual, [in this section](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-source), describes the permitted format of package names. I checked another source that indicated that the release component of the package name (in bold for clarity here: "slimsim_3.7.1**-1**_amd64.deb") may include alphanumerics.

The Ubuntu directives include "packagename_0.1.1-1**ubuntu1ppa1**" and possibly others.

I believe that it is fine to append the Debian release codename to the package release component of the package name, and this did allow me to upload the packages for the other releases of Debian to **package**cloud, but the binary packages were not rebuilt, only renamed.

Debian packaging is _really_ opaque and complex, so there might've been unforseen issues, but there shouldn't be since all the other components of the binary package itself are "up to spec", as far as I'm aware.

If it didn't cause any problems during installation, and the software works then it's all gravy and you can disregard the caution. I put it there because all of this is still in testing and if some reader on [slim-discuss](https://groups.google.com/g/slim-discuss) tried the package for Sid (""" Trixie """) or Bookworm I wanted them and my future self to know that file renaming could have been a culprit.

Regardless, it worked, right? Great!

**Comment by bryce-carson** [comment]
🥇All of the binary packages have been uploaded to either Launchpad or Packagecloud now. The only remaining task is to have all of these sufficiently tested.

Right now that stands at:
**Ubuntu**
- [ ]  18.04 LTS (Bionic Beaver)
- [x]  20.04 LTS (Focal Fossa)
- [ ]  21.10 (Impish Indri)

**Debian**
- [ ] 10 ("Buster")
- [ ] 11 ("Bullseye")
- [ ] 12 (Testing ("Bookworm"))
- [x] 13 ("Trixie" ("Sid"))

**Comment by petrelharp** [comment]
> Debian packaging is really opaque and complex

Seriously. I attempted to start being a package maintainer at one point, but it was too much. Thanks a bunch for getting this working.

And, hah, I didn't know that about Sid. Here's the source [for Trixie](https://wiki.debian.org/DebianTrixie).

**Comment by bryce-carson** [comment]
> > Debian packaging is really opaque and complex
> 
> Seriously. I attempted to start being a package maintainer at one point, but it was too much. Thanks a bunch for getting this working.

It really can be! Just learning the bare minimum to get by was difficult, but I've gotten through it and now it's not _so_ bad. There's still a lot of shortcomings that I wish were addressed.
