### ISSUE TITLE
fitness coloring in SLiMgui wrong when a survival() callback drives migration

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#293]
The new recipe 16.19 II that I just added, demonstrating the use of `survival()` callbacks to implement a migration scheme, reveals a bug in SLiMgui that results in incorrect fitness colors for individuals and subpops in SLiMgui.  This happens because the fitness value for an individual is calculated based upon its residence in subpop A, using A's `fitnessScaling` value, and then the `survival` callback moves the individual to subpop B.  SLiMgui backs out subpopulation-level `fitnessScaling` to try to show individual fitness without the effects of local density-dependence; however, if an individual moved from A to B in the mortality phase, SLiMgui backs out that individual's fitness value using B's `fitnessScaling` even though the individual's fitness was based upon A's `fitnessScaling`, resulting in the wrong backed-out value and thus the wrong color.  This is purely a UI/visualization error; it doesn't affect the running model at all.

It's not clear what the right fix is.  I could add SLiMgui-only code that would remember the fitness values of individuals before the subpop `fitnessScaling` value gets multiplied in; that would be perfectly reasonable.  However, the whole way that SLiMgui backs out the fitness values is a little weird, and is based upon the assumption that that is what the user even actually wants.  It is possible that if SLiM adds in the concept of multiple fitness components, that would fix this issue in a cleaner way; SLiMgui would then be showing the main/default fitness component in its color scheme, while density-dependent effects could be modeled with a separate fitness component that SLiMgui would ignore (depending upon configuration).  So while the first fix is the obvious path, and I'll probably do it just to get this bug fixed for users now, the big picture maybe would benefit from more thought, thus this issue.

**Comment by petrelharp** [comment]
> SLiMgui backs out subpopulation-level fitnessScaling to try to show individual fitness without the effects of local density-dependence

By "density dependence" you mean a global scaling depending on total subpopulation size, right? Not local density dependence, which would be individual-specific, and we definitely want to measure?

**Comment by bhaller** [comment]
> > SLiMgui backs out subpopulation-level fitnessScaling to try to show individual fitness without the effects of local density-dependence
> 
> By "density dependence" you mean a global scaling depending on total subpopulation size, right? Not local density dependence, which would be individual-specific, and we definitely want to measure?

Yes.  Section 8.4 of the manual has a detailed discussion of what SLiMgui tries to do, but in essence, it divides by the `subpop.fitnessScaling` value of the subpop that an individual is in, to get the individual's fitness without any subpop-level fitness rescaling (which, in practice, is usually due to density-dependence), since that seems more useful for visualization purposes.  Local density dependence does not involve the subpopulation's `fitnessScaling` (it typically uses the individual's `fitnessScaling` instead), so SLiMgui's rescaling does not affect that.  And the bug described in this issue occurs because SLiMgui divides by the wrong `fitnessScaling` value when an individual has been moved to a different subpopulation by a `survival()` callback.

**Comment by petrelharp** [comment]
Gotcha. I'm tempted to suggest that you not try to remove the population-level fitnessScaling, since knowing absolute fitness is a useful thing (at least in a nonWF model, where for instance seeing that one population is all more blue than other shows that it has shorter generation times).

**Comment by bhaller** [comment]
> Gotcha. I'm tempted to suggest that you not try to remove the population-level fitnessScaling, since knowing absolute fitness is a useful thing (at least in a nonWF model, where for instance seeing that one population is all more blue than other shows that it has shorter generation times).

Yes, seeing the true fitness can sometimes be helpful.  However, since populations in nonWF models generally fluctuate stochastically up and down to be above/below their carrying capacity, displaying the true fitness in SLiMgui often just results in the color of the individuals/subpopulations flicking up and down between green and red, obscuring the between-individual fitness differences that are actually driving the evolution of the population.  I don't think I am likely to get rid of SLiMgui's dividing out of the subpop-level fitnessScaling, for that reason; I think it is usually more helpful than harmful.  However, I could certainly make it something that can be switched on and off – especially now that, in SLiM 3.7, SLiMgui has those nice new action buttons that make configuration of the views more transparent.  If you want that on/off switch, feel free to log an issue!  :->

**Comment by bhaller** [comment]
This has been fixed in `multispecies`.
