### ISSUE TITLE
Required version of Windows should be specified

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#295]
I realized that we don't say what version of Windows is needed for SLiM, and I don't know.  I lost track of Windows versions a long time ago; NT, or 95, or something?  Anyway, the manual's installation instructions should say what is needed, and the workshop HTML pages should mention this as well.  @rdinnager can you tell we what I ought to say?  Thanks!

**Comment by rdinnager** [comment]
I've only been able to test it on windows 10 / 11, but in theory it should
work on any windows version that msys2 works on which is 64bit Windows 7 or
later.

**Comment by bhaller** [comment]
Perfect.  I've just updated the manual and the workshop web pages accordingly.  Closing.
