### ISSUE TITLE
build failure on multispecies branch for macOS GUI

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#301]
Looks like the install of Qt has started to fail in GitHub Actions CI for macOS.  I have no idea why.  I have just observed this on the `multispecies` branch, which is where I'm spending my time at present.  Here's a link:

[https://github.com/MesserLab/SLiM/runs/5714325093?check_suite_focus=true](https://github.com/MesserLab/SLiM/runs/5714325093?check_suite_focus=true)

My guess is that it probably happens for `master` too, now; I can't see why there would be a difference.  But I don't want to do a commit on master just to trigger a rebuild, that seems gratuitous.  Is there a button somewhere to tell GitHub Actions to just re-run CI on a given branch?

Anyhow, the point is that the CI build now fails because Qt doesn't install.  Ignore the build failures for targets other than the "macOS GUI" targets; their failure is due to [https://github.com/tskit-dev/pyslim/issues/246](https://github.com/tskit-dev/pyslim/issues/246) which is unrelated.

@grahamgower I don't suppose you know why this is happening?  Thanks for any insight/fix; I have absolutely no idea.  :->

**Comment by petrelharp** [comment]
Bummer. You can trigger builds up in the "actions" tab somewhere.

**Comment by grahamgower** [comment]
Looks like an upstream issue, which has been reported: https://github.com/jurplel/install-qt-action/issues/142

The workaround is to not install the python qt bits, which should be fine (I don't think SLiM uses this).
```diff
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
index 7c43ef78..d3349a9a 100644
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -173,6 +173,7 @@ jobs:
         uses: jurplel/install-qt-action@v2
         with:
           version: ${{ matrix.qt }}
+          setup-python: false

       - name: Build (cmake)
         run: |
```

**Comment by bhaller** [comment]
> Looks like an upstream issue, which has been reported: [jurplel/install-qt-action#142](https://github.com/jurplel/install-qt-action/issues/142)
> 
> The workaround is to not install the python qt bits, which should be fine (I don't think SLiM uses this).

Awesome!  Trying this out now.  I also don't think we need the python Qt bits, so this ought to do it.  Thanks @grahamgower!
