### ISSUE TITLE
Interpreter not resilient against target_genome->mutruns_ being NULL.

### ISSUE THREAD

**Issue by vjorlikowski** [MesserLab/SLiM#302]
Hi there,

While debugging an issue with a researcher at our institution, we encountered an input file that allowed for a segmentation fault to occur here:

https://github.com/MesserLab/SLiM/blob/d37f3d88a191b8fb725699902065cfa6b3fe4042/core/genome.cpp#L3820

In the researcher's input file, target_genome->mutruns_ was able to be NULL.

As a workaround, we added:
if (target_genome-> mutruns_ == NULL) break;

Which allowed us to progress to a more robust failure description, later in the file:

ERROR (Genome::NullGenomeAccessError): (internal error) a null genome was accessed.

**Comment by bhaller** [comment]
Errors that start with "(internal error)" are supposed to never happen to end users, so hitting that second error is still indicative of a problem.  Can you share a reproducible case that triggers this problem?

**Comment by vjorlikowski** [comment]
Let me talk to the researcher, and see if they're willing to share their script (for use as a reproducer).
We're aware there's still an issue to be resolved with the researcher's code - but figured we ought to report the need for some kind of additional sanity checking in removeMutations().

**Comment by bhaller** [comment]
Thanks.  Yes, for sure this is a bug worth reporting; I just want a reproducible case so that I can understand the bug and find the correct fix for it.  :->

**Comment by bhaller** [comment]
> Let me talk to the researcher, and see if they're willing to share their script (for use as a reproducer).

Hi @vjorlikowski.  Any progress on this?  A reproducible case is really helpful for fixing a bug like this.  Thanks.

**Comment by vjorlikowski** [comment]
Apologies for the delay!
A minimal reproducer from our researcher is attached.
I appended a ".txt" extension, in order to get GitHub to accept it.

Thanks!

[seg_fault.slim.txt](https://github.com/MesserLab/SLiM/files/8429415/seg_fault.slim.txt)

**Comment by bhaller** [comment]
Thanks; I'll look into it!
