### ISSUE TITLE
Shift from tsk_vargen to tsk_variant

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#304]
The tskit APIs for finding variants at sites is shifting; see https://github.com/tskit-dev/tskit/issues/2175.  We should respond to that shift the next time we update the tskit code in SLiM.  We might not get any compiler warning or error, since they plan to keep the old APIs present but undocumented for now, so I'm opening this issue as a reminder.  @petrelharp tagging you so this is on your radar too.  :->

**Comment by bhaller** [comment]
Sounds like the shift away from vargen_t will happen in the next C API release, by mid-May-ish.  But it won't actually be removed for a good while; just deprecated.  So we could switch over to the new C API, when it is released, for SLiM 4; or we could sweep that under the rug and deal with it in 4.0.1 or 4.1 or whatever.

**Comment by bhaller** [comment]
@petrelharp it looks like there is still use of `tsk_vargen` in `Species::CrosscheckTreeSeqIntegrity()`.  This is lower priority than getting pyslim squared away, of course, but it would be nice to fix it eventually; do you might doing that, since you're on top of how to do this migration?

**Comment by petrelharp** [comment]
#324!

**Comment by bhaller** [comment]
> #324!

Awesome, thanks!  :->
