### ISSUE TITLE
Subpop metadata "carryover" probably broken by recent commits

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#318]
I think “carrying over” non-SLiM metadata will no longer work because of the new code in `Species::__PrepareSubpopulationsFromTables()`.  As it scans through the population table on read, it raises an error on any metadata present that is not JSON, not `'object'`, doesn’t have a `slim_id`, etc.; basically it requires that incoming metadata must either be `'null'` or compliant SLiM metadata.  I guess we don’t want to be raising there, to allow carryover to work…?

I have to say, this “carryover” business still seems super weird to me.  Remind me why we want to be allowing that in the first place?  We write out a schema for the population table that says metadata must either be 'null' or a SLiM-compliant JSON object; but then we allow metadata that violates that schema to “carry over”?  That seems wrong – a deliberate violation of the schema.  Is that really what we want to be doing, or could the decision to allow that maybe have been incorrect?

So, I think we have a bug here one way or the other.  If we want carryover to work then (a) `Species::__PrepareSubpopulationsFromTables()` needs to stop raising on non-compliant metadata, and just allow it through (while "preparing" subpopulations if and only if the metadata present is SLiM-compliant).  If we decide that carryover was a bad idea, then either it should (b) raise on non-compliant metadata, as it does now, or (c) replace non-compliant metadata with `'null'` to force it into compliance.

**Comment by bhaller** [comment]
@petrelharp This needs your input.

**Comment by bhaller** [comment]
Hmm, I guess my term "super weird" was not as specific as it could have been.  :->  I do see the *utility* of carryover, in certain situations such as you describe.  What seems "super weird" to me is to deliberately write out data that we know violates the schema, producing a file in which the metadata in the population table does not all conform to the same schema.  Indeed, there could potentially be even more than two schemas in use in the table, right?  This partly just offends my sensibilities – why even bother having schemas, etc., if you're not going to follow them?  But it is also, in theory, even a bit dangerous, because the exact same pattern of bits might (through a wild coincidence, I'll admit) happen to be interpretable as _both_ valid SLiM metadata and valid metadata under whatever alternative schema is in use in the table – a binary, non-JSON schema, even.  That is very unlikely to happen, but "unlikely" is not the same thing as "impossible"; it's a vulnerability.  But even if you want to discount that risk, the principle of "thou shalt follow the schema" still does seem like a problem for carryover.

In any case, it sounds like you're voting for (a), fixing the code to allow carryover again, which I'm pretty sure I inadvertently broke.  :->  I'm willing to defer to your judgement on this, since you know the tskit stuff and the use cases for this far better than I do.  I just want to register a tentative protest vote against it.  :->  Perhaps if this is really a thing that we want to support, there ought to be a way to support it explicitly, without breaking any rules?  Maybe this is a discussion it would be useful to raise with the tskit folks.  What do _they_ think of "carryover", and does it bother them that it violates the schema?

But that's all somewhat academic.  I'll fix this issue with approach (a).  :->

**Comment by bhaller** [comment]
If you could provide me with a simple python and SLiM script that tests that carryover is working correctly, that would be very helpful for me, @petrelharp.  :->  I guess you intend to write one for that issue you just opened anyway?

**Comment by petrelharp** [comment]
Oh, darn it, you're totally right - we can't do this, as it violates the metadata schema. Or, if we want to do it we need to remove the `"slim_id"` key from the `required` list in the schema, so that "any json is ok" - I'm tempted to go that way, really. Perhaps I'll ask others on slack what they think?

**Comment by bhaller** [comment]
Removing the key is a bit squiffy, to me, because the key *is* required for the metadata to be well-formed SLiM metadata, and that's what they schema is describing – what is required for metadata to be well-formed SLiM metadata.  If we have to get rid of all our required keys for interoperability, everybody else will too – msprime, etc., also won't be able to have any required keys, because they will want to be able to interoperate with (and probably carry over) SLiM metadata as well as their own.  I think there's really a deep philosophical problem here that needs to be resolved.  I'll post this comment on Slack as well, since the discussion is moving there.

**Comment by bhaller** [comment]
So, if I understand what has been said on Slack correctly, we do have to remove the required key; otherwise validation will fail.  I'm not sure this will be a good design in the long run – not having any required keys seems kind of broken to me.  But I guess that's where we're at, until such time as tskit provides schema merging capabilities or whatever they decide to do.  So to fix this issue I guess I will (a) remove the key requirement from the schema (while still requiring it in SLiM's code to be present for metadata to be considered "SLiM metadata"), and (b) modify `Species::__PrepareSubpopulationsFromTables()`  to allow non-SLiM-compliant metadata (but ignore it – don't prepare a subpopulation for that case).  Does this sound correct @petrelharp?  I will proceed on the assumption that it is, but let me know if not.

**Comment by bhaller** [comment]
If I understand where we have ended up, there is no case where we will replace "carryover" metadata with `null` on write.  Either (1) the carryover subpop is not extant in SLiM at the end of simulation, in which case we emit the carryover (even if it _did_ get forward-simulated by us, but has since been removed; we have no knowledge of it any more, and no metadata to replace the old metadata with), or (2) the carryover subpop is extant in SLiM at the end of simulation, in which case we emit the SLiM metadata for it, and the carryover data gets dropped.

**Comment by bhaller** [comment]
I have just committed a partial fix for this issue, but there are loose ends (and also, I'm pretty sure, bugs).  I will wait to close this issue until #319 is done and we can validate that carryover is working in all cases.

**Comment by petrelharp** [comment]
I agree, we remove the required key and modify `PrepareSubpopulationsFromTables`. I think it does totally make sense; we're just saying "SLiM will only look at and deal with metadata having a `slim_id` key (and oh by the way here's the other stuff it'll look for)". There's not a terribly natural way of saying exactly that in the metadata schema, but we don't want to get too caught up in that - we should use the schema when they're helpful but not let them get in our way.

> If I understand where we have ended up, there is no case where we will replace "carryover" metadata with null on write.

I think we *do* need to replace metadata with `null`, actually - if there was a SLiM-simulated population present in the tables when we read them in, but then it got removed, we need to write out `null` to that slot. On write out, I think we need to:
- loop over rows in the population table
- if we have a population that goes there we stick the population's metadata there
- if we *don't* have a population that goes there *and* it's got a `slim_id` key then write `null` there
- otherwise, carry over whatever is there already

**Comment by bhaller** [comment]
> * if we _don't_ have a population that goes there _and_ it's got a `slim_id` key then write `null` there

Ah, I see.  Hmm.  OK, I will do that momentarily.

**Comment by bhaller** [comment]
> > * if we _don't_ have a population that goes there _and_ it's got a `slim_id` key then write `null` there
> 
> Ah, I see. Hmm. OK, I will do that momentarily.

Ah, I think that already got fixed in #317.  Quite the flurry of issues we've got going here.

**Comment by petrelharp** [comment]
The carryover seems to be working! I'll have other issues to be opening though...
