### ISSUE TITLE
informative error message when command-line string variable declarations don't parse

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#32]
Right now, running
```
> slim -d x=5 recipe.slim 
```
as does
```
> slim -d "x=5" recipe.slim
```
but the following fails with an uniformative error:
```
> slim -d x='mu' recipe.slim
// Initial random seed:
1847778891683

terminate called after throwing an instance of 'std::runtime_error'
  what():  A runtime error occurred in Eidos
Aborted
```
and it can be hard to hit upon the right combination of quotes that make it work (although this does appear in Section 17.2 in the manual):
```
> slim -d "x='mu'" recipe.slim
```

If this threw an error that said "Command-line definitions did not parse correctly." that would help new users.

**Comment by bhaller** [comment]
Just fixed.  For foo="bar" it now prints:

ERROR (Eidos_DefineConstantsFromCommandLine): command-line expression could not be evaluated: foo=bar
original error: ERROR (EidosSymbolTable::_GetValue): undefined identifier bar.

The quotes around "bar" are not-so-helpfully removed by the shell, so what SLiM sees is foo=bar.

**Comment by petrelharp** [comment]
Ah, that's why! Thanks - this had hit at least one other person so I thought it worth fixing.

**Comment by Tatianabellagio** [comment]
this helped me! Thanks!
