### ISSUE TITLE
feature request: allow setting hotkeys to move cursor to different regions of slimgui

### ISSUE THREAD

**Issue by bobweek** [MesserLab/SLiM#322]
in environments like vscode and rstudio, pressing ctrl+1 will place the cursor in the scripting window. having the same feature in slimgui would save a lot of time spent reaching over to the mouse to click into the scripting window. almost any work related task on my computer can be done without touching the mouse. so reaching for mouse each time i open a slim script creates a significant bottleneck for me.

**Comment by bhaller** [comment]
OK.  Do you expect this to change which window has focus?  I.e., suppose the window that currently has focus is a graph window, or the Eidos console, or something like that; do you expect this hotkey to switch focus to the main window?  Or does it just shift the focus _within_ the main window?

**Comment by bobweek** [comment]
sorry, just within the main window. i should have said pane instead of window.

**Comment by bhaller** [comment]
I've just committed a fix to `multispecies`.  See what you think.  I added command-2 (control-2 for you I think) to switch focus to the output/console, too; more useful in the Eidos console than in the main window.  I am a heavy mouse user, so I don't notice problems with keyboard navigation; feel free to log issues.  :->

**Comment by bobweek** [comment]
perfect, thank you!
