### ISSUE TITLE
Save parent pedigreeID ID in tree-sequence of individual meta data

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#332]
### Discussed in https://github.com/MesserLab/SLiM/discussions/331

<div type='discussions-op-text'>

<sup>Originally posted by **lerch-a** June 13, 2022</sup>
It would be great if the parent pedigreeID could be saved in the tree-sequence, when the keepPedigrees=T in initializeSLiMOptions.
I think the easiest way would be to save the parent pedigreeID in the meta data of the individual like the pedigreeID of the individual.

I would appreciate if this could be integrated in SLiM v4. 

See https://groups.google.com/g/slim-discuss/c/i_BThb7mQDg/m/nXBzQBZCAwAJ for more discussions
Thanks

I'm using SLiM for a mosquito model of a remote island. Currently, I write every mating event into a text file. As mosquito have a lot of offspring this file becomes very large and SLiM simulation is slowed down because of it. However, I'm only interested in the adult mosquitos which I save with sim.treeSeqRememberIndividuals(inds) when they become adults.</div>

**Comment by petrelharp** [comment]
Let's see - what exactly do you need here, @lerch-a? Like, *which* parents do you need to know about? And, did you know that SLiM now records parentage information for any output individual? So, if `a` and `b` are both individual IDs in the output tree sequence, and `a` is one of `b`'s parent, then `a` will be one of the elements of
```
ts.individual(b).parents
```
(It might be the only element, if the other parent isn't in the tree sequence.) Ah, hm - and actually I'm noticing that we already do just what you're asking for? In individual metadata there are keys `pedigree_p1` and `pedigree_p2`, for instance:
```
$ tskit individuals my.trees
id	flags	location	parents	metadata
0	196608	0.0,0.0,0.0	28,31	{'pedigree_id': 54, 'pedigree_p1': 34, 'pedigree_p2': 40, 'age': 3, 'subpopulation': 1, 'sex': -1, 'flags': 0}
```

I'm not sure when we put this in, so maybe it's not in the version of SLiM you're using? If you use the 4.0 beta then you'll have it, for sure.

**Comment by lerch-a** [comment]
Oh, I'm sorry. I'm still using 3.6.
So everything I need is actually already in place. Great and sorry for not being up to date. 
I'll download SLiM v4 and use all the new feature :)

**Comment by bhaller** [comment]
> Oh, I'm sorry. I'm still using 3.6.
> So everything I need is actually already in place. Great and sorry for not being up to date.
> I'll download SLiM v4 and use all the new feature :)

SLiM 4 is still in beta, so unless you want to be an early adopter, you may want to just update to 3.7.1.  All the installers will give you 3.7.1 now.

**Comment by petrelharp** [comment]
I've just checked, and these things are indeed in 3.7.1, so you should be good there!
