### ISSUE TITLE
Error with paste0 function:  too many arguments supplied

### ISSUE THREAD

**Issue by asadrh8** [MesserLab/SLiM#335]
Hi,

I've been running into the issue below when attempting to name treeseq files using the paste function.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/73436736/177435707-5cebe2bf-1112-4042-b6be-9f81839e2e8f.png">

In this case, I've defined rep and s in the terminal as I'm using a remote server. The simulation runs smoothly when I run it locally in SLiM (defining s and rep within the SLiM file, in that case). Is there something I'm doing incorrectly?

Thanks!
Asad

**Comment by bhaller** [comment]
Hi!  My guess is that the version of SLiM you're running on the remote server is old.  IIRC, `paste0()` was upgraded from something like `paste0(*x)`, taking a single vector of values, to `paste0(...)`, taking multiple vectors, maybe in SLiM 3.7.  If you install 3.7.1 on your remote server I think you'll be fine.  Comment again if that is not the problem, and I'll reopen this issue.  Happy modeling!

**Comment by bhaller** [comment]
This is quite odd.  Your script runs without errors for me in both SLiM 3.7.1 and the SLiM 4 beta.  The change to allow multiple arguments to paste() and paste0() was done in SLiM 3.5.  Are you _really_ sure you're running SLiM 3.7.1?

**Comment by asadrh8** [comment]
So it runs SLiM version 3.3.2! Guess that's the issue. I'm not sure where that's coming from but that's my problem to fix haha.

Thanks for the help.

**Comment by bhaller** [comment]
> So it runs SLiM version 3.3.2! Guess that's the issue. I'm not sure where that's coming from but that's my problem to fix haha.
> 
> Thanks for the help.

You're welcome!  Closing.  :->
