### ISSUE TITLE
feature request: do not include trailing blank space when pressing ctrl+shift+left/right

### ISSUE THREAD

**Issue by bobweek** [MesserLab/SLiM#336]
hi! in slimgui (linux version) holding ctrl+shift while pressing either right or left to highlight a word includes the trailing blank space (when it's there). in other ide's like rstudio and vscode, the trailing blank space is not included. if you could make slimgui conform to this standard, i think it would save users some time when writing scripts in slimgui. thanks!

**Comment by bhaller** [comment]
I'll look into it, but I doubt this behavior can be easily modified; it is defined by Qt, not by me.  Maybe I can override it somehow.  Thanks for the report; for what it's worth, I certainly agree!

**Comment by bhaller** [comment]
Hi @bobweek.  I've been eyeing this issue for the past year, and I think it's time to close it.  I think fixing it would be quite difficult and technical, and I'd be afraid of breaking other things in ways that might be hard to even notice right away.  The word selection algorithm is built into Qt, I think.  Sorry!
