### ISSUE TITLE
logfiles and absolute paths on windows

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#349]
Over in https://github.com/popsim-consortium/stdpopsim/pull/1342 we've run into an issue that if you pass `createLogFile` an absolute path in Windows it erroneously interprets it as a relative path. Ben says that

> I see the bug in log_file.cpp at line 61; it decides whether the path given by the user is an absolute path or not by checking whether the first character is '/' or not.  You might put alternative logic in a #ifndef _WIN32 block there.  See Eidos_ResolvedPath() at eidos_globals.cpp:1182 for a somewhat similar situation.

**Comment by bhaller** [comment]
OK, having sorted out the GitHub Actions issues that were getting in my way, it is now clear that I have managed to fix this issue.  Closing.
