### ISSUE TITLE
Error: condition for if statement has size() != 1 for partial sweeps

### ISSUE THREAD

**Issue by SBNoor** [MesserLab/SLiM#35]
I'm trying to simulate partial sweep. However, I want the script to run as long as partial sweep hasn't been established. The script runs for most of my simulations but for certain simulations it returns the following error:

![Screenshot 2019-03-11 at 14 58 21](https://user-images.githubusercontent.com/23297354/54129248-21deef00-440e-11e9-8c63-52d9f35d8afd.png)

My script is as follows:
<img width="690" alt="Screenshot 2019-03-11 at 15 00 11" src="https://user-images.githubusercontent.com/23297354/54129384-69657b00-440e-11e9-8278-7b3f87081bd8.png">

How can I get rid of this error? 
Lastly, I know I can create a haplotype plot using SLiM GUI. But I am running all these simulations from my terminal and I do not use SLiM GUI. Is there a way to save these haplotypes as well from the terminal?

**Comment by bhaller** [comment]
> How can I get rid of this error?
The variable mut is a vector of mutations, coming from mutationsOfType(m3).  The value of mut.selectionCoeff is therefore a vector too, of the selection coefficients of those mutations, and mut.selectionCoeff != 0 is then also a vector, of T/F values for whether each selection coefficient is zero or not zero.  An if statement requires a single T/F value; it makes no sense to try to do if (x) where x is a non-singleton vector of T/F values.  So you would want to use the all() or any() functions, depending upon whether you want the if statement to execute when all of the values are zero or when any of the values are zero.  You are probably going to have the same issue with other aspects of that code too, though; you need to think more about how you are using that mut vector, and which operations you want to be vectorized and which you don't.  See the Eidos manual for more on vectorization.

> Is there a way to save these haplotypes as well from the terminal?
No.

Please ask help questions on slim-discuss in future.  These questions are not an "issue" for SLiM.
