### ISSUE TITLE
SLiM 4.0.1 release process

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#356]
This seemed to work well for 4.0, so I guess I'll do it again.  This issue is for the roll of SLiM 4.0.1, which has been tagged in git (tag v4.0.1).  There are various things to do:

- [x] a new conda package (me)
- [x] a new Arch installer (@grahamgower)
- [x] a new macOS installer (me)
- [ ] a new Windows pacman installer (@rdinnager)
- [ ] our first Flatpak installer!  (for SLiMgui only) (@bryce-carson)
- [x] other Linux installers (@bryce-carson)

I'm not sure whether you'll be able to check off things when they're done, but anyway you can post about progress on this issue and I'll check things off.  Thanks!

**Comment by grahamgower** [comment]
First post!
https://aur.archlinux.org/packages/slim-simulator

:P

**Comment by bryce-carson** [comment]
[COPR build](https://copr.fedorainfracloud.org/coprs/bacarson/SLiM-Selection_on_Linked_Mutations/build/4836796/) has been submitted.

**Comment by bryce-carson** [comment]
The COPR build has completed successfuly, and the Flatpak has been submitted to Flathub for review. Once the maintainers of Flathub approve the pull-request, the application will be built and immediately published.

**Comment by bhaller** [comment]
Wow, Flathub replied quickly!  That's very nice.  FYI, I'll be offline for the next several hours, back on later today.  Thanks all.

**Comment by bryce-carson** [comment]
> Wow, Flathub replied quickly!  That's very nice.  FYI, I'll be offline for the next several hours, back on later today.  Thanks all.

Indeed! I'll always be AFK, but for a couple days. I have classes and homework that I need to prioritize now, but I should have this resolved on Saturday, I think.

**Comment by bhaller** [comment]
OK, SLiM 4.0.1 is officially released and announced.  The Windows and Flatpak installers will take a little longer to come out, as expected.  This issue will stay open until they do; please post with progress updates.  Thanks everybody!

**Comment by rdinnager** [comment]
Eek! I totally forgot about this. Apologies, I will get on it as soon as possible.

**Comment by bhaller** [comment]
> Eek! I totally forgot about this. Apologies, I will get on it as soon as possible.

I had forgotten too, lol.

**Comment by bryce-carson** [comment]
Flatpak is stuck because CMake is bring belligerent. :/ I don't have the time right now, but maybe late next week if I catch up in my courses.

**Comment by bryce-carson** [comment]
It's certainly been a long time since I've worked on getting the Flatpak ready. If I recall, it was almost done too...

I'll try to determine what the blocker in the CMake script was, then issue a new PR to address anything that needs doing for the Flatpak stuff.

---

I do recall:

- [X] The RPM .spec for Fedora needed to be updated to use CMake...
- [X] CMake was a pain...

**Comment by rdinnager** [comment]
@bhaller I'm available and on board for a 4.1 Windows installer, once its released.

**Comment by bhaller** [comment]
Closing this now, since the 4.1 release is imminent.

@grahamgower and @rdinnager, a warning shot: I'll open an issue for the 4.1 release later today.  It is tagged now, in fact, but please don't act quite yet; wait until the issue for the 4.1 roll has been opened, as I have a couple of things I'd like to make sure work first.  :->  Thanks!
