### ISSUE TITLE
Windows CI failing due to SIGTRAP

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#364]
The Windows CI (both CLI and GUI) presently fail for the "parallel" branch because they try to do `raise(SIGTRAP)`, from signal.h, but signal.h is not part of the Windows compatibility stuff yet.  See, e.g.:

https://github.com/MesserLab/SLiM/actions/runs/3405463393

This is an issue for @rdinnager; thanks Russell.

**Comment by bhaller** [comment]
@rdinnager note that the `parallel` branch has just been merged into `master`, so this issue is now breaking the CI of the `master` branch for Windows.  Would be great to get this fixed when you have a chance.  :->  Maybe once you remind yourself how this Windows compatibility stuff works, you could write up some notes about how to add a new file to it, and add those notes to the SLiM repo somewhere, so that others can do this when you're busy?  Thanks!

**Comment by rdinnager** [comment]
I should be able to work on this this week.

**Comment by bhaller** [comment]
With help from @rdinnager I have just pushed a fix that seems to work.  Thanks!
