### ISSUE TITLE
open and save file dialogs should start in working directory?

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#369]
If I navigate to a directory, and open SLiMgui from the command line, then that directory will be my working directory, e.g.:
```
mkdir test
cd test
SLiMgui
```
and then in SLiMgui, `getwd()` returns `<my home directory>/test`. However, if I then go to the Open File menu, SLiMgui starts me off in whatever the last directory was that I Opened a file in SLiMgui in. (Same for Save File, although this may be a different directory.) This is somewhat inconvenient, but maybe more seriously, it is confusing for people who haven't got the hang of the working directory yet. I'm hoping it's an easy adjustment to make, although I can see annoyances: within a given SLiMgui session, we do want to remember what the last directory used was, so if you open multiple files from the same place you don't always have to re-navigate there from the working directory. And, I don't know if there's an easy way to check "this is a new SLiMgui session, start in the working directory".

**Comment by petrelharp** [comment]
Yes, I'm not sure if I'm being reasonable here.  A quick test with libreoffice shows that if I

1. create a new file and save it in `test/`
2. quit
3. open that file, on the command line, from `test`, like `libreoffice test.odt`
4. go to Open File

then it'll pop me up in the last directory I opened a file from. 

However the "Save as" dialog gives me the directory the file lives in, as indeed SLiMgui does as well.

**Comment by bhaller** [comment]
In my experience (with other app development, not SLiMgui), wherever you choose to situation an open/save panel, somebody will be unhappy and file a bug; and if you change the behavior in response to that bug, somebody else will then be unhappy and file a bug.  There isn't really a "correct" behavior, in general; there is just the frustration of "I wanted it to be here, but it was there", which is very situational.  But as I said, I am happy to ponder it, and see whether I even have control over it.
