### ISSUE TITLE
SLiMgui prompts "This document has been modified" even though it hasn't

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#370]
Suppose I open SLiMgui, save the default recipe as `Untitled.slim`, and then immediately hit "quit". I am prompted "This document has been modified. Do you want to save your changes?", even though it hasn't been. This happens, on my system, seemingly all the time - SLiMgui seems to always think the recipe has been modified, which makes me paranoid (did I change something? I didn't mean to!) and makes me save, updating timestamps on recipes which could otherwise be useful information about when they were actually modified. It also means that the "document has been modified" warning is no longer useful.

There have been situations in which this didn't happen, but currently I can't find them: opening an already-existing file and immediately quitting; opening a file and running it then quitting; etcetera, all give me the dialog, in error.

This is on linux (debian); perhaps the "is file modified" acts differently here?

**Comment by bhaller** [comment]
It looks to me like this is Linux-only; doing this on macOS quits cleanly.  I can look into it, but debugging on Linux is hard (because I don't know the tools there), and in any case the bug is perhaps fairly likely to be inside Qt (since my code in SLiMgui is the same on both platforms).

**Comment by petrelharp** [comment]
It has always happened, and frequently, although perhaps it is more consistent after the upgrade?

**Comment by bhaller** [comment]
@petrelharp this would be a good thing to work on together while you're here, since I assume you have a Linux development environment with a debugger that you know how to use.

**Comment by bhaller** [comment]
@petrelharp Can you canvass folks in your lab about this?  We've only got one person in the lab using Linux, and he says this bug does not happen for him.  He's on Ubuntu.  I'm suspecting that this might be a Qt bug that is specific to Fedora or something.  (In which case it's probably fruitless to try to fix it in my code.)  Can you ask around?

**Comment by bhaller** [comment]
Looked into this on Peter's machine.  It looks like QtSLiMWindow::documentWasModified() is being called with a long backtrace that is completely inside Qt, setting the document to dirty.  I don't see any obvious way to short-circuit that.  The alternative fix, which should be easy, is to ignore Qt's modified flag entirely, and decide whether a document is modified or not based upon whether its script string is different from the last script string saved (which we can keep in a new ivar).
