### ISSUE TITLE
between-species interactions invalidated for species other than the first in reproduction()

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#374]
We're trying to simulate two interacting species; here is a stripped-down version of the script:
```
species all initialize() {
	initializeSLiMModelType("nonWF");
	initializeInteractionType(1, "xy", reciprocal=T, maxDistance=0.3);
	i1.setInteractionFunction("n", 3.0, 0.1);
}
species Ave initialize() {
	initializeSpecies(avatar="🐄", color="cornflowerblue");
	initializeSLiMOptions(dimensionality="xy");
}
species Med initialize() {
	initializeSpecies(avatar="👽", color="red");
	initializeSLiMOptions(dimensionality="xy");
}

ticks all 2: first() {
	Ave_pop = Ave.subpopulations;
	Med_pop = Med.subpopulations;
	i1.evaluate(c(Ave_pop,Med_pop));
}

species Ave reproduction() {
	i1.totalOfNeighborStrengths(individual, Med.subpopulations);
	catn("HELLO from AVE!");
}
species Med reproduction() {
	i1.totalOfNeighborStrengths(individual, Ave.subpopulations);
	catn("HELLO from MED!");
}

ticks all 1 early() {
	Ave.addSubpop("p1", 20);
	p1.setSpatialBounds(c(0,0,5,5));
	p1.individuals.x = runif(p1.individualCount);
	p1.individuals.y = runif(p1.individualCount);
	
	Med.addSubpop("p2", 20);
	p2.setSpatialBounds(c(0,0,5,5));
	p2.individuals.x = runif(p2.individualCount);
	p2.individuals.y = runif(p2.individualCount);
}

ticks all 10 late() {}
```

However, here's what happens:
1. the `Ave` reproduction callbacks run (as evidenced by the HELLOs)
2. we get the `ERROR (InteractionsDataForSubpop): the interaction must be evaluated for the receiver and exerter subpopulations, by calling evaluate(), before any queries.` for the `Med` reproduction callback.

For our actual use case it is more efficient to do the interaction stuff vectorized in `first()` before the reproduction callback; still, if it is correct that the interactions have been invalidated this seems like at the least a confusing situation that calls for more guidance (I couldn't find any in the manual?). Also curiously, the version of SLiMgui that I had on my machine (4.0.1, but git SHA 9e70444) did not produce this error; re-installing the release 4.0.1 produced the error.

**Comment by bhaller** [comment]
Hi Peter!  This is a known bug, fixed post-4.0.1.  If you use the current GitHub head, your test model above works fine, for me at least.  Let me know if that doesn't work for you folks.  Closing.
