### ISSUE TITLE
simulation inscrutibly dies out

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#381]
Here is a very simple simulation that should *not* die out AFAICT. (I am using it as a test in fixing https://github.com/tskit-dev/pyslim/issues/321). It *should* just, every 1000 ticks, have each of the two individuals self once then die. *However*, instead it dies out, in tick 50012. Changing the seed changes the tick that it dies out in. Note that this is *not* a tick in which reproduction happens. I have no idea what's going on.
```
initialize()
{
    setSeed(123);
    initializeSLiMModelType("nonWF");
    initializeMutationRate(1e-4);
    initializeMutationType("m1", 0.5, "f", -0.1);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 99);
    initializeRecombinationRate(1e-4);
}

reproduction() {
    if (individual.tag > 0) {
       offspring = subpop.addSelfed(individual);
       offspring.tag = 0;
    }
}

1 early() { 
    sim.addSubpop("p1", 1);
    sim.addSubpop("p2", 1);
    sim.subpopulations.individuals.tag = 0;
}

first() {
    if (community.tick % 1000 == 0) {
       catn("reproduction: " + community.tick);
       sim.subpopulations.individuals.tag = 1;
       sim.subpopulations.individuals.fitnessScaling = 0;
    }
}

1: late() { if (p1.individualCount == 0) { catn("died out in tick " + community.tick); community.simulationFinished();} }

300000 first() {
    catn("Done.");
    sim.simulationFinished();
}
```

I wondered if perhaps we were having individuals with fitnessScaling=1.0 die because of rare events producing random numbers that are exactly 1.0, but setting everyones' fitnessScaling to 1.1 does not change anything.

p.s. I am probably missing something silly, and apologize in advance.

**Comment by petrelharp** [comment]
Note: removing the `first()` block and changing the reproduction to
```

reproduction() {
    if (community.tick % 1000 == 0) {
       catn("reproduction: " + community.tick);
       offspring = subpop.addSelfed(individual);
       offspring.tag = 0;
       individual.fitnessScaling = 0.0;
    }
}
```
results in exactly the same thing (in the same tick).

**Comment by petrelharp** [comment]
Also note that if you start the populations with more than one individual, they slowly go down in size; this one loses an individual in tick 410:
```
initialize()
{
    setSeed(1234);
    initializeSLiMModelType("nonWF");
    initializeMutationRate(1e-4);
    initializeMutationType("m1", 0.5, "f", -0.1);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 99);
    initializeRecombinationRate(1e-4);
    defineConstant("N", 10);
}

reproduction() {
    if (community.tick % 100 == 0) {
       offspring = subpop.addSelfed(individual);
       individual.fitnessScaling = 0.0;
    }
}

1 early() { 
    sim.addSubpop("p1", N);
    sim.addSubpop("p2", N);
}

1: late() { if (p1.individualCount + p2.individualCount < 2 * N) { catn("died out in tick " + community.tick); community.simulationFinished();} }

300000 first() {
    catn("Done.");
    sim.simulationFinished();
}
```

**Comment by bhaller** [comment]
Well... explain to me why it shouldn't die out.  You have a mutation type that is deleterious, and a mutation rate of 1e-4, so every once in a while you'll get mutations arising that decrease fitness.  Decreased fitness means decreased probability of survival, in a nonWF model.  And so individuals occasionally die.  Why is that surprising?

**Comment by petrelharp** [comment]
Oh! lol, I missed the "deleterious" part.

I'd apologize but I already had that covered: =)  

> p.s. I am probably missing something silly, and apologize in advance.
