### ISSUE TITLE
compile failure of `core/chromosome.cpp` on gcc 13.1.1

### ISSUE THREAD

**Issue by clwgg** [MesserLab/SLiM#382]
I'm getting a somewhat cryptic compile failure on (arch)linux after upgrading to gcc version 13.1.1, where compiling the `slim` binary crashes on `core/chromosome.cpp`. The `cmake` output is [here](https://github.com/MesserLab/SLiM/files/12223961/compile_error.txt), but be warned as it contains >1500 lines.
I've confirmed this happens on a fresh arch box with:
 `gcc-13.1.1-2`, `gcc-libs-13.1.1-2`, `cmake-3.27.1-1`

I was able to remedy the failure by downgrading to:
 `gcc-12.2.1-4`, `gcc-libs-12.2.1-4`, `cmake-3.26.4-1`

Downgrading only `cmake` didn't remedy the failure, but I couldn't only downgrade `gcc` because of dependencies between `gcc-libs-13` and `cmake-3.27`.

It's not a pressing problem for me as everything works fine after downgrading, but I thought I'd pass it along!

**Comment by clwgg** [comment]
Also, I'm not sure if this is helpful, but the failure reported above only occurs with `make slim` as the compile target, i.e. when compiling `CMakeFiles/slim.dir/core/chromosome.cpp.o`, while interestingly `make SLiMgui` proceeds just fine, including `CMakeFiles/SLiMgui.dir/core/chromosome.cpp.o`.

**Comment by bhaller** [comment]
Hmm.  This looks like some kind of toolchain configuration error.  I'm not going to worry about it much; certainly most of these errors reported are not, in fact, errors.  :->  But it does look like there's one or two useful things about missing STL includes that might be harvested from this dump.  I'll do that and then close.

**Comment by clwgg** [comment]
ok, it looks like after an upgrade to `gcc-13.2.1-3` and `gcc-libs-13.2.1-3` everything works fine again! not sure what happened there, sorry about the noise! :sweat_smile:

**Comment by bhaller** [comment]
No worries, these things happen.  Toolchain problems are annoying and confusing.

**Comment by bhaller** [comment]
It looks like maybe it was getting compiled as C rather than C++, or something bizarre like that.  Anyhow, I did find a couple of missing includes as a result.  :->

**Comment by petrelharp** [comment]
FWIW I had the same experience on a fresh Debian install - the current version in "unstable" [is 13.1.0](https://packages.debian.org/sid/gcc), which failed to compile in the same way, but it all worked fine after manually installing [13.2.0](https://packages.debian.org/sid/gcc-13). (So, probably some upstream issue that is fixed and won't affect anyone ever again?)
