### ISSUE TITLE
minor update to install docs for linux

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#385]
The manual currently says that to get the Qt whatnot for building SLiMgui on Debian/Ubuntu one needs to do
```
sudo apt-get install qt5-default
```
The package [qt5-default](https://packages.debian.org/buster/qt5-default) did indeed use to be the package, but since then it's been called [qtbase5-dev](https://packages.debian.org/bookworm/qtbase5-dev). Futhermore, it looks to me like even on the older systems (pretty old now) installing `qtbase5-dev` would get you what you need also.

So, I think that line needs to be changed to
```
sudo apt-get install qtbase5-dev
```

**Comment by petrelharp** [comment]
ps. looks like most all Debian versions would give you Qt 5.15 now, so the next few sentences in the manual could be deleted. Same for Ubuntu: here's [the current long-term stable release](https://packages.ubuntu.com/mantic/qtbase5-dev) and [testing](https://packages.ubuntu.com/jammy/qtbase5-dev).

**Comment by bhaller** [comment]
OK thanks, I'll tweak this and follow up here if I have any questions.

At some point I'm gonna need to cross over to Qt 6.  That'll be a whole new adventure!  :->

**Comment by bhaller** [comment]
Docs fixed, closing.
