### ISSUE TITLE
add ability to draw from the 2d distribution whose cross-section is the t distribution

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#389]
This is *not* a terribly natural thing to do from the point of view of probability, but since it matches best with existing spatial kernel stuff, I've figured out how to do it.

What we'd like to do is to sample from the 2D distribution that is radially symmetric and has value, as a function of radius, equal to `dt(r, df)`, where `dt` is the t distribution's density. The radius of the resulting bivariate draw has density proportional to
$r (1 + r^2/\nu)^{-(\nu+1)/2}$,
and after doing some integrals and algebra, we end up with a cumulative distribution function $F$ that is, for $x > 0$,
$F(x) = 1 + (1 - (1 + x^2/\nu)^{(\nu-1)/2})/2$
and so for $u > 1/2$,
$F^{-1}(u) = \sqrt{\nu ( [2(1-u)]^{-2/(\nu-1)} - 1 )} .$

Here's the verification, comparing the draws to size-biased draws from a t distribution.
```
sb <- function (x) {
    return(x[runif(length(x)) < abs(x)/max(abs(x))])
}

Finv <- function (x, df) {
    pos <- (x > 1/2)
    x <- 1/2 + abs(x-1/2)
    z <- sqrt(pmax(0, (df * ( 1 / (2 - 2*x)^(2/(df-1)) - 1))))
    z[!pos] <- -1 * z[!pos]
    return(z)
}

Fn <- function (x, df) {
    pos <- (x > 1/2)
    z <- (1/2) * (1 - 1 / (1 + x^2/df)^((df-1)/2))
    return(1/2 + sign(x) * z)
}

df <- 5
tt <- rt(1e7, df=df) |> sb()
Ft <- Finv(runif(length(tt)), df=df)

xx <- seq(-10, 10, length.out=201)
pp <- seq(0, 1, length.out=2001)

layout(1:3)
plot(sort(tt), sort(Ft)); abline(0, 1)
plot(xx, Finv(Fn(xx,df=df),df=df))
plot(pp, Fn(Finv(pp,df=df),df=df))

layout(1:2)
plot(xx, Fn(xx, df=3), type='l')
plot(pp, Finv(pp, df=3), type='l')
```

**Comment by bhaller** [comment]
just committed the fix to the `smooth` branch, closing!  :->
