### ISSUE TITLE
allow 'user_metadata' to be loaded with tree sequence when using readFromPopulationFile()

### ISSUE THREAD

**Issue by ShyamieG** [MesserLab/SLiM#393]
Hi there,

I have been discussing ways to annotate tree sequences generated by SLiM with additional metadata. Over the course of some discussion with @petrelharp, I learned that SLiM currently won't really allow me to do [what I'm attempting](https://github.com/tskit-dev/tskit/issues/2842#issuecomment-1736077666).

While I will be able to work around this issue for now, [Peter suggested](https://github.com/tskit-dev/tskit/issues/2842#issuecomment-1736664758) that it would be useful if SLiM could load any 'user_metadata' associated with a tree when using readFromPopulationFile(). Basically, the goal would be for 'user_metadata' to be accessible (and modifiable) within SLiM such that it can be passed along with the tree sequence file across multiple chained-together instances of SLiM.

Is this something that would be possible? Or are there currently other ways of accomplishing this goal?

**Comment by ShyamieG** [comment]
Okay, it seems like the solution to this already exists, and it is to use treeSeqMetadata()

Thanks for your help @bhaller!

**Comment by petrelharp** [comment]
LOL, good work, @bhaller! I had a vague memory that this existed already, but couldn't find it in the manual...

**Comment by bhaller** [comment]
Yes, as a side effect of this conversation I've realized that there are one or two spots in the manual where `treeSeqMetadata()` ought to be mentioned but isn't.  I'll be adding those.  Thanks!
