### ISSUE TITLE
possible issue in `sampleNearbyPoint`?

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#396]
In investigating why `sampleNearbyPoint` seems to be going so slooow in some cases, I noticed the following thing that looks wrong to me? Observe that in `sampleNearbyPoint`, the [reference point is scaled by the bounds](https://github.com/MesserLab/SLiM/blob/master/core/spatial_map.cpp#L2322) to lie between 0 and 1. However, to this point [is added a displacement](https://github.com/MesserLab/SLiM/blob/master/core/spatial_map.cpp#L2334) that if I'm reading correctly, is [*not* correspondingly scaled](https://github.com/MesserLab/SLiM/blob/master/core/spatial_kernel.cpp#L359).  (I am probably missing something, though.)

**Comment by bhaller** [comment]
Yep, that's a bug for sure.  :->  Good catch.  It's hard to test this stuff – I don't know what a unit test looks like for a method like this that is (a) complicated, (b) has many different cases and code paths, and (c) is stochastic.  An ongoing battle.  :-O  Anyhow, yes.  I'll try to get a fix in before I leave for vacation.

**Comment by bhaller** [comment]
OK, I've written a fix; had some time this morning, happily.  Here is my current test model, which now appears to work:

```
initialize() {
	initializeSLiMModelType("nonWF");
	initializeSLiMOptions(dimensionality="xy");
	defineConstant("K", 1000);	// carrying capacity
}

reproduction() {
}

1 early() {
	sim.addSubpop("p1", K);
	sim.addSubpop("p2", K);
	
	p1.setSpatialBounds(c(3.21, 6.85, 4.59, 8.05));
	p2.setSpatialBounds(c(3.21, 6.85, 4.59, 8.05));
	
	pos = p1.pointUniform(K);
	p1.individuals.setSpatialPosition(pos);
	p2.individuals.setSpatialPosition(pos);
	
	map = p1.defineSpatialMap("foo", "xy", matrix(runif(100, 0, 1), ncol=10), valueRange=c(0,1), colors=c("black", "white"));
	defineConstant("MAP", map);
	
	p2.addSpatialMap(MAP);
}
2 early() {
	MAP.interpolate(15, "cubic");
}
3 early() {
	MAP.smooth(0.2, "n", 0.07);
}
4 early() {
	range = MAP.range();
	print(range);
	
	MAP.subtract(range[0]);
	range = MAP.range();
	print(range);
	
	MAP.multiply(1 / range[1]);
	range = MAP.range();
	print(range);
	
	MAP.power(1.5);
	range = MAP.range();
	print(range);
}

5: early() {
	// move individuals towards good habitat
	inds = p1.individuals;
	locs = inds.spatialPosition;
	new_locs = MAP.sampleNearbyPoint(locs, 0.002, "n", 0.001);
	inds.setSpatialPosition(new_locs);
	
	inds = p2.individuals;
	locs = inds.spatialPosition;
	new_locs = MAP.sampleImprovedNearbyPoint(locs, 0.002, "n", 0.001);
	inds.setSpatialPosition(new_locs);
}

200000 late() {  }
```

It used to use the default spatial bounds (and thus did not detect this bug).  Now it uses weird spatial bounds, and the bug appears to be fixed.  PR coming momentarily.

**Comment by petrelharp** [comment]
Also: damn, you're quick. =)

**Comment by bhaller** [comment]
> Suggestions for unit tests:

@petrelharp good suggestions, thanks.  I've made a note of them, but they won't happen for a while.  Leaving for Portugal on Monday.
