### ISSUE TITLE
`pointDeviated` documentation

### ISSUE THREAD

**Issue by jiseonmin** [MesserLab/SLiM#399]
Hi, I just want to start a discussion on `pointDeivated` documentation here, following up to the spatial sims meeting.
First, I think a more clear explanation on how functionType specific input should be formatted can be helpful. i.e. what goes in to ... after functionType?
Second, I thought maybe we can explain what `pointDeviated` does with the kernel differently? Here is what I've brainstormed:

`pointDeviated` returns a vector of n points that are sampled in a radially symmetric way. The projection of the displacement vector to any axis is sampled from the kernel specified by `functionType`. (i.e. in 2D $\theta \sim U(0,2\pi)$, $r \cos\theta \sim$ kernel and in 3D $r \cos\theta \cos\phi\sim$ kernel and $\theta \sim U(0,2\pi)$, $\phi \sim U(0, \pi)$.) Only the distributions that are normalizable are allowed as a dispersal kernel(?). So Cauchy kernel ("c") is not available. In 2D student's t kernel ("t") is available, where it takes number of degrees of freedom as the first argument (has to be at least 3) and a scale factor as the second argument. However, in 3D, "t" cannot be used. "e" for exponential distribution and "n" for normal distribution are available in all dimensions (reference somewhere for formatting). And something about a box kernel and other options?

I specifically wrote about student's t distribution because it's only used in spatial kernel, which is not publicly visible. I am not totally sure if this is consistent with what `pointDeviated` does, so I would appreciate @bhaller and @petrelharp's comments.
Thanks!

**Comment by petrelharp** [comment]
I think maybe writing down what the distribution of either $r \cos \theta$ (like you suggest) or $r$ actuall is would be too much detail - perhaps just a note explaining that (a) we sample from the kernel whose value is a given function of distance, and (b) note that the distribution on distance is not actually the one named by the kernel except in 1D (and let folks figure out what it actually is, maybe have a technical notes in the docs somewhere)?

**Comment by jiseonmin** [comment]
Yeah, so just say a displacement along any direction is sampled from the kernel?

**Comment by bhaller** [comment]
OK, so right now the relevant bit of the `pointDeviated()` doc says:

The dispersal kernel is specified similarly to other kernel-based methods, such as setInteractionFunction() and smooth(); see the InteractionType class documentation for detailed discussion of the available spatial kernel types and their parameters (supplied in the ellipsis, ...).  For pointDeviated(), the Cauchy ("c") kernel is not allowed since it is not well-behaved for this purpose, and the Student’s t ("t") kernel is not allowed in 3D models at present simply because it hasn’t been implemented.  The random points returned from this method are drawn from the probability distribution that is radially symmetric and has density proportional to the interaction strength – in other words, at distance r the density is proportional to the functional form referred to by functionType.  For instance, the density of the probability distribution for type "e" with rate a at distance r is proportional to exp(−ra); and so the distribution of the distance in 1D is exponential, while in 2D it is proportional to r exp(−ra) (i.e., Gamma with shape parameter 1).

That seems like it says pretty much what is being proposed, but perhaps I'm missing the point?

**Comment by jiseonmin** [comment]
My only concern is that the last sentence of the existing doc might be confusing. That is why I personally like the projection of displacement along an axis better than distance from the origin - I think the projection should have the same distribution regardless of the dimensionality, so you can avoid talking about the factor of r or r^2?

**Comment by bhaller** [comment]
I'm not math-y enough to understand all of this, so you and @petrelharp will need to arrive at a consensus.  :->

**Comment by jiseonmin** [comment]
Fair enough, how does this sound to you, @petrelharp: 
Regardless of the dimensionality, projection of the distance traveled along any axis is a random variable sampled from the dispersal kernel specified by `functionType`. The distance, however, follows a different distribution if in 2D or 3D, but related to the kernel - see somewhere for mathematical details? 

Going back to the point about `functionType` and its arguments though, can we maybe list what the options are for `functionType` in each dimension and what goes in ... for each of them?

**Comment by bhaller** [comment]
Ping @petrelharp.  I'd like to resolve and close this, thanks.

**Comment by bhaller** [comment]
> Going back to the point about `functionType` and its arguments though, can we maybe list what the options are for `functionType` in each dimension and what goes in ... for each of them?

Regarding this, I've just pushed a tweak to the docs for this suggestion.  Here's how it now reads:

> `– (float)pointDeviated(integer$ n, float point, string$ boundary, numeric$ maxDistance, string$ functionType, ...)`
> Returns a vector containing n points that are derived from point by adding a deviation drawn from a dispersal kernel (specified by maxDistance, functionType, and the ellipsis parameters ..., as detailed below) and then applying a boundary condition specified by boundary.  This method therefore performs the steps of a simple dispersal algorithm in a single vectorized call.
> The parameter point may contain a single point which is deviated and bounded n times, or may contain n points each of which is deviated and bounded.  In any case, each point in point should match the dimensionality of the model – one element in a 1D model, two elements in a 2D model, or three elements in a 3D model.  This method should not be called in a non-spatial model.
> The dispersal kernel is specified similarly to other kernel-based methods, such as setInteractionFunction() and smooth().  For pointDeviated(), functionType may be “f" with no ellipsis arguments ... to use a flat kernel out to maxDistance; “l" with no ellpises arguments for a kernel that decreases linearly from the center to zero at maxDistance; "e", in which case the ellipsis should supply a numeric$ lambda (rate) parameter for a negative exponential function; "n", in which case the ellipsis should supply a numeric$ sigma (standard deviation) parameter for a Gaussian function; or "t", in which case the ellipsis should supply a numeric$ degrees of freedom and a numeric$ scale parameter for a t-distribution function.  The Cauchy ("c") kernel is not supported by pointDeviated() since it is not well-behaved for this purpose, and the Student’s t ("t") kernel is not allowed in 3D models at present simply because it hasn’t been implemented.  See the InteractionType class documentation (section 25.8) for more detailed discussion of the available kernel types and their parameters and probability distribution functions.  The random points returned from this method are drawn from the probability distribution that is radially symmetric and has density proportional to the kernel – in other words, at distance r the density is proportional to the kernel type referred to by functionType.  For instance, the density of the probability distribution for type "e" with rate a at distance r is proportional to exp(−ra); and so the distribution of the distance in 1D is exponential, while in 2D it is proportional to r exp(−ra) (i.e., Gamma with shape parameter 1).
> The boundary condition must be one of "none", "periodic", "reflecting", "stopping", or "reprising".  For "none", no boundary condition is enforced; the deviated points are simply returned as is.  For "periodic", "reflecting", and "stopping", the boundary condition is enforced just as it is by the pointPeriodic(), pointReflected(), and pointStopped() methods; see their documentation for further details.  For "reprising", if the deviated point is out of bounds a new deviated point will be chosen, based upon the same original point, until a point inside bounds is obtained.  Note that absorbing boundaries (for which being out-of-bounds is lethal) would be implemented in script; this method cannot enforce them.
> In the typical usage case, point comes from the spatialPosition property for a vector of individuals, and the result is then set back onto the same vector of individuals using the setSpatialPosition() method; however, this method might be useful in other situations too.

Let me know if there are further changes you propose here.  Happy to also integrate changes to the math-y portion of the doc once you two arrive at a consensus; or if you decide no change is needed, please close this issue.  Thanks!

**Comment by jiseonmin** [comment]
This looks great! Sorry it took a long time for me to understand the math behind the function, but I think Peter and I are in agreement now.
