### ISSUE TITLE
generalize InteractionType sexSegregation to other restrictions

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#402]
This is an idea from @jiseonmin.  Right now, `InteractionType` has the `sexSegregation` facility that allows you to narrow down which individuals are eligible to be exerters or receivers.  The idea here is that this could be broadened to allow other constraints as well.  @jiseonmin was specifically suggesting a minimum/maximum age, but one can imagine all sorts of other constraints, similar to how `subsetIndividuals()` and `sampleIndividuals()` work.  Presumably you would want to allow different restrictions for the exerter than for the receiver, just as for `sexSegregation`.  So there are potentially lots of separate configuration switches here.  A good API would need to be defined, and probably the current `sexSegregation` facility would be moved over to that new API for consistency, and removed from `initializeInteractionType()`.  Something like `constrainExerters()` and `constrainReceivers()`, perhaps.  Under the hood, this would be done with something like a top-level flag, "constraints exist", and if that flag is set, an eligibility method that would get called to check the eligibility of each potential receiver/exerter, replacing the current sex-segregation checks.

This feature would be quite useful in scenarios where, e.g., only adults interact, or mate search should only find individuals with a particular tag value, etc.  Probably quite broad and general applications.

**Comment by bhaller** [comment]
@jiseonmin @petrelharp This issue got a bit buried in my to-do list.  Is it a feature that would be useful for the spaceness paper?  If so, I could prioritize it.  I like the way that the spaceness paper is pushing the addition of new useful functionality for spatial models, and I'm happy to continue doing that.  But if this isn't needed for the paper, then I'll probably mark it long-term.

**Comment by jiseonmin** [comment]
Thanks Ben for reminding me of this! I think it will be useful for both
vignettes involving life cycle model and the mate choice section. Currently
we mostly talk about sex segregation in mate choice section, but I think it
will be interesting to generalize it for the same reasons you mentioned.

**Comment by petrelharp** [comment]
It might also be useful for @samchamper's model? So, sounds like: useful, but not "needed" in the sense that we can do things other ways?

**Comment by bhaller** [comment]
Just fixed in https://github.com/MesserLab/SLiM/commit/5946830e8132c691a3000a264fb8e51300c75d32.  I'll post new draft documentation to Slack.
