### ISSUE TITLE
max(1,2) != max(2,1)

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#41]
max() on integer arguments always returns the first argument.

```
diff --git a/eidos/eidos_functions.cpp b/eidos/eidos_functions.cpp
index 9bd3deee..28f02312 100644
--- a/eidos/eidos_functions.cpp
+++ b/eidos/eidos_functions.cpp
@@ -3615,7 +3615,7 @@ EidosValue_SP Eidos_ExecuteFunction_max(const EidosValue_SP *const p_arguments,
 			
 			if (arg_count == 1)
 			{
-				int64_t temp = arg_value->LogicalAtIndex(0, nullptr);
+				int64_t temp = arg_value->IntAtIndex(0, nullptr);
 				if (max < temp)
 					max = temp;
 			}
```

**Comment by bhaller** [comment]
Gah.  Well that's bad.  How did this get past my unit tests??  Well, thanks, I'll fix this in SLiM 3.3 which should be released this week.

**Comment by bhaller** [comment]
There needs to be a "recoil in horror" reaction on GitHub.

**Comment by bhaller** [comment]
BTW, not so much that it always returns the first argument, as that singleton integer arguments get coerced to logical type, and so values other than 0 or 1 are mishandled – 0 is treated as 0, 1 is treated as 1, all other values are coerced to 1.  Anyway, horrifying, fixed.  Thanks for the report.
