### ISSUE TITLE
SLiM 4.2.1 release process

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#439]
Hi all.  Sadly, I now have to roll SLiM 4.2.1, because of a bug that was found.  It's not common, and it usually leads to a crash (which is not so bad, in the big picture), but sometimes it leads to incorrect results (which is unacceptable).  So, here we go.  Sorry.

- [x] a new conda package (me)
- [x] a new macOS installer (me)
- [x] a new Arch installer (@grahamgower)
- [x] a new Windows pacman installer (@rdinnager)
- [x] Linux installers (@bryce-carson)

Since almost nothing has changed from 4.2, hopefully this will go smoothly and painlessly.  I am not re-rolling the doc apart from the version number change, because changes were minimal and doing a full doc re-roll takes hours.  The little changes that were made can be in the next release, whenever that happens.

I have tagged the repo with `v4.2.1`, but have not created the official Release from that tag.  Stay tuned.

**Comment by bhaller** [comment]
@bryce-carson I changed the .spec file, hopefully correctly.  :->

**Comment by bhaller** [comment]
There was a flaw in the tagged release.  I just removed the `v4.2.1` tag and made a new `v4.2.1` tag.  The new tag's description says it is "final candidate 2", so you can tell the difference.  The conda build had already completed based on the original tag; I'm not sure whether I need to redo it.  (The flaw did not affect the conda build, because it was a QtSLiM issue, and conda doesn't build QtSLiM.)  Does conda mind if the tag that it made a build based upon no longer exists?  Anybody know?  Or if somebody is a conda user, maybe they could check that v4.2.1 installs from conda smoothly, despite this switcheroo?

**Comment by bryce-carson** [comment]
> @bryce-carson I changed the .spec file, hopefully correctly. :->

It looks correct to me. 😃 I submitted the build.

**Comment by bryce-carson** [comment]
> There was a flaw in the tagged release. I just removed the `v4.2.1` tag and made a new `v4.2.1` tag. The new tag's description says it is "final candidate 2", so you can tell the difference. The conda build had already completed based on the original tag; I'm not sure whether I need to redo it. (The flaw did not affect the conda build, because it was a QtSLiM issue, and conda doesn't build QtSLiM.) Does conda mind if the tag that it made a build based upon no longer exists? Anybody know? Or if somebody is a conda user, maybe they could check that v4.2.1 installs from conda smoothly, despite this switcheroo?

I don't know about the question surrounding Conda.

I'll resubmit the build on Copr, to be sure that it is building the correct sources.

**Comment by bhaller** [comment]
Looks like the Copr build is done on all platforms!  Rolling on.

**Comment by bhaller** [comment]
The release itself now exists (https://github.com/MesserLab/SLiM/releases/tag/v4.2.1), and it has been announced on slim-discuss and slim-announce.  I'm assuming conda is fine until someone tells me otherwise.  :->  Ping @grahamgower @rdinnager.  I'll close this issue when all installers are updated, as usual.  Thanks everybody!

**Comment by grahamgower** [comment]
I've updated the arch package.

I'm not 100% certain, but if the conda-forge infrastructure built a release from the initial tag then I reckon it should be fine. It doesn't look like the new tag was picked up by the automation rules, so I guess it won't be a problem.

**Comment by rdinnager** [comment]
@bhaller Okay, PR has been merged for pacman (https://github.com/msys2/MINGW-packages/pull/20672). Should be available to users within a day or two max.

**Comment by bhaller** [comment]
> @bhaller Okay, PR has been merged for pacman ([msys2/MINGW-packages#20672](https://github.com/msys2/MINGW-packages/pull/20672)). Should be available to users within a day or two max.

Thanks @rdinnager!  I'll keep an eye on the status.  :->

**Comment by bhaller** [comment]
Looks like the pacman installer is up @rdinnager (or at least `slim-simulator` vanished from that page!), so this issue is done and I'll close it now.  :->  Thanks everybody!  Hopefully the next release won't happen for a good long time!
