### ISSUE TITLE
blank lines in vcf files

### ISSUE THREAD

**Issue by TomJamesW** [MesserLab/SLiM#44]
Hi SLiM team,

I am running simulations in SLiM before analysing them in R with the package vcfR. My session kept crashing when I tried to read in specific vcf files. After inspecting the files, I discovered they aren't being read in as they have consecutive blank rows. This only seems to happen with simplifyNucleotides=T inside the function, specifically when back mutations are removed. I'm able to work round this in R but still thought it worth making you aware if you weren't already.

The attached script outputs two files: "broken.vcf", with consecutive blank lines before eg POS=346; and "fixed.vcf" which does not.

[simnuc.slim.zip](https://github.com/MesserLab/SLiM/files/3376652/simnuc.slim.zip)

Many thanks,
Tom

**Comment by TomJamesW** [comment]
p.s. the SLiM script needs to be run with seed=19 for the said outputs.

**Comment by bhaller** [comment]
Hi @TomJamesW, thanks for the very clear bug report with a reproducible case!  :->  This bug has now been fixed in the current GitHub head of the master branch.
