### ISSUE TITLE
no gcc-11 for ubuntu-20.04, and other perhaps out-of-date Actions settings

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#445]
Hi @grahamgower and @bryce-carson!  See the GitHub Actions error here:

https://github.com/MesserLab/SLiM/actions/runs/9170110315/job/25212700020

This just started happening, I think.  The obvious fix is just to remove this build configuration from the GitHub Actions suite, which is easy enough to do of course.  I suppose they have perhaps just discontinued/deprecated `gcc-11` for some reason, at least on the `ubuntu-20.04` platform?  I find that surprising, especially since even gcc-7 is still supported on that platform, but who knows...?  But I thought I'd check with you guys first to see if you have any knowledge/opinion here.

Maybe it is also some random temporary failure, I suppose.  I'll try re-running that build in a day or two, and see if the problem fixes itself, I guess.

In general, I wonder how/where one can find out which packages are supported for a given platform; there must be a big list somewhere, right?  Probably the GitHub Actions tests are out of date in other respects anyway, such as the Qt5 version they are based on.  So I've just broadened the title of this issue to reflect that larger possible scope for this issue.

**Comment by grahamgower** [comment]
As frustrating and non-transparent as this is, it seems like the breakage was deliberately introduced. See https://github.com/actions/runner-images/issues/9679 for what changed and how to fix it.

I found this out by following some links in the workflow logs to the git repo for the runner image (see lines 9 and 10 under "Set up job"), then poking around in the issues.
![setup-job-runner-image](https://github.com/MesserLab/SLiM/assets/8665077/d55db52a-51e6-48ed-9373-261a477e23b4)

**Comment by bhaller** [comment]
Is that in fact related?  That seems to say that gcc 13 and 14 will break, not 11; and 12 still works for SLiM.  Maybe a red herring?  But I guess I can try the fix...

**Comment by grahamgower** [comment]
I've never used Ubuntu, so I'm not sure how they've chosen to organise things. There appear to be at least two repositories carrying toolchain builds. And they appear to correspond to different Ubuntu versions.

https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa

**Comment by bhaller** [comment]
@grahamgower Added those lines, and it fixed the build.  Thanks very much for tracking this down!  :->  (Quite annoying that they deliberately broke something as simple as installing a slightly older compiler version like gcc-11!  I wonder how many thousands of developers had to figure out the fix for this problem!  They could have at LEAST come up with a way to emit a better error message, it seems to me!)
