### ISSUE TITLE
Trouble installing on Ubuntu 22 

### ISSUE THREAD

**Issue by Alan-Izarraras** [MesserLab/SLiM#446]
Hi! 

Having trouble installing SLiM on my Ubuntu 22 machine. 
When executing install script DebianUbuntuInstall.sh I get the following error: 

´
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to download https://github.com/MesserLab/SLiM/archive/refs/tags/v4.2.2.tar.gz as SLiM-4.2.2.tar.gz or decompress and unarchive it.
´
It seems like the directory was changed?

**Comment by bhaller** [comment]
Hi!  That link (I clicked on it directly from the issue text above) downloads and unzips just fine on my end.  Perhaps you're having network issues, or browser cache issues, or browser compatibility issues, who knows what else; but the link is fine, I think.  Closing; feel free to reopen if you continue to think there is a problem (that is not on your machine's end).

**Comment by bhaller** [comment]
@bryce-carson tagging you just in case there might be some issue with the way `DebianUbuntuInstall.sh` pulls over the download; but that seems unlikely I guess?

**Comment by bryce-carson** [comment]
> @bryce-carson tagging you just in case there might be some issue with the way `DebianUbuntuInstall.sh` pulls over the download; but that seems unlikely I guess?

Indeed, the links are good. From the stdout the user included it appears that nothing was downloaded (or appears that way because they elided the download progress?), and so tar and gzip necessarily complained.
