### ISSUE TITLE
system() waits for child to return, even when using &

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#45]
The following script is accepted by both Rscript and eidos. The intended behaviour is that the sleep command is run in the background. This is what Rscript does, but the `system()` function in eidos always waits for the child process to complete. An alternative method to run a command in the background would be fine (e.g. a parameter to system()), but I have not found this functionality in the eidos manual.
 
```
system("sleep 5 &");
print("system() returned");
```

**Comment by grahamgower** [comment]
I note that in section 14.8 of the SLiM manual, there is a request for a Linux user to contribute a way to "open" a pdf with the default pdf viewer. The canonical way to do this on Linux is with the `xdg-open` command. However, this is a blocking command (unlike `open` on MacOS), and so would need to be run in the background.

**Comment by grahamgower** [comment]
As a workaround, one may prefix the command with `coproc`, which is a bash builtin. But this only works when bash is the shell. I don't know of a portable way to do this.

```
system("coproc sleep 5");
print("system returned");
```

**Comment by bhaller** [comment]
I've just committed a fix to the master branch on GitHub.  There is now a "wait" parameter to system, T by default but if F is supplied then the command is run in the background by appending an &.  You can append an & yourself, which should produce the same result, so your example of `system("sleep 5 &");` should now run in the background without a wait on its completion.  Let me know if you see any problems with this.  And re: recipe 14.8, I would very much appreciate it if you would submit (via email or an issue) the exact Eidos code needed to adapt the model to Linux.  Thanks!
