### ISSUE TITLE
treeSeqSimplify not recognized by SLiM

### ISSUE THREAD

**Issue by bguo068** [MesserLab/SLiM#450]
Hi @bhaller,

I am working on sampling some ancestors from 2000 generations before the last generation during a forward simulation in SLiM. According to the SLiM Manual (v4.2.2) and SLiMgui Help, one can disable SLiM's auto-simplification by setting `simplificationRatio=INF ` in the `initializeTreeSeq()` function and then manually calling the `treeSeqSimplify()` method. However, it seems that SLiM does not recognize the `treeSeqSimplify` function. Below is my SLiM script:

```slim
initialize()
{
	initializeTreeSeq(simplificationRatio=INF); // turn off autosimplifcation
	initializeMutationRate(0);
	initializeMutationType("m1", 0.5, "f", 0.0); // neutral
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 50*1000);
	initializeRecombinationRate(1e-8);

}

late()
{
	// manually simplify treeseq at interval of 1000 generations 
	// but leave unsimplified for recent 1000 generations
	if (sim.cycle == 1000) {
		treeSeqSimplify();
	}else	if (sim.cycle > 1000 & sim.cycle % 1000 == 0){
		treeSeqSimplify();
	}

}

1 early()
{
	sim.addSubpop("p1", 10000);
}

200000 early()
{
	sim.simulationFinished();
	sim.treeSeqOutput("slim.trees");
}

```
It generates error message below:
```
// Initial random seed:
3525993084394076220

// RunInitializeCallbacks():
initializeTreeSeq(simplificationRatio = inf);
initializeMutationRate(0);
initializeMutationType(1, 0.5, "f", 0);
initializeGenomicElementType(1, m1, 1);
initializeGenomicElement(g1, 0, 50000);
initializeRecombinationRate(1e-08);

// Starting run at tick <start>:
1 

ERROR (EidosInterpreter::Evaluate_Call): unrecognized function name treeSeqSimplify.

Error on script line 17, character 2:

      treeSeqSimplify();
```

Any suggestions?

**Comment by bguo068** [comment]
Just found it's under `sim` (`sim.treeSeqSimplify()`). Closing it now.

**Comment by bhaller** [comment]
Yes, "functions" are called independently (like, say, `sum()`), whereas "methods" are called on an object of a particular class (like `sim.treeSeqSimplify()`).  If you look in the doc you can find out whether something is a function or a method, what type of object a method needs to be called on, etc.

**Comment by bguo068** [comment]
I apologize for not reading it carefully. Thank you for the explanation. Happy 4th of July!
