### ISSUE TITLE
Vectorized parameters for kernel functions

### ISSUE THREAD

**Issue by silastittes** [MesserLab/SLiM#453]
Hi SLiM team! 
I've been thinking about dispersal as a quantitative trait. It would be a nice feature to vectorize the parameters of the kernels in newer methods like `sampleNearbyPoint`, i.e., `p1.deviatePositions(inds, "reprising", INF, "n", inds.tagF)` or `MAP.sampleNearbyPoint(inds.spatialPosition, 10.0 * SD, "n", inds.tagF)`.  I have no idea how to do this, but I would excitedly watch on the sidelines to see how it would be implemented!

**Comment by bhaller** [comment]
I notice that supplying a vector of values doesn't even throw an error right now; the usual checking doesn't occur, because the arguments defining the kernel are ellipsis "..." arguments that are unchecked, and the existing code doesn't check their count.

**Comment by bhaller** [comment]
Fixed!  @silastittes please try this out and let me know if you see any problems!  :->

**Comment by silastittes** [comment]
Yay, thank you @bhaller! Will do asap!
