### ISSUE TITLE
Segmentation fault with complex mutation matrices

### ISSUE THREAD

**Issue by shz9** [MesserLab/SLiM#55]
Hi everyone,

I've been experimenting with some DNA evolution simulations in SLiM 3.0 and I recently noticed an issue that arises when we try to use complex mutation matrices (i.e. F81) in a **clonal** evolution setting. I tried to get to the bottom of the problem using many different combinations of parameters, and in the end it seems like the problem consistently arises when:

1.  We set the cloning rate > 0.0.
2. We use a mutation matrix that's different from K80 or JC69. Even symmetric mutation matrices result in segmentation fault errors.

**How to replicate the issue:**

This is a snippet of code that should reproduce the error that I'm seeing:

```
initialize() {
        defineConstant("L", 100);
        defineConstant("mode", "F81");
        defineConstant("mu", 1e-5);
        initializeSLiMOptions(nucleotideBased=T);
        initializeAncestralNucleotides(randomNucleotides(L));
        initializeMutationTypeNuc("m1", 0.5, "f", 0.0);

        if (mode == "JC69") {
                mut_matrix = mmJukesCantor(mu);
        }
        else if (mode == "K80") {
                mut_matrix = mmKimura(mu, 2.*mu);
        }
        else if (mode == "symmetric"){
                mut_matrix = matrix(c(0, 3.*mu, 4.*mu, 1.*mu,
                                      3.*mu, 0, 2.*mu, 3.*mu,
                                      4.*mu, 2.*mu, 0, 1.*mu,
                                      1.*mu, 3.*mu, 1.*mu, 0), ncol=4);
        }
        else {
                mut_matrix = matrix(c(0, 3.*mu, 3.*mu, 3.*mu,
                                      2.*mu, 0, 2.*mu, 2.*mu,
                                      4.*mu, 4.*mu, 0, 4.*mu,
                                      1.*mu, 1.*mu, 1.*mu, 0), ncol=4);
        }

        print(mut_matrix);

        initializeGenomicElementType("g1", m1, 1.0, mut_matrix);
        initializeGenomicElement(g1, 0, L-1);
        initializeRecombinationRate(0.0);
}

1 {
        sim.addSubpop("p1", 500);
        p1.setCloningRate(1.0);
}

2000 late() { sim.outputFixedMutations(); }
```

When I run this, I get the following error message:

```
// Initial random seed:
2888021158675

// RunInitializeCallbacks():
initializeSLiMOptions(nucleotideBased = T);
initializeAncestralNucleotides("TAACTACGAACGTCGGAAGG...");
initializeMutationTypeNuc(1, 0.5, "f", 0);
      [,0]  [,1]  [,2]  [,3]
[0,]     0 2e-05 4e-05 1e-05
[1,] 3e-05     0 4e-05 1e-05
[2,] 3e-05 2e-05     0 1e-05
[3,] 3e-05 2e-05 4e-05     0
initializeGenomicElementType(1, m1, 1);
initializeGenomicElement(g1, 0, 99);
initializeRecombinationRate(0);

// Starting run at generation <start>:
1 

Segmentation fault (core dumped)
```

Any help with this would be appreciated.

**Comment by bhaller** [comment]
Ah, interesting.  The bug reproduces for me, so it should be straightforward to find and fix.  I might not have time for a little while, as I'm presently giving a SLiM workshop in Sweden, but I'll fix it as soon as I can.  Thanks for the very clear report.

**Comment by bhaller** [comment]
Hi @shz9.  Got it, fixed.  Sorry for the slow turnaround, it has been a busy time for me.  The fix is now in the github head of the master branch (which you can build now if you like; see chapter 2 of the manual for instructions), and will be included in the next release of SLiM.
