### ISSUE TITLE
Problem installing SLiM

### ISSUE THREAD

**Issue by drwhitehouse** [MesserLab/SLiM#56]
From the documentation:

```
cmake -D CMAKE_BUILD_TYPE=Release -D -DCMAKE_INSTALL_PREFIX:PATH=/path/to/install ../SLiM
make
make install
```
Result:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    -DCMAKE_INSTALL_PREFIX
```

make ignores the variable and attempts to install in "/usr/local/bin".

**Comment by bhaller** [comment]
Hi @drwhitehouse.  Thanks for the report.  There's a collaborator of mine who may address this; I tried to tag her (@brnorris03) on this issue but GitHub won't let me tag her for some reason.  Mysterious.  Anyway, hopefully this will get fixed.  :->

**Comment by bhaller** [comment]
Ah, maybe that tag worked after all; it didn't provide the usual feedback, as I typed it, that it was recognized as a valid tag.  Odd.

**Comment by drwhitehouse** [comment]
I think its a minor typo in the docs:

`cmake -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=/path/to/install ../SLiM`

Seems to have done the trick for me.

**Comment by brnorris03** [comment]
Thanks for catching that, will fix!

**Comment by brnorris03** [comment]
> Hi @drwhitehouse. Thanks for the report. There's a collaborator of mine who may address this; I tried to tag her (@brnorris03) on this issue but GitHub won't let me tag her for some reason. Mysterious. Anyway, hopefully this will get fixed. :->

That is my username, but I am not a collaborator, indeed.

**Comment by bhaller** [comment]
Hi @brnorris03.  Thanks for the pull request, accepted.  And now GitHub completes your handle properly, for whatever reason.  :->  @drwhitehouse, thanks for the report!
