### ISSUE TITLE
Self Test Issues

### ISSUE THREAD

**Issue by drwhitehouse** [MesserLab/SLiM#58]
As far as I can tell, SLiMs self tests (slim -testEidos / slim -testSLiM) use hardcoded paths to generate files that are used for testing. These are not cleared up afterwards.

If you use the self tests then:

1./ your /tmp will contain a large number of slim related files which may or may not be an issue.
2./ more importantly, if another users has already run self tests, and you run them again, some of the files will have the same names, and the 2nd user won't be able to overwrite them.

When this occurs, it seems to generate a segfault.

This causes the tests to fail and can lead you to thinking that you have wasted a fair bit of time trying to make a working binary.

You may even be unlucky enough to delete it all and try rebuilding several times again, only to find that the self tests would have worked if you had cleared /tmp before running them...

**Comment by bhaller** [comment]
Yes, this should be cleaned up.  There's also a related issue that if /tmp is unwritable (which is apparently the case on some systems!) then the self-test fares poorly.  I'm not concerned about the files left in /tmp – they get cleaned out by the system eventually, and this sort of usage of /tmp is quite standard – but your issue #2 should certainly be fixed.  Thanks.

**Comment by bhaller** [comment]
Hi @drwhitehouse.  This should now be fixed; I have committed it to Github, so you can get it by building the current Github head of the master branch (instructions are in chapter 2 of the manual).  It would be great if you could arrange a test of it in the environment where the bug occurred for you; please let me know the outcome if you do.  Thanks for the report!

**Comment by drwhitehouse** [comment]
I have tested this and I can confirm that I was unable to replicate the issue which lead to me reporting the bug. Thanks very much.

**Comment by bhaller** [comment]
Thank you!
