### ISSUE TITLE
Segmentation fault with chromosome painting

### ISSUE THREAD

**Issue by GertjanBisschop** [MesserLab/SLiM#59]
Hi,

I have been running a script uses mutations to track the hybrid index of two populations upon a secondary contact event. I have to track mutations since fitness is based on the hybrid index. However during certain runs segmentation faults (core dumped) occur.

I think that you should be able to reproduce the error with the following information.

```
// Initial random seed:
1889190714725

// RunInitializeCallbacks():
initializeMutationRate(0);
initializeRecombinationRate(1e-05);
initializeMutationType(2, 0.5, "f", 0);
initializeGenomicElementType(1, m2, 1);
initializeGenomicElement(g1, 0, 149999);

// Starting run at generation <start>:
1

Segmentation fault
```

Script:
```
initialize() {
	
	defineConstant('selection_strength', 0.015);
	defineConstant('migration', 0.001);
	defineConstant('seq_len', 1.5e5);
	defineConstant('recombination_rate', 1e-6);
	
	initializeMutationRate(0.0);
	initializeRecombinationRate(1e-5);

	// m2 mutation for pop2 = mutation labeling individuals from pop2
	//mutation have fixed effect size 0.0 == neutral
	initializeMutationType("m2", 0.5, "f", 0.0);
	
	//make sure fixed mutations are still counted with countMutationsOfType(m2)
	m2.convertToSubstitution = F;
	
	//genomic element g1 only contains mutations of type m2	
	initializeGenomicElementType("g1", m2, 1.0);
	//whole genome can potentially carry a mutation of type m2
	initializeGenomicElement(g1, 0, asInteger(seq_len)-1);
	
}

function (float)FitnessFunction(float HI, float S){
	
	return 1 - S*(4*HI*(1-HI));
}

1 {
	sim.addSubpop("p1", 2000);
	sim.addSubpop("p2", 2000);
	p1.setMigrationRates(p2, migration);
	p2.setMigrationRates(p1, migration);
}


1 late(){
	//label all genomes of individuals from pop2 with an m2 mutation
	p2.genomes.addNewMutation(m2, 0.0, 0:(asInteger(seq_len)-1));
}

1: late(){
	for (pop in c(p1, p2)){
	inds = pop.individuals;
	//phenotypes == hybriditity index
	phenotypes = inds.countOfMutationsOfType(m2)/(2*seq_len);
	inds.fitnessScaling =FitnessFunction(phenotypes, selection_strength);
	//save the hybriditiy index as in the by SLiM provided tagF variable slot for each individual		
	inds.tagF = phenotypes;}	
	}

1000 late(){sim.simulationFinished();}
```

**Comment by bhaller** [comment]
Interesting.  I'm on the road at present, but will look into it soon.  Thanks.

**Comment by bhaller** [comment]
Hi Gertjan.  The model you supplied seems to run with no crash for me, with the random number seed of 1889190714725 that you quoted.  So I'm not sure what's going on here; I need a reproducible case.  Given a random number seed that crashed once, like 1889190714725, does it crash reproducibly for you with that seed?  If so, you could dig up the crash log and post that here, which would give me an idea of where the crash occurs, at least.

The model is fairly large and takes a while to run.  If there is no reproducible case, and I just need to run it a bunch until one of the runs crashes, then more info would be helpful.  (1) Do the crashes generally occur at the beginning of a run, near the end, or at a seemingly random point?  (2) If you scale the model down (use a shorter chromosome length), do the crashes still occur, just as often, or is this size of model necessary to get the crashes?  (3) Could the crash be related to memory usage limits?  I.e. are you running on a cluster with a memory limit than some runs might be exceeding, causing a memory allocation failure and a crash?  The model does seem to use quite a lot of memory, so I can see that being an issue.

Also: I assume you're using the current release version of SLiM, 3.3?

**Comment by GertjanBisschop** [comment]
Hi Ben,

Thanks for getting back so quickly.

I have not tested whether this random number seed will crash reproducible. This is annoying and sorry about that, I should have checked this. I am away at the moment. Once back, I will try to reproduce the crash and dig up the crash log.

(1)Crashes definitely all occur at the beginning of a rum (first 200 generations).
(2) will check whether chromosome length affects the chance of crashing
(3) I have had models running out of memory on the cluster I use, however this produces a different error message, so I was assuming this was not the issue.

And lastly, I indeed am using the current release version.

**Comment by GertjanBisschop** [comment]
Hi,

I can't seem to replicate the error consistently, even with the same random bumber seed. And I have not been able to get any useful information out of the core dump. 
I will try and run the same script on a different cluster if I have the opportunity. If the same error were to occur on a different cluster, I will report this. But I think this issue can be closed for now.

Thanks for taking the time to respond and to test the issue yourself as well.

**Comment by bhaller** [comment]
Hi Gertjan.  Hmm.  Well, it is a crashing bug, and as such is serious and should be fixed.  I don't see a way to get a handle on it at the moment; but I'm not inclined to close it just yet.  If you can find out more about it, that would be very helpful.  If time goes by and nobody else reports it and we can't find a way to reproduce it, then I'll close it; but right now I remain concerned about it.

**Comment by bhaller** [comment]
Well, given no news on this and no other reports of such crashes, I'm going to close this bug.  If you can get it to reproduce, or if it is still causing you problems, please comment and I'll re-open the bug.  Thanks.
