### ISSUE TITLE
QtSLiM Travis-CI builds fail on macOS

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#65]
Hi @brnorris03.  I've accepted your pull requests and it looks like QtSLiM builds on Travis-CI using your CMake stuff – but only for Linux, not for macOS.  I think we discussed this a bit on the old pull request #52, but didn't really get anywhere.  I guess macOS is complicated because Qt could be installed by various routes (homebrew, macports, maybe also conda or something?), leading to different paths that need to be used for headers and linkage.  I've opened this issue since the pull request is now closed.  This is not presently urgent, but will become more important as we get toward wanting to merge the qtslim branch into master – maybe in two months or so?

**Comment by bhaller** [comment]
An example of a build that fails: https://travis-ci.com/MesserLab/SLiM/builds/142009933.  It seems to fail with this log:

```
CMake Error at /usr/local/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:15 (message):
The imported target "Qt5::Core" references the file
"/usr/local/.//mkspecs/macx-clang"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
"/usr/local/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake"
but not all the files it references.
```

I'm not sure what to think about that, but I would note that on macOS it is more usual, I think, to build with gcc, which is an Apple alias to clang in some manner.  Anyway, that's about all I know about the problem.  :->

**Comment by brnorris03** [comment]
I wasn't able to reproduce the problems on my Mac, unfortunately! I follow the same steps but it works fine, probably something else in my environment? Are you able to reproduce it locally?

**Comment by bhaller** [comment]
If I try a local build, I get a different error:

```
darwin-447:~/Documents/Research/MesserLab/SLiM_project/QtSLiM_build bhaller $ cmake -DCMAKE_BUILD_TYPE=Release -D BUILD_QTSLIM=ON ../SLiM_Qt
CMAKE_BUILD_TYPE is Release
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework   
CMake Error at CMakeLists.txt:135 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/bhaller/Documents/Research/MesserLab/SLiM_project/QtSLiM_build/CMakeFiles/CMakeOutput.log".
```

I have no idea what to do about that either.  :->

**Comment by brnorris03** [comment]
Remind me which Qt install you used? The Mac native (or brew, ports)?

**Comment by bhaller** [comment]
I have Qt 5.9.8. installed via their installer (i.e., https://doc.qt.io/qt-5/gettingstarted.html).  (I thought I did it through macports, but apparently not.)  Probably the online installer, not the offline installer; I'm not sure but I'd be surprised if that makes a difference.  I notice that they have some details about the macOS installation here: https://doc.qt.io/qt-5/macos.html

**Comment by bhaller** [comment]
I just sent a message to the Travis-CI folks asking if they know why the macOS build is failing; perhaps they will have an idea, they've been helpful to me in the past.

**Comment by bhaller** [comment]
Here's what the Travis-CI folks wrote back to me:

> Hey Ben,
> 
> Thanks for the email. We are sorry to hear about the problem you are having.
> 
> Have you tried running the build in the debug mode? With access to the VM and the intimate understanding of the code base, you are in the best position to troubleshoot this issue further. The debug mode is explained in https://docs.travis-ci.com/user/running-build-in-debug-mode/
> 
> Let us know if you need further assistance. Thank you.
> 
> Best,
> Mustafa

I have not attempted the "debug mode".  :->

**Comment by bhaller** [comment]
OK, the build issue on Travis is apparently a bug, but there's argument as to whether it is homebrew's bug, cmake's bug, or Qt's bug (sigh), and so it apparently has not been fixed.  Here is the relevant issue on homebrew, which has been closed even though it has not been fixed:

https://github.com/Homebrew/legacy-homebrew/issues/29938

I am trying the solution given by "apathyboy" in that thread:

`export PATH=/usr/local/opt/qt5/bin:$PATH`

Regarding the qmake problem I have been seeing with building locally on macOS (see above), that is a different issue, apparently a result of Qt not being installed in a standard place (I don't know where the standard place would even be).  This can be worked around by providing the Qt5_DIR environment variable to cmake, like so:

Qt5_DIR=/Users/bch59/Qt5.9.8/5.9.8/clang_64 cmake -D BUILD_QTSLIM=ON ../SLiM_Qt

Just substitute the path to the clang_64 subdirectory of your Qt install, wherever it may be.

Woo-hoo!  The solution from "apathyboy" worked!  Closing this bug!

**Comment by brnorris03** [comment]
Awesome, thank you!!

**Comment by bhaller** [comment]
I finally found a relevant hit in google – in Japanese.  But that was what broke it for me.  :->
