### ISSUE TITLE
outputFull does not record (or, reload?) pedigree IDs

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#70]
I don't know if outputFull does not record pedigree IDs, or if it doesn't reload them, but either way: saving out the population state with outputFull and then reloading it will end up with individuals with *different* pedigreeIDs.

Having them agree would be necessary for matching individuals across segments of a simulation that is run in pieces, (eg simulate->outputFull->reload->simulate->...).

However, outputting and reloading from tree sequences *does* preserve pedigreeIDs, so this is not a serious problem - but perhaps a gotcha. I thought you should at least know about this.

**Comment by bhaller** [comment]
Yeah.  As the doc discusses, there are actually lots of things that outputFull() doesn't save; it's a bigger problem than just pedigree IDs.  Which should be fixed.

**Comment by bhaller** [comment]
This bug is higher priority now that pedigree tracking is always enabled.

**Comment by bhaller** [comment]
This is now fixed, although some testing remains to be done.  Note that writing out of pedigree IDs is optional, and is off by default, to preserve backward compatibility – not so much with SLiM itself (why would someone write out a new-format output file and then read it in with an old version of SLiM?), but with other scripts/programs that might parse SLiM's outputFull() formatted output for post-processing.  To avoid breaking such scripts when people upgrade to SLiM 3.5, the new pedigree ID field needs to be off by default.  If people want it, it's easy to turn on.  :->

I did not add in saving of other state information – tag and tagF, setValue() key/value pairs, etc.  There's lots of side state on objects now, and at present the file I/O stuff is just not set up to persist it easily, so fixing that would be a much bigger project.  (You can open an issue on that if you want, but I'm certainly aware of it.  :->)
