### ISSUE TITLE
avoid extra copy on load of tree sequences?

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#72]
When loading a tree sequence, SLiM  [makes an extra copy of it](https://github.com/MesserLab/SLiM/blob/cb387d398d8992f256dd2e5036db83beea67bd74/core/slim_sim.cpp#L8075) due to a restriction that - I think - has been removed.  According to [this note](https://github.com/tskit-dev/tskit/blob/92fe9c04a27385401732a698843756aa797bacdd/c/tskit/tables.c#L40), `tsk_table_collection_load( )` now [allocates columns](https://github.com/tskit-dev/tskit/blob/92fe9c04a27385401732a698843756aa797bacdd/c/tskit/tables.c#L5899) by default, which is I think what we needed here?

This could be the cause of some early spikes in memory usage we've seen.

**Comment by bhaller** [comment]
Yes, this could probably be fixed.  The memory spike shouldn't be much larger than the size of the .trees file being loaded, though, right?  So unless you're working with really huge .trees files, this is unlikely to be a big deal.  But it'd be nice to fix it just for polish, in any case.

**Comment by petrelharp** [comment]
The first step, though, is to update the tskit code.

**Comment by bhaller** [comment]
Oh, did that improvement not already get rolled into SLiM?  I thought this got fixed quite a while ago now.  Well, do a PR to bring SLiM up to the current tskit whenever you want.

**Comment by petrelharp** [comment]
It did get updated! But, there's been movement since then...

**Comment by bhaller** [comment]
Hi @petrelharp.  What's the status on this?  I'm starting to think about releasing SLiM 3.4.  Should a merge from tskit into SLiM happen before that happens?

**Comment by petrelharp** [comment]
I haven't done anything about it yet, and won't be able to get to it immediately. So, I'd like to do it, but not sure I can promise it.

**Comment by bhaller** [comment]
OK.  If SLiM 3.4 ships without this, that seems fine to me; I'm not aware that anyone actually cares about it.  Let me know if you'd like me to wait, though.

**Comment by bhaller** [comment]
I believe this has been fixed; not sure why it didn't get auto-closed when the tskit PR was merged.  @petrelharp, this is fixed, right?
