### ISSUE TITLE
Adding fixed value onto selective coefficient of type "g" mutations

### ISSUE THREAD

**Issue by bioXiaoheng** [MesserLab/SLiM#73]
Hi Ben,

I'm trying to simulate overlapping functional regions, and got stuck at defining the selective coefficients for the mutations in overlapping part.

So I want to simulate a length>1 functional element A with arbitrary fixed selective coefficient s_a, and for the gene elements (exons, introns, etc.) it sits in, I want both the deleterious and neutral mutations (m1 and m2) in regions covered by A have s_a added onto their initial s, and started with defining new mutation types m1a and m2a for those in the overlapping part.

I was going to use fitness() function, and realized 
`fitness(m1a){return relFitness + s_a; }`
would add an s_a every generation instead of just once. So I attempted to use an indicator/boolean variable to show the addition has (or has not) been done:
```
initialize(){
...
addflag=0;
}   
fitness(m1a){
  if(addflag == 0){
    return relFitness + s_a ; 
  }else return relFitness
}
```
But everytime I run it, it says
```
ERROR (EidosSymbolTable::_GetValue): undefined identifier addflag.
Error on script line 70, character 28:
    if(addflag==0){
       ^^^^^^^
```
I then tried replacing `addflag=0;` as `defineConstant("addflag",0);`, but then I'd get
```
ERROR (EidosSymbolTable::SetValueForSymbol): identifier 'addflag' cannot be redefined because it is a constant.
```

And now I'm confused and not sure what to do next... Is there a better way to do it?

**Comment by bhaller** [comment]
Hi!  Overall, I would recommend that you go slower and work through more of the recipes in the manual, or attend a SLiM workshop if you can; it seems like you have several conceptual misunderstandings.  First of all, fitness functions do not change the selection coefficient of mutations, they just change the fitness effect of mutations for a given individual in a given generation; so your initial approach might work just fine, and would certainly not add s_a over and over to produce a larger and larger change.  The chapter on fitness() callbacks has many examples that should make this more clear.  Second, if you just want a region of the genome that draws selection coefficients from a different DFE than other parts of the genome – which sounds like what you want – then a fitness() callback is overkill and would be inefficient.  This sort of thing is precisely what the genomic structure of mutation types, genomic element types, and genomic elements is for.  So you should probably review that chapter and work through those recipes to build your understanding of SLiM's architecture.  Third, yes, you have to decide whether a given symbol is a variable (in which case you can change it) or a constant (in which case you can't), and variables have limited scope in SLiM (whereas constants are globals); if you need a variable that you can access globally, you can use tag property values or setValue()/getValue().  Again, this is all discussed at length in the manual; but in any case I don't think the correct approach to your problem would require the addflag symbol you're trying to define.

If you have further questions, please ask them on the slim-discuss mailing list, not by filing an issue in GitHub; issues are for reporting bugs, not for asking questions.  I'm going to close this issue now.  But before asking further questions on slim-discuss, please do spend some time studying the manual and getting to know SLiM; I have put a great deal of work into it precisely to help new SLiM users get up to speed with these sorts of basic concepts.  :->  Or attend a SLiM workshop; there is one scheduled for May at Harvard, and there will be others in future.
