### ISSUE TITLE
`qnorm()` and similar functions, for truncation selection? 

### ISSUE THREAD

**Issue by vsbuffalo** [MesserLab/SLiM#74]
I'd like to implement truncation selection by providing a tail probability to the command line. To do so, we'd need a function like R's `qnorm()`, which given a probability (and Gaussian parameters) will return the quantile of that probability. Is this something that you'd consider merging in to SLiM? 

GSL has [the required functions](https://www.gnu.org/software/gsl/doc/html/randist.html#the-gaussian-distribution) that could be wrapped much like `rnorm()` is. If you're welcome to the idea, I'd be happy to work on it and submit a pull request.

**Comment by bhaller** [comment]
Adding this would be fine, yes.  It would be straightforward for me to do it, and I'd be happy to.  If you'd like to take a crack at it, feel free, but the Eidos code is pretty hairy.  :->  If you start from dnorm's implementation (maybe better than rnorm for these purposes), and do all the same things, you might get there.

Note that the GSL code is included inside SLiM's code; it does not link to the GSL.  Note also that the GSL code included in SLiM is an *incomplete* copy, and the requisite code to implement qnorm() might not be there, in which case it would need to be copied over from the standard GSL code base, which is generally easy to do but requires fixing #includes and such.

If you decide you don't want to do it, just let me know and I'll do it; I could probably turn in around by the end of the weekend.

**Comment by vsbuffalo** [comment]
Thanks Ben! I have implemented it, and am just finalizing the Eidos testing code before I push. 

I would like to add relevant documentation for `qnorm()`, but can't seem to find the best way to do this. In what places should I add the documentation for this function?

**Comment by bhaller** [comment]
> Thanks Ben! I have implemented it, and am just finalizing the Eidos testing code before I push.

  Groovy.

> I would like to add relevant documentation for `qnorm()`, but can't seem to find the best way to do this. In what places should I add the documentation for this function?

  That has to be done on my end; it's a Pages document that is used to generate the manual PDF, and it is not on GitHub.  If you could send me text to be used for the documentation (email it or post it here), I'll see to incorporating it.

**Comment by mufernando** [comment]
Hi @bhaller, related to this issue, did you consider adding a `quantile` function to Eidos? That would be essential for simulating truncating selection. Let me know if you'd consider it and I can open a new issue.

**Comment by bhaller** [comment]
Hi @mufernando.  I'm amenable to adding a quantile function.  However, looking at the doc for quantile() in R, it's pretty complex and the mathematical details of all the different types of quantiles, etc., are beyond me.  If you and/or Peter can make those details crystal clear (or write the necessary C code to implement it, even better!), and supply test cases that can be used to validate that the behavior is correct, then I'm happy to add it.
