### ISSUE TITLE
eidos no longer takes FIFOs

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#77]
Until recently, one could run simple commands through eidos on the command line like so:
```
eidos <(echo "2 + 3;")
# 5
```
What's going on here is that the `<( ... )` syntax in bash makes a [named pipe](https://vincebuffalo.com/blog/2013/08/08/using-names-pipes-and-process-substitution-in-bioinformatics.html) (see the bit on "process substitution"), and the output of the command (here, the text "2 + 3;") is put in a special file-like object with a name like `/dev/fd/63`; this can be treated just like a file by many programs.  Note that this works on osX as well as linux.

However, ever since 91fbb3d2b4ac005ddc0076156dfae1b8b0596bcd, this resulted in the error message
```
ERROR (main): input file /dev/fd/63 is not a regular file (it might be a directory or other special file).
```

Was there a problem this was avoiding? Being able to pipe scripts in was really handy for quickly debugging things without a GUI (e.g., remotely). It also made it possible to do things like
```
slim <(cat script.slim | sed -e 's/CONST/20/g')
```
(I know it'd be easier to do this example with a `defineConstant( )` and a `-d` flag, but you get the idea.)

**Comment by bhaller** [comment]
Whoops.  Thanks for the report, I wasn't aware of this regression.  I imagine I can manage to fix both bugs at the same time if I set my mind to it.  :->  Hold on, I'll try to do this today.

**Comment by bhaller** [comment]
OK, both of these syntaxes should work now, for both eidos and slim:

./eidos <(echo "2 + 3;")
echo "2+3;" | ./eidos

Please let me know if you see any problems.

**Comment by petrelharp** [comment]
Looks good! Thanks!!

**Comment by petrelharp** [comment]
>  echo "2+3;" | ./eidos

Oh, that's great!
