### ISSUE TITLE
Add "add mutations" option to treeSeqOutput( )

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#8]
To make it easier on folks, we should add a simple argument (the neutral mutation rate) to the tree seq output function, that will (a) load the tables into a tree sequence, (b) add mutations, and (c) *then* write out the .trees file.

This depends on some other things: currently I don't think we have the ability in tskit to *add* mutations to an existing file (as opposed to making a whole new sites/mutations tables).

**Comment by bhaller** [comment]
Hmm.  It's so easy to do in Python anyway; and there are all sorts of different ways that people might want to do it (different mutational models, mutation rate maps, etc.).  I'm not sure that it makes sense for SLiM to try to get into the business of doing this sort of thing.  I dunno.

**Comment by petrelharp** [comment]
Yes, definately.  I'll close this.
