### ISSUE TITLE
"Check script" from command line?

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#82]
QtSLiM has a "Check script" option. I'd love to use this from the command line in stdpopsim unit tests! Is that available somewhere, and I just missed it?

**Comment by bhaller** [comment]
If you invoke slim with a script at the command line, the first thing it does is parse the script and give an error message if there's anything that doesn't pass syntactically.  So in effect it already does "check script", as the first thing it does.  Are you asking for a command-line option that would do that check, but then not actually run the model?

**Comment by grahamgower** [comment]
> Are you asking for a command-line option that would do that check, but then not actually run the model?

I had imagined that's what the "check script" option is doing. But I think I can do this with slightly more correctness garuantees in my specific case. (After setting up the simulation, exit if a specific flag is set with `-d`. This will also check that the setup code runs properly.)

**Comment by bhaller** [comment]
Ah, yes, you should be able to do that with -d with no problem.  It's a reasonable and easy feature request, though, so feel free to reopen it if you decide it would be better for SLiM to support this itself.  (But maybe it is pretty specific to your situation, so I'll leave that judgement to you :->.)

**Comment by grahamgower** [comment]
Thanks Ben. You're already putting in a heroic effort with all the QtSLiM stuff, so I think this feature request can be ignored!

**Comment by bhaller** [comment]
Cheers.  :->  By the way, I gather you have been doing amazing things with stdpopsim and SLiM.  I don't know much about it yet, but @petrelharp tells me a wave of documentation will be coming online soon that will explain it all to me; I'm looking forward to reading that and catching up!  :->  It sounds very useful and cool; please don't hesitate to ask for additions to SLiM that would make your life simpler.
