### ISSUE TITLE
Need an incremental sort algorithm

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#85]
For reasons having to do with showing progress and allowing user cancellation during a long sort operation, I need an incremental sort algorithm in QtSLiM.  I believe I have found exactly the algorithm I want, at:

http://larshagencpp.github.io/blog/2016/04/23/fast-incremental-sort

He shows several algorithms there; his "Incremental Quicksort" algorithm appears to me to be ideal for my purposes.  Unfortunately, the code he presents is incomplete; there are "..." ellipses in two places that I'm not sure how to fill in.  I'm just not that experienced of a C++ programmer; I don't really know how to do template programming and such.  So I need help from someone with strong C++ chops.  For such a person, I'm guessing this is a matter of perhaps an hour's work, to fill in the ellipses (which I think are mostly just constructor/destructor type stuff) and do a quick test (scramble a vector of 100,000 doubles and then incrementally sort them by asking for the next sorted double 100,000 times, for example).

If you have a bit of time to spare, @molpopgen, this seems like a perfect fit for you, and perhaps you'll enjoy the puzzle of working out the details of the algorithm.  :->  If not, perhaps @grahamgower or @petrelharp or @brnorris03 or @vsbuffalo knows someone who wants to take a crack at it?  You would have my undying gratitude.  :->

**Comment by molpopgen** [comment]
So, some of the `...` mean "insert standard boiler plate here", such as in the iterator definitions.  Pre-C++11, this meant inheriting from `std::iterator`.  But now, one does it a bit more manually: https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/.

I believe that the `...` in the `private:` block mean to copy/paste the declarations shown near the top, which are the internal state of the class.

**Comment by molpopgen** [comment]
For the iterator boilerplate, the required `typedef` are taken from the template parameter type of the outer class:

```cpp
class iterator {
using iterator_category = typename I::iterator_category
... // ;)
};
```

Once the iterator is defined, then `first` and `last` should have type `iterator` and not `I`, but I'd have to do actual work to confirm or deny that.

**Comment by bhaller** [comment]
@molpopgen Do you have the time/inclination to do that actual work?  That would be very helpful.  :->  I'm really out of my depth here.

**Comment by molpopgen** [comment]
I can take a quick look. If it comes together quickly, then I'm happy to help out. It doesn't seem too hard if I understand the examples correctly

**Comment by molpopgen** [comment]
There may be errors in this implementation.  At the very least, there are problems with class member initialization that don't warrant the `...` and there is the possibility of UB.  For example, `vector<T>::back` is called w/o first checking that the vector isn't empty.

It may be smoother to go back to the algorithm description linked to on Wikipedia and start from there.

**Comment by bhaller** [comment]
Hmm.  Well that's a bummer.

**Comment by molpopgen** [comment]
I checked the poster's github account and didn't find the actual code used.  To me, that's not a good sign.  The post is definitely more "hints" than "how to".

**Comment by bhaller** [comment]
> I checked the poster's github account and didn't find the actual code used. To me, that's not a good sign. The post is definitely more "hints" than "how to".

Yeah, I already checked his github, and emailed him to ask about it too (no reply).  He seems to have vanished from the coding scene a couple of years ago.  It's really a bummer, though, because that algorithm is exactly what I need, and I haven't found anything comparable elsewhere.  :-<

**Comment by bhaller** [comment]
OK, I figured it out after much head-scratching.  See https://github.com/MesserLab/incsort.  Closing.
