### ISSUE TITLE
Need an installation script for QtSLiM on Linux

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#87]
Splitting this action item out from #78, which is more of a discussion topic than an "issue".

QtSLiM should have the same icon as SLiMgui, and should own the .slim extension so that double-clicking a .slim file launches QtSLiM and opens the file.  These things can't be too hard, other apps on Linux seem to manage them.  This should be either a separate post-processing script (non-optimal) or a final step in `make install` that sets up the app automatically.  (Does `make install` even do the right thing on Linux now?  Does it actually "install" the app in some standard location where the OS finds it and knows about it?  That would also be good.)

Associating an app icon: https://askubuntu.com/questions/894990/how-to-change-an-icon-in-16-04

Associating a file extension: https://askubuntu.com/questions/538299/globally-associate-file-type-with-certain-application

I believe @petrelharp has volunteered to give this a whirl.  It would be good to get to it fairly soon; QtSLiM is approaching completion and I'd like to release it!  :->

**Comment by bhaller** [comment]
BTW, @petrelharp, I have pretty much figured this out.  Complicated but not insurmountable.  I only know how to do it for Ubuntu/GNOME; no idea if the same steps will work on other distros, seems like there's a lot of variation in how this stuff is done, and standards are not followed well, and there's a lot of bugs.  :-<  Several of the steps require `sudo`; I think I'll just lay out the steps in the manual, rather than providing a shell script that would have to be run with `sudo`, at least for now.  Let the dust settle a bit.

**Comment by petrelharp** [comment]
Sorry I flaked on this, but I think the instructions in the manual are a good way to go. I don't know the "right" way to do this (that works across distros), anyhow.

**Comment by bhaller** [comment]
Closing this since it is resolved for the time being.
