### ISSUE TITLE
small documentation bug

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#88]
This excerpt from the manual sounds backwards: 

> Note that by default in WF models, all mutations of a given mutation type will be converted into Substitution objects when they reach fixation, for efficiency reasons. If you need to disable this conversion, to keep mutations of a given type active in the simulation even after they have fixed, you can do so by setting the convertToSubstitution property of MutationType to T .

ht @cjbattey

**Comment by petrelharp** [comment]
Wasn't sure if this was the right place for documentation bugs. Thanks!

**Comment by bhaller** [comment]
Sure.  For a long time I didn't use GitHub issues at all, but I've gotten used to them, to the point where now they seem simple and useful.  :->
