### ISSUE TITLE
qmake build of QtSLiM does not run

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#89]
Building and running QtSLiM under Qt Creator, which of course uses qmake under the hood, works fine.  But building QtSLiM at the command line with qmake, such as with `qmake ../SLiM_Qt` or (if qmake is an alias to qtchooser) `qmake -qt=qt5 ../SLiM_Qt`, succeeds but does not run.  You get a launch-time error, like:

./QtSLiM: error while loading shared libraries: libeidos.so.1: cannot open shared object file: No such file or directory

I'm not sure what's going on here.  The cmake build of the same sources works fine.  I think it may be the case the cmake is building all of the sub-components as statically linked libraries, so the linkage is resolved at compile time, whereas qmake is building the sub-components as dynamically linked libraries, and then for some reason the dylibs can't be found at launch (maybe they're not in the search path, because they haven't been installed?).  Probably the right fix is to change the `.pro` files that configure the qmake build to use static linkage instead; that's probably what we want anyway, even without this problem.  I'm not sure how to do that, however.

**Comment by grahamgower** [comment]
You're exactly right about what's going on. It can be forced to run by adding all the shared lib dirs to LD_LIBRARY_PATH. There are plenty of qt projects out there in the world, so this must be solvable without static linking and without installing the dynamic libs. But if you get it to work using static libs, that will probably be the least hassle in the long term.

**Comment by bhaller** [comment]
I kind of suspect that the root of the problem is the gsl sub-project, which collides with the installed gsl library on my machine.  I haven't tested that hypothesis yet, though.

**Comment by grahamgower** [comment]
Any reason it can't just be linked to the system gsl instead? Do you have changes to the gsl library, or do you just want to pin the version?

**Comment by bhaller** [comment]
We just want to avoid external dependencies, to make it simpler for people to build SLiM.

**Comment by bhaller** [comment]
Not sure why the commit didn't close the issue; maybe because it's on a branch?  Anyway, fixed, closing.
