### ISSUE TITLE
Ctrl-W errors (multiply defined?) in QtSLiM

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#92]
When I try to close a QtSLiM window in the usual way (control-w), it does nothing, and tells me (in the console):
```
QAction::event: Ambiguous shortcut overload: Ctrl+W
```
*edit:* Also Ctrl-Q:
```
QAction::event: Ambiguous shortcut overload: Ctrl+Q
```

**Comment by petrelharp** [comment]
btw, maybe you should add a "label" for QtSLiM (over on the right)?

**Comment by bhaller** [comment]
Huh.  Strange; works fine for me on Ubuntu, last I checked.  Any idea why it would be different on Debian (if that is indeed the root of the problem)?  What version of Qt are you running against?  I'll test this again next time I'm on Ubuntu.

**Comment by bhaller** [comment]
OK, I can reproduce this on Ubuntu.  The key is to have more than one QtSLiM window open.  In that situation, Qt is not sure which window to send the keyboard shortcut to, for some reason.  Investigating.

**Comment by bhaller** [comment]
This has been fixed.  Thanks for the report, good bug.  Action dispatch in Qt is one of the weakest parts of its design, but I think I've got things nailed down properly now.
